-- Generated by `tools/iapply_cells.py` (aggregator mode) of the development repository (not part of this release).
import OmegaBound.ADVXXZGeneralRowsCellsR2X0
import OmegaBound.ADVXXZGeneralRowsCellsR2X1
import OmegaBound.ADVXXZGeneralRowsCellsR2X2
import OmegaBound.ADVXXZGeneralRowsCellsR2X3
import OmegaBound.ADVXXZGeneralRowsCellsR2X4

open scoped BigOperators
open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

def rowsR2XQ30Num (p : Fin 126) : ℕ :=
  match p.1 with
  | 0 => 12658877683669481093
  | 1 => 519225283135796864493
  | 2 => 118649417368988337409
  | 3 => 0
  | 4 => 60237915668509448791
  | 5 => 12977417917102944193
  | 6 => 447144348842507617228
  | 7 => 5273419651091384500788
  | 8 => 4419038362818089808961
  | 9 => 1494184677028524393429
  | 10 => 0
  | 11 => 827606793556790952865
  | 12 => 0
  | 13 => 4115087810734017123768
  | 14 => 0
  | 15 => 0
  | 16 => 1273602710135059395774
  | 17 => 4038910073382436085212
  | 18 => 121459264802927715747
  | 19 => 269409399681716962215
  | 20 => 12809591565579182598
  | 21 => 12780239759030350201
  | 22 => 478736972663722908292
  | 23 => 571388281116795498497
  | 24 => 0
  | 25 => 0
  | 26 => 12734147718114596096
  | 27 => 410188951758260703357
  | 28 => 1518551613475499816728
  | 29 => 3576904013419605084429
  | 30 => 0
  | 31 => 0
  | 32 => 1088736614354616280456
  | 33 => 0
  | 34 => 3832242790116312020621
  | 35 => 0
  | 36 => 0
  | 37 => 1199716783150340381532
  | 38 => 4090738659259151487085
  | 39 => 123329982302845651328
  | 40 => 270100665363280361399
  | 41 => 12808876961501426972
  | 42 => 12665369261299954737
  | 43 => 516746425485351900265
  | 44 => 128301516589391068051
  | 45 => 0
  | 46 => 114816981100708931642
  | 47 => 13149433662969284801
  | 48 => 448483378239053146319
  | 49 => 5328895399663098793346
  | 50 => 4954861799617310946386
  | 51 => 2615180776916876350594
  | 52 => 0
  | 53 => 794432696613135036450
  | 54 => 0
  | 55 => 4807251685793527399218
  | 56 => 0
  | 57 => 0
  | 58 => 1110881136779131125992
  | 59 => 4393522489001141954888
  | 60 => 63669678783690866744
  | 61 => 309993823972129684034
  | 62 => 12732714005335869742
  | 63 => 12770267134481699900
  | 64 => 478481159352614609622
  | 65 => 594340496844420917637
  | 66 => 0
  | 67 => 115693691289681464727
  | 68 => 13151429030038670925
  | 69 => 415624575535446512153
  | 70 => 1574435526997233490390
  | 71 => 4530186682808246448024
  | 72 => 2561071307591482699348
  | 73 => 0
  | 74 => 1062314706000691774566
  | 75 => 0
  | 76 => 5144534598457998152457
  | 77 => 0
  | 78 => 0
  | 79 => 155288620858693985952
  | 80 => 5136522852468240067354
  | 81 => 0
  | 82 => 349246104090666625784
  | 83 => 12668237047467514967
  | 84 => 12865673585853744445
  | 85 => 430484418321650182702
  | 86 => 804165083905211640357
  | 87 => 0
  | 88 => 0
  | 89 => 12740118646329043229
  | 90 => 366022981057277201058
  | 91 => 0
  | 92 => 3065607975378335663265
  | 93 => 0
  | 94 => 0
  | 95 => 1224284683038802814835
  | 96 => 0
  | 97 => 4195555169318904151769
  | 98 => 0
  | 99 => 0
  | 100 => 1063937674992984180809
  | 101 => 4442249601917217993542
  | 102 => 62204734018523687127
  | 103 => 313129922193629984917
  | 104 => 12742939624886019223
  | 105 => 12874699203349043834
  | 106 => 429637025812048452576
  | 107 => 804064679020742660737
  | 108 => 0
  | 109 => 54460320567939691680
  | 110 => 12976632790700316867
  | 111 => 372774139697425221302
  | 112 => 0
  | 113 => 3522408307692657295539
  | 114 => 1667725837526705243304
  | 115 => 0
  | 116 => 1227461846063919505194
  | 117 => 0
  | 118 => 4767078188025067741289
  | 119 => 0
  | 120 => 0
  | 121 => 85273126107993433232
  | 122 => 5249528033441247023108
  | 123 => 0
  | 124 => 351781584529344099031
  | 125 => 12669739822604347843
  | _ => 0

noncomputable def rowsR2XQ30 (p : Fin 126) : ℝ :=
  (rowsR2XQ30Num p : ℝ) / 1000000000000000000000000

theorem rowsR2XQ30_le_semantic (p : Fin 126) :
    rowsR2XQ30 p ≤ semanticQuantity130f (dualQ130fR2 p) p 2
      (roleIndex30 .X) := by
  fin_cases p
  · convert rowsCellR2XP000 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP001 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP002 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP003 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP004 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP005 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP006 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP007 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP008 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP009 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP010 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP011 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP012 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP013 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP014 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP015 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP016 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP017 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP018 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP019 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP020 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP021 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP022 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP023 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP024 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP025 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP026 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP027 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP028 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP029 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP030 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP031 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP032 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP033 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP034 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP035 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP036 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP037 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP038 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP039 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP040 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP041 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP042 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP043 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP044 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP045 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP046 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP047 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP048 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP049 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP050 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP051 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP052 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP053 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP054 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP055 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP056 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP057 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP058 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP059 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP060 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP061 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP062 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP063 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP064 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP065 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP066 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP067 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP068 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP069 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP070 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP071 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP072 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP073 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP074 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP075 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP076 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP077 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP078 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP079 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP080 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP081 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP082 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP083 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP084 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP085 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP086 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP087 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP088 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP089 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP090 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP091 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP092 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP093 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP094 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP095 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP096 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP097 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP098 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP099 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP100 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP101 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP102 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP103 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP104 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP105 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP106 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP107 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP108 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP109 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP110 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP111 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP112 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP113 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP114 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP115 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP116 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP117 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP118 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP119 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP120 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP121 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP122 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP123 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP124 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]
  · convert rowsCellR2XP125 using 1 <;> norm_num [rowsR2XQ30, rowsR2XQ30Num]

theorem rowsR2XQ30Num_sum :
    (∑ p : Fin 126, rowsR2XQ30Num p) = 122574000884125084711386 := by
  decide +kernel

theorem rowsR2XQ30_sum :
    (∑ p : Fin 126, rowsR2XQ30 p) = ((61287000442062542355693 : ℝ) / 500000000000000000000000) := by
  simp only [rowsR2XQ30]
  rw [← Finset.sum_div, ← Nat.cast_sum, rowsR2XQ30Num_sum]
  norm_num

theorem rowsR2XFlooredSum_le_paper30 :
    (∑ p : Fin 126, rowsR2XQ30 p) ≤
      Real.log 2 * paperRow30 2 .X / (releasedCertificate.D ^ 2 : ℝ) := by
  have hscaled :
      (releasedCertificate.D ^ 2 : ℝ) * (∑ p : Fin 126, rowsR2XQ30 p) ≤
        Real.log 2 * paperRow30 2 .X := by
    rw [paperRow_eq_sum30, Finset.mul_sum, Finset.mul_sum]
    exact Finset.sum_le_sum (fun p _ => by
      calc
        (releasedCertificate.D ^ 2 : ℝ) * rowsR2XQ30 p ≤
            (releasedCertificate.D ^ 2 : ℝ) * semanticQuantity130f
              (dualQ130fR2 p) p 2 (roleIndex30 .X) := by
          exact mul_le_mul_of_nonneg_left (rowsR2XQ30_le_semantic p) (by positivity)
        _ ≤ Real.log 2 * paperParent30 p 2 .X :=
          semantic_parent_bound (dualQ130fR2 p) p 2 .X)
  have hD : (0 : ℝ) < (releasedCertificate.D ^ 2 : ℝ) := by
    norm_num [releasedCertificate, OmegaBound.ADVXXZT2.certDen]
  apply (le_div_iff₀ hD).2
  simpa [mul_comm] using hscaled

theorem R4_le_rowsR2XFlooredSum30 :
    OmegaBound.ADVXXZCert.R4 ≤ (∑ p : Fin 126, rowsR2XQ30 p) := by
  rw [rowsR2XQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R4]

theorem rowsR2XFlooredSum_margin30 :
    (∑ p : Fin 126, rowsR2XQ30 p) - OmegaBound.ADVXXZCert.R4 =
      ((29696775693 : ℝ) / 500000000000000000000000) := by
  rw [rowsR2XQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R4]

theorem R4_le_rowsR2XPaper30 :
    OmegaBound.ADVXXZCert.R4 ≤
      Real.log 2 * paperRow30 2 .X / (releasedCertificate.D ^ 2 : ℝ) :=
  R4_le_rowsR2XFlooredSum30.trans rowsR2XFlooredSum_le_paper30

end OmegaBound.ADVXXZGeneral
