-- Generated by `tools/iapply_cells.py` (aggregator mode) of the development repository (not part of this release).
import OmegaBound.ADVXXZGeneralRowsSource30Assembly
import OmegaBound.ADVXXZGeneralRowsCellsR2Y0
import OmegaBound.ADVXXZGeneralRowsCellsR2Y1
import OmegaBound.ADVXXZGeneralRowsCellsR2Y2
import OmegaBound.ADVXXZGeneralRowsCellsR2Y3
import OmegaBound.ADVXXZGeneralRowsCellsR2Y4
import OmegaBound.ADVXXZGeneralRowsCellsR2Y5
import OmegaBound.ADVXXZGeneralRowsCellsR2Y6
import OmegaBound.ADVXXZGeneralRowsCellsR2Y7

open scoped BigOperators
open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

def rowsR2YQ30Num (p : Fin 126) : ℕ :=
  match p.1 with
  | 0 => 12658877683679685732
  | 1 => 399618878509074838222
  | 2 => 101643277079122366932
  | 3 => 0
  | 4 => 54358639789697054536
  | 5 => 12737200055645696161
  | 6 => 581595970797428638740
  | 7 => 5278870591106798552589
  | 8 => 4981069848418401365813
  | 9 => 2519668580181213720360
  | 10 => 0
  | 11 => 967875999977902787913
  | 12 => 0
  | 13 => 4234323459859627504638
  | 14 => 0
  | 15 => 0
  | 16 => 785563639990280304784
  | 17 => 2942061802905755086781
  | 18 => 134853402616898897354
  | 19 => 236166313262327027170
  | 20 => 13160722156930489155
  | 21 => 12780239758960969994
  | 22 => 365050334076553033631
  | 23 => 487840061619527612367
  | 24 => 0
  | 25 => 0
  | 26 => 12661455203341551185
  | 27 => 538409632378168905408
  | 28 => 1519947637251338825008
  | 29 => 4034465339087540852876
  | 30 => 0
  | 31 => 0
  | 32 => 1277534865830646934311
  | 33 => 0
  | 34 => 3945349883007304030963
  | 35 => 0
  | 36 => 0
  | 37 => 739898159104195425025
  | 38 => 2980730350560785719036
  | 39 => 136928211210613573396
  | 40 => 236738501416493972873
  | 41 => 13159988567808869997
  | 42 => 12665369261306421051
  | 43 => 397735013822657728053
  | 44 => 109849724551858757728
  | 45 => 0
  | 46 => 103422741061898049733
  | 47 => 12798634438151427294
  | 48 => 583384411078165517560
  | 49 => 5335168615961332181611
  | 50 => 5580239567211214426825
  | 51 => 4297482189144867665406
  | 52 => 0
  | 53 => 928449591585960267329
  | 54 => 0
  | 55 => 4938985422234642925628
  | 56 => 0
  | 57 => 0
  | 58 => 668103004007219892355
  | 59 => 3138898560728122789904
  | 60 => 70559095686169644022
  | 61 => 275413336921946281751
  | 62 => 12974720500830009639
  | 63 => 12770265830451550246
  | 64 => 364927406733163728738
  | 65 => 506906382572593989058
  | 66 => 0
  | 67 => 104214143321220711607
  | 68 => 12800577259905791585
  | 69 => 545647143067460309279
  | 70 => 1576483906056991595475
  | 71 => 5102966402803146775796
  | 72 => 4209220306955724580520
  | 73 => 0
  | 74 => 1245072096410036280344
  | 75 => 0
  | 76 => 5282842379507825995486
  | 77 => 0
  | 78 => 0
  | 79 => 89812412765540145138
  | 80 => 3554170775519713061388
  | 81 => 0
  | 82 => 309999300560145482195
  | 83 => 12722297758254434675
  | 84 => 12865673512247182281
  | 85 => 326595381268205133896
  | 86 => 685053494650517177436
  | 87 => 0
  | 88 => 0
  | 89 => 12667731206044864042
  | 90 => 482907927306858884749
  | 91 => 0
  | 92 => 3458091909277566459745
  | 93 => 0
  | 94 => 0
  | 95 => 1438466581155093995792
  | 96 => 0
  | 97 => 4316289516351736451709
  | 98 => 0
  | 99 => 0
  | 100 => 639738108424459367120
  | 101 => 3176330806194153655023
  | 102 => 68935323379387261615
  | 103 => 278138688602359829537
  | 104 => 12970430758914054578
  | 105 => 12874699129713797899
  | 106 => 325992421571822769033
  | 107 => 684664018322083926210
  | 108 => 0
  | 109 => 49144113771616715910
  | 110 => 12735974497460328640
  | 111 => 491879986417765061702
  | 112 => 0
  | 113 => 3971623261711317364283
  | 114 => 2812795039928986472926
  | 115 => 0
  | 116 => 1441469201985814994041
  | 117 => 0
  | 118 => 4899284693205212924281
  | 119 => 0
  | 120 => 0
  | 121 => 49316850351339664139
  | 122 => 3633817140180587641630
  | 123 => 0
  | 124 => 312220502977961408537
  | 125 => 12723749517277424331
  | _ => 0

noncomputable def rowsR2YQ30 (p : Fin 126) : ℝ :=
  (rowsR2YQ30Num p : ℝ) / 1000000000000000000000000

theorem rowsR2YQ30_le_semantic (p : Fin 126) :
    rowsR2YQ30 p ≤ semanticQuantity130f (dualQ130fR2 p) p 2
      (roleIndex30 .Y) := by
  fin_cases p
  · convert rowsCellR2YP000 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP001 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP002 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP003 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP004 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP005 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP006 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP007 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP008 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP009 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP010 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP011 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP012 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP013 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP014 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP015 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP016 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP017 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP018 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP019 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP020 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP021 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP022 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP023 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP024 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP025 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP026 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP027 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP028 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP029 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP030 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP031 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP032 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP033 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP034 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP035 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP036 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP037 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP038 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP039 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP040 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP041 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP042 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP043 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP044 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP045 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP046 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP047 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP048 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP049 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP050 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP051 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP052 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP053 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP054 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP055 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP056 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP057 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP058 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP059 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP060 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP061 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP062 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP063 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP064 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP065 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP066 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP067 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP068 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP069 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP070 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP071 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP072 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP073 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP074 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP075 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP076 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP077 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP078 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP079 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP080 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP081 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP082 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP083 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP084 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP085 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP086 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP087 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP088 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP089 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP090 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP091 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP092 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP093 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP094 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP095 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP096 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP097 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP098 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP099 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP100 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP101 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP102 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP103 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP104 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP105 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP106 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP107 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP108 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP109 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP110 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP111 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP112 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP113 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP114 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP115 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP116 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP117 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP118 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP119 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP120 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP121 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP122 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP123 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP124 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]
  · convert rowsCellR2YP125 using 1 <;> norm_num [rowsR2YQ30, rowsR2YQ30Num]

theorem rowsR2YQ30Num_sum :
    (∑ p : Fin 126, rowsR2YQ30Num p) = 122574000884439087521454 := by
  decide +kernel

theorem rowsR2YQ30_sum :
    (∑ p : Fin 126, rowsR2YQ30 p) = ((61287000442219543760727 : ℝ) / 500000000000000000000000) := by
  simp only [rowsR2YQ30]
  rw [← Finset.sum_div, ← Nat.cast_sum, rowsR2YQ30Num_sum]
  norm_num

theorem rowsR2YFlooredSum_le_paper30 :
    (∑ p : Fin 126, rowsR2YQ30 p) ≤
      Real.log 2 * paperRow30 2 .Y / (releasedCertificate.D ^ 2 : ℝ) := by
  have hscaled :
      (releasedCertificate.D ^ 2 : ℝ) * (∑ p : Fin 126, rowsR2YQ30 p) ≤
        Real.log 2 * paperRow30 2 .Y := by
    rw [paperRow_eq_sum30, Finset.mul_sum, Finset.mul_sum]
    exact Finset.sum_le_sum (fun p _ => by
      calc
        (releasedCertificate.D ^ 2 : ℝ) * rowsR2YQ30 p ≤
            (releasedCertificate.D ^ 2 : ℝ) * semanticQuantity130f
              (dualQ130fR2 p) p 2 (roleIndex30 .Y) := by
          exact mul_le_mul_of_nonneg_left (rowsR2YQ30_le_semantic p) (by positivity)
        _ ≤ Real.log 2 * paperParent30 p 2 .Y :=
          semantic_parent_bound (dualQ130fR2 p) p 2 .Y)
  have hD : (0 : ℝ) < (releasedCertificate.D ^ 2 : ℝ) := by
    norm_num [releasedCertificate, OmegaBound.ADVXXZT2.certDen]
  apply (le_div_iff₀ hD).2
  simpa [mul_comm] using hscaled

theorem R4_le_rowsR2YFlooredSum30 :
    OmegaBound.ADVXXZCert.R4 ≤ (∑ p : Fin 126, rowsR2YQ30 p) := by
  rw [rowsR2YQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R4]

theorem rowsR2YFlooredSum_margin30 :
    (∑ p : Fin 126, rowsR2YQ30 p) - OmegaBound.ADVXXZCert.R4 =
      ((186698180727 : ℝ) / 500000000000000000000000) := by
  rw [rowsR2YQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R4]

theorem R4_le_rowsR2YPaper30 :
    OmegaBound.ADVXXZCert.R4 ≤
      Real.log 2 * paperRow30 2 .Y / (releasedCertificate.D ^ 2 : ℝ) :=
  R4_le_rowsR2YFlooredSum30.trans rowsR2YFlooredSum_le_paper30

end OmegaBound.ADVXXZGeneral
