import OmegaBound.ADVXXZT6Round65FieldMap
import OmegaBound.ADVXXZT9R2ScaleAlignment
import OmegaBound.ADVXXZT9TargetArithmetic
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Combinatorics.Nullstellensatz
import Mathlib.Data.Fin.VecNotation
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Ring
