-- Generated by `tools/iapply_cells.py` (cells mode) of the development repository (not part of this release).
-- The release tooling rewrote its imports.
import OmegaBound.ReleaseCompactRowsR2Z2Check
import OmegaBound.ADVXXZGeneralRowsSemanticCore30
import OmegaBound.ReleaseCompactR61CohortR2P032P063Check
import OmegaBound.ADVXXZRetainedAtom039
import OmegaBound.ADVXXZRetainedAtom041
import OmegaBound.ADVXXZRetainedAtom042
import OmegaBound.ADVXXZRetainedAtom043
import OmegaBound.ADVXXZRetainedAtom054
import OmegaBound.ADVXXZRetainedAtom055
import OmegaBound.ADVXXZRetainedAtom060
import OmegaBound.ADVXXZRetainedAtom064
import OmegaBound.ADVXXZRetainedAtom070
import OmegaBound.ADVXXZRetainedAtom072
import OmegaBound.ADVXXZRetainedAtom077
import OmegaBound.ADVXXZRetainedAtom079
import OmegaBound.ADVXXZRetainedAtom080
import OmegaBound.ADVXXZRetainedAtom085
import OmegaBound.ADVXXZRetainedAtom086
import OmegaBound.ADVXXZRetainedAtom094
import OmegaBound.ADVXXZRetainedAtom095
import OmegaBound.ADVXXZRetainedAtom099
import OmegaBound.ADVXXZRetainedAtom101
import OmegaBound.ADVXXZRetainedAtom102
import OmegaBound.ADVXXZRetainedAtom103
import OmegaBound.ADVXXZRetainedAtom109
import OmegaBound.ADVXXZRetainedAtom110
import OmegaBound.ADVXXZRetainedAtom114
import OmegaBound.ADVXXZRetainedAtom116
import OmegaBound.ADVXXZRetainedAtom117
import OmegaBound.ADVXXZRetainedAtom118
import OmegaBound.ADVXXZRetainedAtom120
import OmegaBound.ADVXXZRetainedAtom121
import OmegaBound.ADVXXZRetainedAtom122
import OmegaBound.ADVXXZRetainedAtom124
import OmegaBound.ADVXXZRetainedAtom125
import OmegaBound.ADVXXZRetainedAtom126
import OmegaBound.ADVXXZRetainedAtom127
import OmegaBound.ADVXXZRetainedAtom128
import OmegaBound.ADVXXZRetainedAtom129
import OmegaBound.ADVXXZRetainedAtom133
import OmegaBound.ADVXXZRetainedAtom135
import OmegaBound.ADVXXZRetainedAtom141
import OmegaBound.ADVXXZRetainedAtom143
import OmegaBound.ADVXXZRetainedAtom144
import OmegaBound.ADVXXZRetainedAtom145
import OmegaBound.ADVXXZRetainedAtom146
import OmegaBound.ADVXXZRetainedAtom149
import OmegaBound.ADVXXZRetainedAtom153
import OmegaBound.ADVXXZRetainedAtom155
import OmegaBound.ADVXXZRetainedAtom157
import OmegaBound.ADVXXZRetainedAtom158
import OmegaBound.ADVXXZRetainedAtom160
import OmegaBound.ADVXXZRetainedAtom161
import OmegaBound.ADVXXZRetainedAtom162
import OmegaBound.ADVXXZRetainedAtom163
import OmegaBound.ADVXXZRetainedAtom164
import OmegaBound.ADVXXZRetainedAtom165
import OmegaBound.ADVXXZRetainedAtom166
import OmegaBound.ADVXXZRetainedAtom168
import OmegaBound.ADVXXZRetainedAtom169
import OmegaBound.ADVXXZRetainedAtom170
import OmegaBound.ADVXXZRetainedAtom172
import OmegaBound.ADVXXZRetainedAtom174
import OmegaBound.ADVXXZRetainedAtom176
import OmegaBound.ADVXXZRetainedAtom178
import OmegaBound.ADVXXZRetainedAtom180
import OmegaBound.ADVXXZRetainedAtom181
import OmegaBound.ADVXXZRetainedAtom184
import OmegaBound.ADVXXZRetainedAtom190
import OmegaBound.ADVXXZRetainedAtom194
import OmegaBound.ADVXXZRetainedAtom195
import OmegaBound.ADVXXZRetainedAtom196
import OmegaBound.ADVXXZRetainedAtom197
import OmegaBound.ADVXXZRetainedAtom198

set_option maxRecDepth 1000000
set_option linter.style.longLine false

open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

noncomputable def rowsCellR2ZP034Expr30 : ℝ :=
  ((18465711031851332913879022090735 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((162219188446772846899791714775663 : ℝ) / 41538374868278621028243970633760768)
    + ((18465711031851332913879022090735 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((648876852200456934027866934892607 : ℝ) / 166153499473114484112975882535043072)
    + ((-36230760358936309653994066572344660682035199125 : ℝ) / 11692013098647223345629478661730264157247460343808) * Real.negMulLog ((5223508953997079 : ℝ) / 288230376151711744)
    + ((-76122096997377928822082193189182999748171003385 : ℝ) / 374144419156711147060143317175368453031918731001856) * Real.negMulLog ((8060237677562323 : ℝ) / 288230376151711744)
    + ((-41312437217731219368178920262473537583564276515 : ℝ) / 187072209578355573530071658587684226515959365500928) * Real.negMulLog ((7978011490425785 : ℝ) / 144115188075855872)
    + ((18465711031851332913879022090735 : ℝ) / 973555660975280180349468061728768) * Real.negMulLog ((362312816059023821 : ℝ) / 2305843009213693952)
    + ((18465711031851332913879022090735 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((3695526937010066227243506847255953 : ℝ) / 20769187434139310514121985316880384)
    + ((18465711031851332913879022090735 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((14782108753890237167060676673775553 : ℝ) / 83076749736557242056487941267521536)
    + ((-6690363764482238943962712349540609175298588398435 : ℝ) / 561216628735066720590214975763052679547878096502784) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-41312437217731219368178920262473537583564276515 : ℝ) / 374144419156711147060143317175368453031918731001856) * Real.negMulLog ((64079582547502151 : ℝ) / 72057594037927936)
    + ((-76122096997377928822082193189182999748171003385 : ℝ) / 748288838313422294120286634350736906063837462003712) * Real.negMulLog ((136054950398293549 : ℝ) / 144115188075855872)
    + ((-36230760358936309653994066572344660682035199125 : ℝ) / 23384026197294446691258957323460528314494920687616) * Real.negMulLog ((138891679121858793 : ℝ) / 144115188075855872)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP034_value_bridge : rowsCellR2ZP034Expr30 = rowsCellR2ZP034Raw30.value := by
  unfold rowsCellR2ZP034Expr30 rowsCellR2ZP034Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP034_coefficient :
    ((dualQ130fR2 34).coefficient : ℝ) =
      (coefficientQ130f 2 34 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP034R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 34 := OmegaBound.ADVXXZT6Round61.coefficientP034R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 34).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP034_lower : ((2177405703698133858497 : ℝ) / 500000000000000000000000) ≤ rowsCellR2ZP034Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16572_lower
    (show 0 ≤ ((18465711031851332913879022090735 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17014_lower
    (show 0 ≤ ((18465711031851332913879022090735 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07954_upper
    (show ((-36230760358936309653994066572344660682035199125 : ℝ) / 11692013098647223345629478661730264157247460343808) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10349_upper
    (show ((-76122096997377928822082193189182999748171003385 : ℝ) / 374144419156711147060143317175368453031918731001856) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10291_upper
    (show ((-41312437217731219368178920262473537583564276515 : ℝ) / 187072209578355573530071658587684226515959365500928) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14182_lower
    (show 0 ≤ ((18465711031851332913879022090735 : ℝ) / 973555660975280180349468061728768) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17453_lower
    (show 0 ≤ ((18465711031851332913879022090735 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17842_lower
    (show 0 ≤ ((18465711031851332913879022090735 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-6690363764482238943962712349540609175298588398435 : ℝ) / 561216628735066720590214975763052679547878096502784) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12640_upper
    (show ((-41312437217731219368178920262473537583564276515 : ℝ) / 374144419156711147060143317175368453031918731001856) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom13317_upper
    (show ((-76122096997377928822082193189182999748171003385 : ℝ) / 748288838313422294120286634350736906063837462003712) ≤ 0 by norm_num)
  have h11 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom13581_upper
    (show ((-36230760358936309653994066572344660682035199125 : ℝ) / 23384026197294446691258957323460528314494920687616) ≤ 0 by norm_num)
  unfold rowsCellR2ZP034Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP034_eq_semantic : rowsCellR2ZP034Expr30 =
    semanticQuantity130f (dualQ130fR2 34) 34 2 2 := by
  calc
    rowsCellR2ZP034Expr30 = rowsCellR2ZP034Raw30.value := rowsCellR2ZP034_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 34) 34 2 2).value := by
      rw [rowsCellR2ZP034_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP034_coefficient

theorem rowsCellR2ZP034 : ((2177405703698133858497 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 34) 34 2
      (roleIndex30 .Z) := by
  change ((2177405703698133858497 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 34) 34 2 2
  rw [← rowsCellR2ZP034_eq_semantic]
  exact rowsCellR2ZP034_lower

noncomputable def rowsCellR2ZP035Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP035_value_bridge : rowsCellR2ZP035Expr30 = rowsCellR2ZP035Raw30.value := by
  unfold rowsCellR2ZP035Expr30 rowsCellR2ZP035Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP035_coefficient :
    ((dualQ130fR2 35).coefficient : ℝ) =
      (coefficientQ130f 2 35 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP035R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 35 := OmegaBound.ADVXXZT6Round61.coefficientP035R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 35).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP035_lower : (0 : ℝ) ≤ rowsCellR2ZP035Expr30 := by
  unfold rowsCellR2ZP035Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP035_eq_semantic : rowsCellR2ZP035Expr30 =
    semanticQuantity130f (dualQ130fR2 35) 35 2 2 := by
  calc
    rowsCellR2ZP035Expr30 = rowsCellR2ZP035Raw30.value := rowsCellR2ZP035_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 35) 35 2 2).value := by
      rw [rowsCellR2ZP035_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP035_coefficient

theorem rowsCellR2ZP035 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 35) 35 2
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 35) 35 2 2
  rw [← rowsCellR2ZP035_eq_semantic]
  exact rowsCellR2ZP035_lower

noncomputable def rowsCellR2ZP036Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP036_value_bridge : rowsCellR2ZP036Expr30 = rowsCellR2ZP036Raw30.value := by
  unfold rowsCellR2ZP036Expr30 rowsCellR2ZP036Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP036_coefficient :
    ((dualQ130fR2 36).coefficient : ℝ) =
      (coefficientQ130f 2 36 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP036R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 36 := OmegaBound.ADVXXZT6Round61.coefficientP036R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 36).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP036_lower : (0 : ℝ) ≤ rowsCellR2ZP036Expr30 := by
  unfold rowsCellR2ZP036Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP036_eq_semantic : rowsCellR2ZP036Expr30 =
    semanticQuantity130f (dualQ130fR2 36) 36 2 2 := by
  calc
    rowsCellR2ZP036Expr30 = rowsCellR2ZP036Raw30.value := rowsCellR2ZP036_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 36) 36 2 2).value := by
      rw [rowsCellR2ZP036_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP036_coefficient

theorem rowsCellR2ZP036 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 36) 36 2
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 36) 36 2 2
  rw [← rowsCellR2ZP036_eq_semantic]
  exact rowsCellR2ZP036_lower

noncomputable def rowsCellR2ZP037Expr30 : ℝ :=
  ((3443412120397365335892835399765 : ℝ) / 1298074214633706907132624082305024) * Real.negMulLog ((7297472731177674004564317613152945 : ℝ) / 1329227995784915872903807060280344576)
    + ((3443412120397365335892835399765 : ℝ) / 1298074214633706907132624082305024) * Real.negMulLog ((3648736602985543246486397388680181 : ℝ) / 664613997892457936451903530140172288)
    + ((-35500722296494852970592784853848664196575693685 : ℝ) / 46768052394588893382517914646921056628989841375232) * Real.negMulLog ((2757818009465323 : ℝ) / 72057594037927936)
    + ((-42651884681352065143777901089803604423599851295 : ℝ) / 23945242826029513411849172299223580994042798784118784) * Real.negMulLog ((3031371597253801 : ℝ) / 72057594037927936)
    + ((3443412120397365335892835399765 : ℝ) / 649037107316853453566312041152512) * Real.negMulLog ((11607032337670867037 : ℝ) / 73786976294838206464)
    + ((3443412120397365335892835399765 : ℝ) / 2596148429267413814265248164610048) * Real.negMulLog ((115915817310280796904852090041312591 : ℝ) / 664613997892457936451903530140172288)
    + ((3443412120397365335892835399765 : ℝ) / 2596148429267413814265248164610048) * Real.negMulLog ((57957911279266933966447160843211787 : ℝ) / 332306998946228968225951765070086144)
    + ((-39967795833380028429691874997187613434974056046305 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-42651884681352065143777901089803604423599851295 : ℝ) / 47890485652059026823698344598447161988085597568237568) * Real.negMulLog ((32997425421710167 : ℝ) / 36028797018963968)
    + ((-35500722296494852970592784853848664196575693685 : ℝ) / 93536104789177786765035829293842113257979682750464) * Real.negMulLog ((33270979009498645 : ℝ) / 36028797018963968)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP037_value_bridge : rowsCellR2ZP037Expr30 = rowsCellR2ZP037Raw30.value := by
  unfold rowsCellR2ZP037Expr30 rowsCellR2ZP037Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP037_coefficient :
    ((dualQ130fR2 37).coefficient : ℝ) =
      (coefficientQ130f 2 37 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP037R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 37 := OmegaBound.ADVXXZT6Round61.coefficientP037R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 37).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP037_lower : ((48927305567453030933 : ℝ) / 40000000000000000000000) ≤ rowsCellR2ZP037Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17619_lower
    (show 0 ≤ ((3443412120397365335892835399765 : ℝ) / 1298074214633706907132624082305024) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17428_lower
    (show 0 ≤ ((3443412120397365335892835399765 : ℝ) / 1298074214633706907132624082305024) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom06090_upper
    (show ((-35500722296494852970592784853848664196575693685 : ℝ) / 46768052394588893382517914646921056628989841375232) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom06453_upper
    (show ((-42651884681352065143777901089803604423599851295 : ℝ) / 23945242826029513411849172299223580994042798784118784) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15538_lower
    (show 0 ≤ ((3443412120397365335892835399765 : ℝ) / 649037107316853453566312041152512) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18138_lower
    (show 0 ≤ ((3443412120397365335892835399765 : ℝ) / 2596148429267413814265248164610048) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18055_lower
    (show 0 ≤ ((3443412120397365335892835399765 : ℝ) / 2596148429267413814265248164610048) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-39967795833380028429691874997187613434974056046305 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11812_upper
    (show ((-42651884681352065143777901089803604423599851295 : ℝ) / 47890485652059026823698344598447161988085597568237568) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11832_upper
    (show ((-35500722296494852970592784853848664196575693685 : ℝ) / 93536104789177786765035829293842113257979682750464) ≤ 0 by norm_num)
  unfold rowsCellR2ZP037Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP037_eq_semantic : rowsCellR2ZP037Expr30 =
    semanticQuantity130f (dualQ130fR2 37) 37 2 2 := by
  calc
    rowsCellR2ZP037Expr30 = rowsCellR2ZP037Raw30.value := rowsCellR2ZP037_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 37) 37 2 2).value := by
      rw [rowsCellR2ZP037_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP037_coefficient

theorem rowsCellR2ZP037 : ((48927305567453030933 : ℝ) / 40000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 37) 37 2
      (roleIndex30 .Z) := by
  change ((48927305567453030933 : ℝ) / 40000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 37) 37 2 2
  rw [← rowsCellR2ZP037_eq_semantic]
  exact rowsCellR2ZP037_lower

noncomputable def rowsCellR2ZP038Expr30 : ℝ :=
  ((157027209997961620674212312468915 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((2305842940698221783 : ℝ) / 9223372036854775808)
    + ((157027209997961620674212312468915 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((2305843077729166121 : ℝ) / 9223372036854775808)
    + ((-157027209997961620674212312468915 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP038_value_bridge : rowsCellR2ZP038Expr30 = rowsCellR2ZP038Raw30.value := by
  unfold rowsCellR2ZP038Expr30 rowsCellR2ZP038Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP038_coefficient :
    ((dualQ130fR2 38).coefficient : ℝ) =
      (coefficientQ130f 2 38 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP038R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 38 := OmegaBound.ADVXXZT6Round61.coefficientP038R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 38).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP038_lower : ((174686609232115121381 : ℝ) / 50000000000000000000000) ≤ rowsCellR2ZP038Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14960_lower
    (show 0 ≤ ((157027209997961620674212312468915 : ℝ) / 15576890575604482885591488987660288) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14979_lower
    (show 0 ≤ ((157027209997961620674212312468915 : ℝ) / 15576890575604482885591488987660288) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-157027209997961620674212312468915 : ℝ) / 15576890575604482885591488987660288) ≤ 0 by norm_num)
  unfold rowsCellR2ZP038Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP038_eq_semantic : rowsCellR2ZP038Expr30 =
    semanticQuantity130f (dualQ130fR2 38) 38 2 2 := by
  calc
    rowsCellR2ZP038Expr30 = rowsCellR2ZP038Raw30.value := rowsCellR2ZP038_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 38) 38 2 2).value := by
      rw [rowsCellR2ZP038_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP038_coefficient

theorem rowsCellR2ZP038 : ((174686609232115121381 : ℝ) / 50000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 38) 38 2
      (roleIndex30 .Z) := by
  change ((174686609232115121381 : ℝ) / 50000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 38) 38 2 2
  rw [← rowsCellR2ZP038_eq_semantic]
  exact rowsCellR2ZP038_lower

noncomputable def rowsCellR2ZP039Expr30 : ℝ :=
  ((1385779018440748719804745404665 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((34630665707667831386819190363627 : ℝ) / 5192296858534827628530496329220096)
    + ((1385779018440748719804745404665 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((17315333587657617367473399905495 : ℝ) / 2596148429267413814265248164610048)
    + ((-17676226203132683901553523162874071338559596645 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((5429943065645309 : ℝ) / 144115188075855872)
    + ((1385779018440748719804745404665 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((727853740371228031 : ℝ) / 4611686018427387904)
    + ((1385779018440748719804745404665 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((221976536612039786876285507748649 : ℝ) / 1298074214633706907132624082305024)
    + ((1385779018440748719804745404665 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((443953106202309023722849690151445 : ℝ) / 2596148429267413814265248164610048)
    + ((-1008644441900067940526967849952120038130086164615 : ℝ) / 2244866514940266882360859903052210718191512386011136) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-17676226203132683901553523162874071338559596645 : ℝ) / 280608314367533360295107487881526339773939048251392) * Real.negMulLog ((66627650972282627 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP039_value_bridge : rowsCellR2ZP039Expr30 = rowsCellR2ZP039Raw30.value := by
  unfold rowsCellR2ZP039Expr30 rowsCellR2ZP039Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP039_coefficient :
    ((dualQ130fR2 39).coefficient : ℝ) =
      (coefficientQ130f 2 39 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP039R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 39 := OmegaBound.ADVXXZT6Round61.coefficientP039R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 39).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP039_lower : ((16279163681980875361 : ℝ) / 100000000000000000000000) ≤ rowsCellR2ZP039Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16253_lower
    (show 0 ≤ ((1385779018440748719804745404665 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16076_lower
    (show 0 ≤ ((1385779018440748719804745404665 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom08064_upper
    (show ((-17676226203132683901553523162874071338559596645 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14616_lower
    (show 0 ≤ ((1385779018440748719804745404665 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16641_lower
    (show 0 ≤ ((1385779018440748719804745404665 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16877_lower
    (show 0 ≤ ((1385779018440748719804745404665 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-1008644441900067940526967849952120038130086164615 : ℝ) / 2244866514940266882360859903052210718191512386011136) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12897_upper
    (show ((-17676226203132683901553523162874071338559596645 : ℝ) / 280608314367533360295107487881526339773939048251392) ≤ 0 by norm_num)
  unfold rowsCellR2ZP039Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP039_eq_semantic : rowsCellR2ZP039Expr30 =
    semanticQuantity130f (dualQ130fR2 39) 39 2 2 := by
  calc
    rowsCellR2ZP039Expr30 = rowsCellR2ZP039Raw30.value := rowsCellR2ZP039_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 39) 39 2 2).value := by
      rw [rowsCellR2ZP039_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP039_coefficient

theorem rowsCellR2ZP039 : ((16279163681980875361 : ℝ) / 100000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 39) 39 2
      (roleIndex30 .Z) := by
  change ((16279163681980875361 : ℝ) / 100000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 39) 39 2 2
  rw [← rowsCellR2ZP039_eq_semantic]
  exact rowsCellR2ZP039_lower

noncomputable def rowsCellR2ZP040Expr30 : ℝ :=
  ((6155219126542744020185907562449 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((576460741187078475 : ℝ) / 2305843009213693952)
    + ((6155219126542744020185907562449 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((576460763419768501 : ℝ) / 2305843009213693952)
    + ((-6155219126542744020185907562449 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP040_value_bridge : rowsCellR2ZP040Expr30 = rowsCellR2ZP040Raw30.value := by
  unfold rowsCellR2ZP040Expr30 rowsCellR2ZP040Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP040_coefficient :
    ((dualQ130fR2 40).coefficient : ℝ) =
      (coefficientQ130f 2 40 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP040R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 40 := OmegaBound.ADVXXZT6Round61.coefficientP040R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 40).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP040_lower : ((205423192256368439031 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2ZP040Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14465_lower
    (show 0 ≤ ((6155219126542744020185907562449 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14524_lower
    (show 0 ≤ ((6155219126542744020185907562449 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-6155219126542744020185907562449 : ℝ) / 10384593717069655257060992658440192) ≤ 0 by norm_num)
  unfold rowsCellR2ZP040Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP040_eq_semantic : rowsCellR2ZP040Expr30 =
    semanticQuantity130f (dualQ130fR2 40) 40 2 2 := by
  calc
    rowsCellR2ZP040Expr30 = rowsCellR2ZP040Raw30.value := rowsCellR2ZP040_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 40) 40 2 2).value := by
      rw [rowsCellR2ZP040_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP040_coefficient

theorem rowsCellR2ZP040 : ((205423192256368439031 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 40) 40 2
      (roleIndex30 .Z) := by
  change ((205423192256368439031 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 40) 40 2 2
  rw [← rowsCellR2ZP040_eq_semantic]
  exact rowsCellR2ZP040_lower

noncomputable def rowsCellR2ZP041Expr30 : ℝ :=
  ((36844810877045057621321664891233 : ℝ) / 996920996838686904677855295210258432) * Real.negMulLog ((36028796839441185 : ℝ) / 144115188075855872)
    + ((36844810877045057621321664891233 : ℝ) / 996920996838686904677855295210258432) * Real.negMulLog ((36028797198486751 : ℝ) / 144115188075855872)
    + ((-36844810877045057621321664891233 : ℝ) / 996920996838686904677855295210258432) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP041_value_bridge : rowsCellR2ZP041Expr30 = rowsCellR2ZP041Raw30.value := by
  unfold rowsCellR2ZP041Expr30 rowsCellR2ZP041Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP041_coefficient :
    ((dualQ130fR2 41).coefficient : ℝ) =
      (coefficientQ130f 2 41 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP041R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 41 := OmegaBound.ADVXXZT6Round61.coefficientP041R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 41).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP041_lower : ((800554810093839179 : ℝ) / 62500000000000000000000) ≤ rowsCellR2ZP041Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12089_lower
    (show 0 ≤ ((36844810877045057621321664891233 : ℝ) / 996920996838686904677855295210258432) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12104_lower
    (show 0 ≤ ((36844810877045057621321664891233 : ℝ) / 996920996838686904677855295210258432) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-36844810877045057621321664891233 : ℝ) / 996920996838686904677855295210258432) ≤ 0 by norm_num)
  unfold rowsCellR2ZP041Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP041_eq_semantic : rowsCellR2ZP041Expr30 =
    semanticQuantity130f (dualQ130fR2 41) 41 2 2 := by
  calc
    rowsCellR2ZP041Expr30 = rowsCellR2ZP041Raw30.value := rowsCellR2ZP041_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 41) 41 2 2).value := by
      rw [rowsCellR2ZP041_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP041_coefficient

theorem rowsCellR2ZP041 : ((800554810093839179 : ℝ) / 62500000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 41) 41 2
      (roleIndex30 .Z) := by
  change ((800554810093839179 : ℝ) / 62500000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 41) 41 2 2
  rw [← rowsCellR2ZP041_eq_semantic]
  exact rowsCellR2ZP041_lower

noncomputable def rowsCellR2ZP042Expr30 : ℝ :=
  ((9108002530656185659971601202939 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((27545458566664869215593322032335 : ℝ) / 340282366920938463463374607431768211456)
    + ((9108002530656185659971601202939 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((55091027047736674995059528784045 : ℝ) / 680564733841876926926749214863536422912)
    + ((-50165048006329017060598487212307841145371660281 : ℝ) / 5986310706507378352962293074805895248510699696029696) * Real.negMulLog ((6668237922063195 : ℝ) / 9444732965739290427392)
    + ((9108002530656185659971601202939 : ℝ) / 498460498419343452338927647605129216) * Real.negMulLog ((19507337340263030295905805691169755953 : ℝ) / 170141183460469231731687303715884105728)
    + ((9108002530656185659971601202939 : ℝ) / 498460498419343452338927647605129216) * Real.negMulLog ((39014752520486846770319485645254600531 : ℝ) / 340282366920938463463374607431768211456)
    + ((9108002530656185659971601202939 : ℝ) / 124615124604835863084731911901282304) * Real.negMulLog ((55534196782333999 : ℝ) / 288230376151711744)
    + ((-505805604831456665763626077089887197572478423061 : ℝ) / 8979466059761067529443439612208842872766049544044544) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-50165048006329017060598487212307841145371660281 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((4722359814631723150501 : ℝ) / 4722366482869645213696)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP042_value_bridge : rowsCellR2ZP042Expr30 = rowsCellR2ZP042Raw30.value := by
  unfold rowsCellR2ZP042Expr30 rowsCellR2ZP042Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP042_coefficient :
    ((dualQ130fR2 42).coefficient : ℝ) =
      (coefficientQ130f 2 42 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP042R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 42 := OmegaBound.ADVXXZT6Round61.coefficientP042R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 42).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP042_lower : ((12742774840321028457 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2ZP042Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16206_lower
    (show 0 ≤ ((9108002530656185659971601202939 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16372_lower
    (show 0 ≤ ((9108002530656185659971601202939 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom09451_upper
    (show ((-50165048006329017060598487212307841145371660281 : ℝ) / 5986310706507378352962293074805895248510699696029696) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18427_lower
    (show 0 ≤ ((9108002530656185659971601202939 : ℝ) / 498460498419343452338927647605129216) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18456_lower
    (show 0 ≤ ((9108002530656185659971601202939 : ℝ) / 498460498419343452338927647605129216) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12415_lower
    (show 0 ≤ ((9108002530656185659971601202939 : ℝ) / 124615124604835863084731911901282304) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-505805604831456665763626077089887197572478423061 : ℝ) / 8979466059761067529443439612208842872766049544044544) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom15728_upper
    (show ((-50165048006329017060598487212307841145371660281 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  unfold rowsCellR2ZP042Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP042_eq_semantic : rowsCellR2ZP042Expr30 =
    semanticQuantity130f (dualQ130fR2 42) 42 2 2 := by
  calc
    rowsCellR2ZP042Expr30 = rowsCellR2ZP042Raw30.value := rowsCellR2ZP042_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 42) 42 2 2).value := by
      rw [rowsCellR2ZP042_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP042_coefficient

theorem rowsCellR2ZP042 : ((12742774840321028457 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 42) 42 2
      (roleIndex30 .Z) := by
  change ((12742774840321028457 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 42) 42 2 2
  rw [← rowsCellR2ZP042_eq_semantic]
  exact rowsCellR2ZP042_lower

noncomputable def rowsCellR2ZP043Expr30 : ℝ :=
  ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((1907038661362005 : ℝ) / 576460752303423488)
    + ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((7628180800163519 : ℝ) / 2305843009213693952)
    + ((46553024756147265370009480815 : ℝ) / 20282409603651670423947251286016) * Real.negMulLog ((2665373912011186547422220280833 : ℝ) / 649037107316853453566312041152512)
    + ((46553024756147265370009480815 : ℝ) / 20282409603651670423947251286016) * Real.negMulLog ((166585907005265898942474169719 : ℝ) / 40564819207303340847894502572032)
    + ((-578454013374548762144848665674131581063389895 : ℝ) / 1461501637330902918203684832716283019655932542976) * Real.negMulLog ((429009839361289 : ℝ) / 9007199254740992)
    + ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((77390686799756087201250597116927 : ℝ) / 324518553658426726783156020576256)
    + ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((4836918954577506467245832327817 : ℝ) / 20282409603651670423947251286016)
    + ((-46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-578454013374548762144848665674131581063389895 : ℝ) / 2923003274661805836407369665432566039311865085952) * Real.negMulLog ((4074589788009207 : ℝ) / 4503599627370496)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP043_value_bridge : rowsCellR2ZP043Expr30 = rowsCellR2ZP043Raw30.value := by
  unfold rowsCellR2ZP043Expr30 rowsCellR2ZP043Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP043_coefficient :
    ((dualQ130fR2 43).coefficient : ℝ) =
      (coefficientQ130f 2 43 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP043R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 43 := OmegaBound.ADVXXZT6Round61.coefficientP043R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 43).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP043_lower : ((458546039117079147109 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2ZP043Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom05537_lower
    (show 0 ≤ ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10108_lower
    (show 0 ≤ ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15840_lower
    (show 0 ≤ ((46553024756147265370009480815 : ℝ) / 20282409603651670423947251286016) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15769_lower
    (show 0 ≤ ((46553024756147265370009480815 : ℝ) / 20282409603651670423947251286016) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom04351_upper
    (show ((-578454013374548762144848665674131581063389895 : ℝ) / 1461501637330902918203684832716283019655932542976) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16438_lower
    (show 0 ≤ ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15882_lower
    (show 0 ≤ ((46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-46553024756147265370009480815 : ℝ) / 40564819207303340847894502572032) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07209_upper
    (show ((-578454013374548762144848665674131581063389895 : ℝ) / 2923003274661805836407369665432566039311865085952) ≤ 0 by norm_num)
  unfold rowsCellR2ZP043Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP043_eq_semantic : rowsCellR2ZP043Expr30 =
    semanticQuantity130f (dualQ130fR2 43) 43 2 2 := by
  calc
    rowsCellR2ZP043Expr30 = rowsCellR2ZP043Raw30.value := rowsCellR2ZP043_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 43) 43 2 2).value := by
      rw [rowsCellR2ZP043_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP043_coefficient

theorem rowsCellR2ZP043 : ((458546039117079147109 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 43) 43 2
      (roleIndex30 .Z) := by
  change ((458546039117079147109 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 43) 43 2 2
  rw [← rowsCellR2ZP043_eq_semantic]
  exact rowsCellR2ZP043_lower

noncomputable def rowsCellR2ZP044Expr30 : ℝ :=
  ((822873403655446021343276268105 : ℝ) / 1298074214633706907132624082305024) * Real.negMulLog ((65431416490119673746930421385233330664911362063087 : ℝ) / 6129982163463555433433388108601236734474956488734408704)
    + ((-1616717590979269970950106493605397022395050873715 : ℝ) / 5986310706507378352962293074805895248510699696029696) * Real.negMulLog ((5020901409631743 : ℝ) / 18446744073709551616)
    + ((822873403655446021343276268105 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((5993324527118293 : ℝ) / 18446744073709551616)
    + ((822873403655446021343276268105 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((5993449337899443 : ℝ) / 18446744073709551616)
    + ((822873403655446021343276268105 : ℝ) / 1298074214633706907132624082305024) * Real.negMulLog ((42452809615450455 : ℝ) / 2305843009213693952)
    + ((822873403655446021343276268105 : ℝ) / 1298074214633706907132624082305024) * Real.negMulLog ((21226411049170579 : ℝ) / 1152921504606846976)
    + ((822873403655446021343276268105 : ℝ) / 2596148429267413814265248164610048) * Real.negMulLog ((60388575699139079472880331164693684372507708791719185 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((822873403655446021343276268105 : ℝ) / 2596148429267413814265248164610048) * Real.negMulLog ((60388587545886994992409207663332344918820868246734097 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((-1616717590979269970950106493605397022395050873715 : ℝ) / 5986310706507378352962293074805895248510699696029696) * Real.negMulLog ((6632900620309123 : ℝ) / 144115188075855872)
    + ((-69866586157843485118611250959829793370288403365 : ℝ) / 748288838313422294120286634350736906063837462003712) * Real.negMulLog ((1 : ℝ) / 2)
    + ((822873403655446021343276268105 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((1184939238644289045532146356324241367963564170183441135 : ℝ) / 1532495540865888858358347027150309183618739122183602176)
    + ((-1616717590979269970950106493605397022395050873715 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((65424693417618813 : ℝ) / 72057594037927936)
    + ((-1616717590979269970950106493605397022395050873715 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((9218351135445144065 : ℝ) / 9223372036854775808)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP044_value_bridge : rowsCellR2ZP044Expr30 = rowsCellR2ZP044Raw30.value := by
  unfold rowsCellR2ZP044Expr30 rowsCellR2ZP044Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP044_coefficient :
    ((dualQ130fR2 44).coefficient : ℝ) =
      (coefficientQ130f 2 44 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP044R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 44 := OmegaBound.ADVXXZT6Round61.coefficientP044R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 44).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP044_lower : ((3663016163723130817 : ℝ) / 40000000000000000000000) ≤ rowsCellR2ZP044Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19006_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 1298074214633706907132624082305024) by norm_num)
  have h1 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07752_upper
    (show ((-1616717590979269970950106493605397022395050873715 : ℝ) / 5986310706507378352962293074805895248510699696029696) ≤ 0 by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08647_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08648_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12247_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 1298074214633706907132624082305024) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11444_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 1298074214633706907132624082305024) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19550_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 2596148429267413814265248164610048) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19551_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 2596148429267413814265248164610048) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom09429_upper
    (show ((-1616717590979269970950106493605397022395050873715 : ℝ) / 5986310706507378352962293074805895248510699696029696) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-69866586157843485118611250959829793370288403365 : ℝ) / 748288838313422294120286634350736906063837462003712) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19797_lower
    (show 0 ≤ ((822873403655446021343276268105 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h11 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12825_upper
    (show ((-1616717590979269970950106493605397022395050873715 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  have h12 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom15389_upper
    (show ((-1616717590979269970950106493605397022395050873715 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  unfold rowsCellR2ZP044Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP044_eq_semantic : rowsCellR2ZP044Expr30 =
    semanticQuantity130f (dualQ130fR2 44) 44 2 2 := by
  calc
    rowsCellR2ZP044Expr30 = rowsCellR2ZP044Raw30.value := rowsCellR2ZP044_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 44) 44 2 2).value := by
      rw [rowsCellR2ZP044_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP044_coefficient

theorem rowsCellR2ZP044 : ((3663016163723130817 : ℝ) / 40000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 44) 44 2
      (roleIndex30 .Z) := by
  change ((3663016163723130817 : ℝ) / 40000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 44) 44 2 2
  rw [← rowsCellR2ZP044_eq_semantic]
  exact rowsCellR2ZP044_lower

noncomputable def rowsCellR2ZP045Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP045_value_bridge : rowsCellR2ZP045Expr30 = rowsCellR2ZP045Raw30.value := by
  unfold rowsCellR2ZP045Expr30 rowsCellR2ZP045Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP045_coefficient :
    ((dualQ130fR2 45).coefficient : ℝ) =
      (coefficientQ130f 2 45 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP045R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 45 := OmegaBound.ADVXXZT6Round61.coefficientP045R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 45).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP045_lower : (0 : ℝ) ≤ rowsCellR2ZP045Expr30 := by
  unfold rowsCellR2ZP045Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP045_eq_semantic : rowsCellR2ZP045Expr30 =
    semanticQuantity130f (dualQ130fR2 45) 45 2 2 := by
  calc
    rowsCellR2ZP045Expr30 = rowsCellR2ZP045Raw30.value := rowsCellR2ZP045_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 45) 45 2 2).value := by
      rw [rowsCellR2ZP045_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP045_coefficient

theorem rowsCellR2ZP045 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 45) 45 2
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 45) 45 2 2
  rw [← rowsCellR2ZP045_eq_semantic]
  exact rowsCellR2ZP045_lower

noncomputable def rowsCellR2ZP046Expr30 : ℝ :=
  ((18593508169492611631412145229151 : ℝ) / 62307562302417931542365955950641152) * Real.negMulLog ((34616095037289624249916182530033 : ℝ) / 5192296858534827628530496329220096)
    + ((18593508169492611631412145229151 : ℝ) / 62307562302417931542365955950641152) * Real.negMulLog ((34616096737133101641416667033381 : ℝ) / 5192296858534827628530496329220096)
    + ((-118567447655699128821672596724102260809399222477 : ℝ) / 1122433257470133441180429951526105359095756193005568) * Real.negMulLog ((5428426388529641 : ℝ) / 144115188075855872)
    + ((18593508169492611631412145229151 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((727928075279597139 : ℝ) / 4611686018427387904)
    + ((18593508169492611631412145229151 : ℝ) / 124615124604835863084731911901282304) * Real.negMulLog ((443883929409470701417140574228699 : ℝ) / 2596148429267413814265248164610048)
    + ((18593508169492611631412145229151 : ℝ) / 124615124604835863084731911901282304) * Real.negMulLog ((443884003792662368912046353512463 : ℝ) / 2596148429267413814265248164610048)
    + ((-4511578871504740733246571234019093216749372999663 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-118567447655699128821672596724102260809399222477 : ℝ) / 2244866514940266882360859903052210718191512386011136) * Real.negMulLog ((66629167649398295 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP046_value_bridge : rowsCellR2ZP046Expr30 = rowsCellR2ZP046Raw30.value := by
  unfold rowsCellR2ZP046Expr30 rowsCellR2ZP046Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP046_coefficient :
    ((dualQ130fR2 46).coefficient : ℝ) =
      (coefficientQ130f 2 46 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP046R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 46 := OmegaBound.ADVXXZT6Round61.coefficientP046R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 46).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP046_lower : ((1706283251485202957 : ℝ) / 12500000000000000000000) ≤ rowsCellR2ZP046Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16237_lower
    (show 0 ≤ ((18593508169492611631412145229151 : ℝ) / 62307562302417931542365955950641152) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16238_lower
    (show 0 ≤ ((18593508169492611631412145229151 : ℝ) / 62307562302417931542365955950641152) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom08057_upper
    (show ((-118567447655699128821672596724102260809399222477 : ℝ) / 1122433257470133441180429951526105359095756193005568) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14620_lower
    (show 0 ≤ ((18593508169492611631412145229151 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16869_lower
    (show 0 ≤ ((18593508169492611631412145229151 : ℝ) / 124615124604835863084731911901282304) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16870_lower
    (show 0 ≤ ((18593508169492611631412145229151 : ℝ) / 124615124604835863084731911901282304) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-4511578871504740733246571234019093216749372999663 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12904_upper
    (show ((-118567447655699128821672596724102260809399222477 : ℝ) / 2244866514940266882360859903052210718191512386011136) ≤ 0 by norm_num)
  unfold rowsCellR2ZP046Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP046_eq_semantic : rowsCellR2ZP046Expr30 =
    semanticQuantity130f (dualQ130fR2 46) 46 2 2 := by
  calc
    rowsCellR2ZP046Expr30 = rowsCellR2ZP046Raw30.value := rowsCellR2ZP046_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 46) 46 2 2).value := by
      rw [rowsCellR2ZP046_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP046_coefficient

theorem rowsCellR2ZP046 : ((1706283251485202957 : ℝ) / 12500000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 46) 46 2
      (roleIndex30 .Z) := by
  change ((1706283251485202957 : ℝ) / 12500000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 46) 46 2 2
  rw [← rowsCellR2ZP046_eq_semantic]
  exact rowsCellR2ZP046_lower

noncomputable def rowsCellR2ZP047Expr30 : ℝ :=
  ((3067945684931716044121198818495 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((9006892382560637 : ℝ) / 36028797018963968)
    + ((3067945684931716044121198818495 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((9007506126921347 : ℝ) / 36028797018963968)
    + ((-3067945684931716044121198818495 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP047_value_bridge : rowsCellR2ZP047Expr30 = rowsCellR2ZP047Raw30.value := by
  unfold rowsCellR2ZP047Expr30 rowsCellR2ZP047Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP047_coefficient :
    ((dualQ130fR2 47).coefficient : ℝ) =
      (coefficientQ130f 2 47 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP047R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 47 := OmegaBound.ADVXXZT6Round61.coefficientP047R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 47).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP047_lower : ((2559726886986236813 : ℝ) / 200000000000000000000000) ≤ rowsCellR2ZP047Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10931_lower
    (show 0 ≤ ((3067945684931716044121198818495 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10962_lower
    (show 0 ≤ ((3067945684931716044121198818495 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-3067945684931716044121198818495 : ℝ) / 83076749736557242056487941267521536) ≤ 0 by norm_num)
  unfold rowsCellR2ZP047Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP047_eq_semantic : rowsCellR2ZP047Expr30 =
    semanticQuantity130f (dualQ130fR2 47) 47 2 2 := by
  calc
    rowsCellR2ZP047Expr30 = rowsCellR2ZP047Raw30.value := rowsCellR2ZP047_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 47) 47 2 2).value := by
      rw [rowsCellR2ZP047_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP047_coefficient

theorem rowsCellR2ZP047 : ((2559726886986236813 : ℝ) / 200000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 47) 47 2
      (roleIndex30 .Z) := by
  change ((2559726886986236813 : ℝ) / 200000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 47) 47 2 2
  rw [← rowsCellR2ZP047_eq_semantic]
  exact rowsCellR2ZP047_lower

noncomputable def rowsCellR2ZP048Expr30 : ℝ :=
  ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((474361071039067 : ℝ) / 144115188075855872)
    + ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((1897478020273483 : ℝ) / 576460752303423488)
    + ((40314534654320801897126105089517 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((42706935576124350886453914166575 : ℝ) / 10384593717069655257060992658440192)
    + ((40314534654320801897126105089517 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((21353475597480507384247961829725 : ℝ) / 5192296858534827628530496329220096)
    + ((-502273594428811392128969737008839551136883790747 : ℝ) / 1122433257470133441180429951526105359095756193005568) * Real.negMulLog ((6855668178433775 : ℝ) / 144115188075855872)
    + ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((1238276167899778482389572256996049 : ℝ) / 5192296858534827628530496329220096)
    + ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((619138376622145172524958152867491 : ℝ) / 2596148429267413814265248164610048)
    + ((-40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-502273594428811392128969737008839551136883790747 : ℝ) / 2244866514940266882360859903052210718191512386011136) * Real.negMulLog ((65201925859494161 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP048_value_bridge : rowsCellR2ZP048Expr30 = rowsCellR2ZP048Raw30.value := by
  unfold rowsCellR2ZP048Expr30 rowsCellR2ZP048Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP048_coefficient :
    ((dualQ130fR2 48).coefficient : ℝ) =
      (coefficientQ130f 2 48 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP048R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 48 := OmegaBound.ADVXXZT6Round61.coefficientP048R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 48).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP048_lower : ((258421844920472717947 : ℝ) / 500000000000000000000000) ≤ rowsCellR2ZP048Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom04386_lower
    (show 0 ≤ ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom05512_lower
    (show 0 ≤ ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16296_lower
    (show 0 ≤ ((40314534654320801897126105089517 : ℝ) / 15576890575604482885591488987660288) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16115_lower
    (show 0 ≤ ((40314534654320801897126105089517 : ℝ) / 15576890575604482885591488987660288) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom09582_upper
    (show ((-502273594428811392128969737008839551136883790747 : ℝ) / 1122433257470133441180429951526105359095756193005568) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17207_lower
    (show 0 ≤ ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17000_lower
    (show 0 ≤ ((40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-40314534654320801897126105089517 : ℝ) / 31153781151208965771182977975320576) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12784_upper
    (show ((-502273594428811392128969737008839551136883790747 : ℝ) / 2244866514940266882360859903052210718191512386011136) ≤ 0 by norm_num)
  unfold rowsCellR2ZP048Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP048_eq_semantic : rowsCellR2ZP048Expr30 =
    semanticQuantity130f (dualQ130fR2 48) 48 2 2 := by
  calc
    rowsCellR2ZP048Expr30 = rowsCellR2ZP048Raw30.value := rowsCellR2ZP048_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 48) 48 2 2).value := by
      rw [rowsCellR2ZP048_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP048_coefficient

theorem rowsCellR2ZP048 : ((258421844920472717947 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 48) 48 2
      (roleIndex30 .Z) := by
  change ((258421844920472717947 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 48) 48 2 2
  rw [← rowsCellR2ZP048_eq_semantic]
  exact rowsCellR2ZP048_lower

noncomputable def rowsCellR2ZP049Expr30 : ℝ :=
  ((22772231157281764198993833350209 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((369475752988465 : ℝ) / 1152921504606846976)
    + ((22772231157281764198993833350209 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((5911639675264971 : ℝ) / 18446744073709551616)
    + ((22772231157281764198993833350209 : ℝ) / 973555660975280180349468061728768) * Real.negMulLog ((19766636285243561640473669616721635550920074430685765 : ℝ) / 24519928653854221733733552434404946937899825954937634816)
    + ((-235220386369211998918733003268720409113062372386405 : ℝ) / 17958932119522135058886879224417685745532099088089088) * Real.negMulLog ((1766870862622511 : ℝ) / 1152921504606846976)
    + ((22772231157281764198993833350209 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((179168363040383409771126739631215309811105141845220795 : ℝ) / 12259964326927110866866776217202473468949912977468817408)
    + ((22772231157281764198993833350209 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((179168363040393981528243223514700812762926948745829819 : ℝ) / 12259964326927110866866776217202473468949912977468817408)
    + ((22772231157281764198993833350209 : ℝ) / 973555660975280180349468061728768) * Real.negMulLog ((10516896981254097 : ℝ) / 576460752303423488)
    + ((22772231157281764198993833350209 : ℝ) / 973555660975280180349468061728768) * Real.negMulLog ((10516897185818547 : ℝ) / 576460752303423488)
    + ((-240768808253283194388833565269371665394716117721 : ℝ) / 70152078591883340073776871970381584943484762062848) * Real.negMulLog ((3773396243058965 : ℝ) / 72057594037927936)
    + ((-240768808253283194388833565269371665394716117721 : ℝ) / 70152078591883340073776871970381584943484762062848) * Real.negMulLog ((7547736412008597 : ℝ) / 144115188075855872)
    + ((-39915535240605258112037957972422320038399631883 : ℝ) / 11692013098647223345629478661730264157247460343808) * Real.negMulLog ((1 : ℝ) / 2)
    + ((22772231157281764198993833350209 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((4853271193737238214119462702952095866924628253515620933 : ℝ) / 6129982163463555433433388108601236734474956488734408704)
    + ((-240768808253283194388833565269371665394716117721 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((64509857625919339 : ℝ) / 72057594037927936)
    + ((-240768808253283194388833565269371665394716117721 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((32255400775905003 : ℝ) / 36028797018963968)
    + ((-235220386369211998918733003268720409113062372386405 : ℝ) / 35917864239044270117773758448835371491064198176178176) * Real.negMulLog ((574693881440800977 : ℝ) / 576460752303423488)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP049_value_bridge : rowsCellR2ZP049Expr30 = rowsCellR2ZP049Raw30.value := by
  unfold rowsCellR2ZP049Expr30 rowsCellR2ZP049Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP049_coefficient :
    ((dualQ130fR2 49).coefficient : ℝ) =
      (coefficientQ130f 2 49 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP049R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 49 := OmegaBound.ADVXXZT6Round61.coefficientP049R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 49).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP049_lower : ((3373984006755530547807 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2ZP049Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom04278_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08579_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19472_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 973555660975280180349468061728768) by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom05466_upper
    (show ((-235220386369211998918733003268720409113062372386405 : ℝ) / 17958932119522135058886879224417685745532099088089088) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19663_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19664_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11001_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 973555660975280180349468061728768) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11002_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 973555660975280180349468061728768) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07028_upper
    (show ((-240768808253283194388833565269371665394716117721 : ℝ) / 70152078591883340073776871970381584943484762062848) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom09989_upper
    (show ((-240768808253283194388833565269371665394716117721 : ℝ) / 70152078591883340073776871970381584943484762062848) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-39915535240605258112037957972422320038399631883 : ℝ) / 11692013098647223345629478661730264157247460343808) ≤ 0 by norm_num)
  have h11 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19868_lower
    (show 0 ≤ ((22772231157281764198993833350209 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h12 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12709_upper
    (show ((-240768808253283194388833565269371665394716117721 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h13 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11739_upper
    (show ((-240768808253283194388833565269371665394716117721 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h14 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom14391_upper
    (show ((-235220386369211998918733003268720409113062372386405 : ℝ) / 35917864239044270117773758448835371491064198176178176) ≤ 0 by norm_num)
  unfold rowsCellR2ZP049Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP049_eq_semantic : rowsCellR2ZP049Expr30 =
    semanticQuantity130f (dualQ130fR2 49) 49 2 2 := by
  calc
    rowsCellR2ZP049Expr30 = rowsCellR2ZP049Raw30.value := rowsCellR2ZP049_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 49) 49 2 2).value := by
      rw [rowsCellR2ZP049_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP049_coefficient

theorem rowsCellR2ZP049 : ((3373984006755530547807 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 49) 49 2
      (roleIndex30 .Z) := by
  change ((3373984006755530547807 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 49) 49 2 2
  rw [← rowsCellR2ZP049_eq_semantic]
  exact rowsCellR2ZP049_lower

noncomputable def rowsCellR2ZP050Expr30 : ℝ :=
  ((5936349588999316870724695605125 : ℝ) / 243388915243820045087367015432192) * Real.negMulLog ((25460816429751480980045811028681 : ℝ) / 5192296858534827628530496329220096)
    + ((5936349588999316870724695605125 : ℝ) / 243388915243820045087367015432192) * Real.negMulLog ((25460868549651194733140407665081 : ℝ) / 5192296858534827628530496329220096)
    + ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) * Real.negMulLog ((31305856448385061 : ℝ) / 4611686018427387904)
    + ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) * Real.negMulLog ((62614017203572167 : ℝ) / 9223372036854775808)
    + ((-38355163223599803280394593275096817359485265875 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((242323341945815 : ℝ) / 4503599627370496)
    + ((-2158505582494168845216282849305277020491794625 : ℝ) / 548063113999088594326381812268606132370974703616) * Real.negMulLog ((4107300893339193 : ℝ) / 72057594037927936)
    + ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) * Real.negMulLog ((605952062280150411942686723751495 : ℝ) / 2596148429267413814265248164610048)
    + ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) * Real.negMulLog ((605952557910585079638502226128183 : ℝ) / 2596148429267413814265248164610048)
    + ((-5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-2158505582494168845216282849305277020491794625 : ℝ) / 1096126227998177188652763624537212264741949407232) * Real.negMulLog ((31921496125624775 : ℝ) / 36028797018963968)
    + ((-38355163223599803280394593275096817359485265875 : ℝ) / 280608314367533360295107487881526339773939048251392) * Real.negMulLog ((2009476471739433 : ℝ) / 2251799813685248)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP050_value_bridge : rowsCellR2ZP050Expr30 = rowsCellR2ZP050Raw30.value := by
  unfold rowsCellR2ZP050Expr30 rowsCellR2ZP050Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2ZP050_coefficient :
    ((dualQ130fR2 50).coefficient : ℝ) =
      (coefficientQ130f 2 50 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP050R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 50 := OmegaBound.ADVXXZT6Round61.coefficientP050R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 50).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP050_lower : ((5243925408508108557243 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2ZP050Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16171_lower
    (show 0 ≤ ((5936349588999316870724695605125 : ℝ) / 243388915243820045087367015432192) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16172_lower
    (show 0 ≤ ((5936349588999316870724695605125 : ℝ) / 243388915243820045087367015432192) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11662_lower
    (show 0 ≤ ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12572_lower
    (show 0 ≤ ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom04175_upper
    (show ((-38355163223599803280394593275096817359485265875 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07246_upper
    (show ((-2158505582494168845216282849305277020491794625 : ℝ) / 548063113999088594326381812268606132370974703616) ≤ 0 by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16945_lower
    (show 0 ≤ ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16946_lower
    (show 0 ≤ ((5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-5936349588999316870724695605125 : ℝ) / 486777830487640090174734030864384) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11685_upper
    (show ((-2158505582494168845216282849305277020491794625 : ℝ) / 1096126227998177188652763624537212264741949407232) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom05581_upper
    (show ((-38355163223599803280394593275096817359485265875 : ℝ) / 280608314367533360295107487881526339773939048251392) ≤ 0 by norm_num)
  unfold rowsCellR2ZP050Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2ZP050_eq_semantic : rowsCellR2ZP050Expr30 =
    semanticQuantity130f (dualQ130fR2 50) 50 2 2 := by
  calc
    rowsCellR2ZP050Expr30 = rowsCellR2ZP050Raw30.value := rowsCellR2ZP050_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 50) 50 2 2).value := by
      rw [rowsCellR2ZP050_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2ZP050_coefficient

theorem rowsCellR2ZP050 : ((5243925408508108557243 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 50) 50 2
      (roleIndex30 .Z) := by
  change ((5243925408508108557243 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 50) 50 2 2
  rw [← rowsCellR2ZP050_eq_semantic]
  exact rowsCellR2ZP050_lower


end OmegaBound.ADVXXZGeneral
