-- Generated by `tools/advxxz_retained_cert.py` of the development repository (not part of this release).
import OmegaBound.ADVXXZT7EnrichedShard00
import OmegaBound.ADVXXZT7EnrichedShard01
import OmegaBound.ADVXXZT7EnrichedShard02
import OmegaBound.ADVXXZT7EnrichedShard03
import OmegaBound.ADVXXZT7EnrichedShard04
import OmegaBound.ADVXXZT7EnrichedShard05
import OmegaBound.ADVXXZT7EnrichedShard06
import OmegaBound.ADVXXZT7EnrichedShard07
import OmegaBound.ADVXXZT7EnrichedShard08
import OmegaBound.ADVXXZT7EnrichedShard09
import OmegaBound.ADVXXZT7EnrichedShard10
import OmegaBound.ADVXXZT7EnrichedShard11
import OmegaBound.ADVXXZT7EnrichedShard12
import OmegaBound.ADVXXZT7EnrichedShard13
import OmegaBound.ADVXXZT7EnrichedShard14
import OmegaBound.ADVXXZT7EnrichedShard15
import OmegaBound.ADVXXZT7EnrichedShard16
import OmegaBound.ADVXXZT7EnrichedShard17
set_option maxRecDepth 1000000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZT7Enriched

open OmegaBound.ADVXXZCertSemantic (Level2TermId)

def enrichedRows : List RawEnrichedRow :=
  enrichedRows00
    ++ enrichedRows01
    ++ enrichedRows02
    ++ enrichedRows03
    ++ enrichedRows04
    ++ enrichedRows05
    ++ enrichedRows06
    ++ enrichedRows07
    ++ enrichedRows08
    ++ enrichedRows09
    ++ enrichedRows10
    ++ enrichedRows11
    ++ enrichedRows12
    ++ enrichedRows13
    ++ enrichedRows14
    ++ enrichedRows15
    ++ enrichedRows16
    ++ enrichedRows17

theorem enrichedRows_length : enrichedRows.length = 5508 := by
  simp [enrichedRows, (enrichedRows00_ok).1, (enrichedRows01_ok).1, (enrichedRows02_ok).1, (enrichedRows03_ok).1, (enrichedRows04_ok).1, (enrichedRows05_ok).1, (enrichedRows06_ok).1, (enrichedRows07_ok).1, (enrichedRows08_ok).1, (enrichedRows09_ok).1, (enrichedRows10_ok).1, (enrichedRows11_ok).1, (enrichedRows12_ok).1, (enrichedRows13_ok).1, (enrichedRows14_ok).1, (enrichedRows15_ok).1, (enrichedRows16_ok).1, (enrichedRows17_ok).1]

def shardRows : Fin 18 -> List RawEnrichedRow
  | 0 => enrichedRows00
  | 1 => enrichedRows01
  | 2 => enrichedRows02
  | 3 => enrichedRows03
  | 4 => enrichedRows04
  | 5 => enrichedRows05
  | 6 => enrichedRows06
  | 7 => enrichedRows07
  | 8 => enrichedRows08
  | 9 => enrichedRows09
  | 10 => enrichedRows10
  | 11 => enrichedRows11
  | 12 => enrichedRows12
  | 13 => enrichedRows13
  | 14 => enrichedRows14
  | 15 => enrichedRows15
  | 16 => enrichedRows16
  | _ => enrichedRows17

set_option maxHeartbeats 1000000 in
-- Elaborating the 18-way finite split needs more than the default budget; no proof search occurs.
theorem shardRows_ok (b : Fin 18) : ShardOK (306 * b.1) (shardRows b) := by
  fin_cases b <;> first | exact enrichedRows00_ok | exact enrichedRows01_ok | exact enrichedRows02_ok | exact enrichedRows03_ok | exact enrichedRows04_ok | exact enrichedRows05_ok | exact enrichedRows06_ok | exact enrichedRows07_ok | exact enrichedRows08_ok | exact enrichedRows09_ok | exact enrichedRows10_ok | exact enrichedRows11_ok | exact enrichedRows12_ok | exact enrichedRows13_ok | exact enrichedRows14_ok | exact enrichedRows15_ok | exact enrichedRows16_ok | exact enrichedRows17_ok

def shardIndex (i : Level2TermId) : Fin 18 := ⟨i.1 / 306, by omega⟩

def shardOffset (i : Level2TermId) : Fin 306 :=
  ⟨i.1 % 306, Nat.mod_lt _ (by omega)⟩

def enrichedRow (i : Level2TermId) : RawEnrichedRow :=
  (shardRows (shardIndex i)).getD (shardOffset i).1 dummyRow

/-- Every node can be opened through its own checked shard, without a second 5,508-row check. -/
theorem enrichedRow_ok (i : Level2TermId) :
    RowOK (enrichedRow i) (releasedAt i.1) := by
  have h := (shardRows_ok (shardIndex i)).2 (shardOffset i)
  have hi : 306 * (i.1 / 306) + i.1 % 306 = i.1 := by
    rw [Nat.add_comm]
    exact Nat.mod_add_div i.1 306
  simpa [enrichedRow, shardIndex, shardOffset, hi] using h

/-- Global access theorem.  The generator has already factored the verdict into
eighteen 306-node shards, each checked by one `native_decide`; this theorem only exposes their conjunction. -/
def EnrichedShardLaws : Prop :=
  ShardOK 0 enrichedRows00 ∧
  ShardOK 306 enrichedRows01 ∧
  ShardOK 612 enrichedRows02 ∧
  ShardOK 918 enrichedRows03 ∧
  ShardOK 1224 enrichedRows04 ∧
  ShardOK 1530 enrichedRows05 ∧
  ShardOK 1836 enrichedRows06 ∧
  ShardOK 2142 enrichedRows07 ∧
  ShardOK 2448 enrichedRows08 ∧
  ShardOK 2754 enrichedRows09 ∧
  ShardOK 3060 enrichedRows10 ∧
  ShardOK 3366 enrichedRows11 ∧
  ShardOK 3672 enrichedRows12 ∧
  ShardOK 3978 enrichedRows13 ∧
  ShardOK 4284 enrichedRows14 ∧
  ShardOK 4590 enrichedRows15 ∧
  ShardOK 4896 enrichedRows16 ∧
  ShardOK 5202 enrichedRows17

theorem enriched_shard_laws : EnrichedShardLaws :=
  ⟨enrichedRows00_ok, enrichedRows01_ok, enrichedRows02_ok, enrichedRows03_ok, enrichedRows04_ok, enrichedRows05_ok, enrichedRows06_ok, enrichedRows07_ok, enrichedRows08_ok, enrichedRows09_ok, enrichedRows10_ok, enrichedRows11_ok, enrichedRows12_ok, enrichedRows13_ok, enrichedRows14_ok, enrichedRows15_ok, enrichedRows16_ok, enrichedRows17_ok⟩

end OmegaBound.ADVXXZT7Enriched
