-- Generated by `tools/ctriple/genregions.py` of the development repository (not part of this release).
-- The release tooling removed unused declarations and rewrote its imports.
import OmegaBound.ADVXXZCertRegionalSemanticBase
import OmegaBound.ADVXXZCertSemantic
set_option maxRecDepth 1000000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZR5CertificateSplitData

open ADVXXZ

def r5ResXRow40Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 26 => 467928552954663648194957339660253966597340914532
  | 44 => 21265691909200183525006045086595527448262501742904
  | 50 => 35667562847147354691315443608581789879663849373696
  | 52 => 35667562847147354691315443608581789879663849373696
  | 62 => 467928552954663648194957339660253966597340914532
  | 68 => 35667562847147354691315443608581789879663849373696
  | 70 => 35667562847147354691315443608581789879663849373696
  | 74 => 467904529228326031089066399432573666889425269377
  | 76 => 21264600116199991881235791588575884282067933895422
  | 78 => 467904529228326031089066399432573666889425269377
  | _ => 0

def r5ResXRow40Dist : SplitDist 4 where
  num := r5ResXRow40Num
  den := 187072209578355573530071658587684226515959365500928
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r5ResXRow41Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 26 => 7940950163291154
  | 44 => 179161920287256992
  | 50 => 190708481343258077
  | 52 => 190708480455508224
  | 62 => 7940950152574601
  | 68 => 190708480487477632
  | 70 => 190708480470849088
  | 74 => 7940949337412430
  | 76 => 179161863182743936
  | 78 => 7940948726474842
  | _ => 0

def r5ResXRow41Dist : SplitDist 4 where
  num := r5ResXRow41Num
  den := 1152921504606846976
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r5ResXRow42Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 53 => 2251799813685249
  | 71 => 2251799813685240
  | 77 => 2251799813685252
  | 79 => 2251799813685251
  | _ => 0

def r5ResXRow42Dist : SplitDist 4 where
  num := r5ResXRow42Num
  den := 9007199254740992
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r5ResXRow43Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 53 => 2251799813685249
  | 71 => 2251799813685240
  | 77 => 2251799813685252
  | 79 => 2251799813685251
  | _ => 0

def r5ResXRow43Dist : SplitDist 4 where
  num := r5ResXRow43Num
  den := 9007199254740992
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r5ResXRow44Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 80 => 1
  | _ => 0

def r5ResXRow44Dist : SplitDist 4 where
  num := r5ResXRow44Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

end OmegaBound.ADVXXZR5CertificateSplitData
