-- Generated by `tools/ctriple/genregions.py` of the development repository (not part of this release).
-- The release tooling removed unused declarations and rewrote its imports.
import OmegaBound.ADVXXZCertRegionalSemanticBase
import OmegaBound.ADVXXZCertSemantic
set_option maxRecDepth 1000000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZR1CertificateSplitData

open ADVXXZ

def r1ResXRow00Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow00Dist : SplitDist 4 where
  num := r1ResXRow00Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow01Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow01Dist : SplitDist 4 where
  num := r1ResXRow01Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow02Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow02Dist : SplitDist 4 where
  num := r1ResXRow02Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow03Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow03Dist : SplitDist 4 where
  num := r1ResXRow03Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow04Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow04Dist : SplitDist 4 where
  num := r1ResXRow04Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow05Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow05Dist : SplitDist 4 where
  num := r1ResXRow05Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow06Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow06Dist : SplitDist 4 where
  num := r1ResXRow06Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r1ResXRow07Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r1ResXRow07Dist : SplitDist 4 where
  num := r1ResXRow07Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

end OmegaBound.ADVXXZR1CertificateSplitData
