-- Generated by `tools/iapply_cells.py` (cells mode) of the development repository (not part of this release).
-- The release tooling rewrote its imports.
import OmegaBound.ReleaseCompactRowsR4Z6Check
import OmegaBound.ADVXXZGeneralRowsSemanticCore30
import OmegaBound.ReleaseCompactR61CohortR4P096P125Check
import OmegaBound.ADVXXZRetainedAtom039
import OmegaBound.ADVXXZRetainedAtom048
import OmegaBound.ADVXXZRetainedAtom051
import OmegaBound.ADVXXZRetainedAtom052
import OmegaBound.ADVXXZRetainedAtom055
import OmegaBound.ADVXXZRetainedAtom059
import OmegaBound.ADVXXZRetainedAtom060
import OmegaBound.ADVXXZRetainedAtom068
import OmegaBound.ADVXXZRetainedAtom070
import OmegaBound.ADVXXZRetainedAtom071
import OmegaBound.ADVXXZRetainedAtom072
import OmegaBound.ADVXXZRetainedAtom076
import OmegaBound.ADVXXZRetainedAtom077
import OmegaBound.ADVXXZRetainedAtom080
import OmegaBound.ADVXXZRetainedAtom081
import OmegaBound.ADVXXZRetainedAtom083
import OmegaBound.ADVXXZRetainedAtom085
import OmegaBound.ADVXXZRetainedAtom087
import OmegaBound.ADVXXZRetainedAtom090
import OmegaBound.ADVXXZRetainedAtom101
import OmegaBound.ADVXXZRetainedAtom102
import OmegaBound.ADVXXZRetainedAtom103
import OmegaBound.ADVXXZRetainedAtom104
import OmegaBound.ADVXXZRetainedAtom110
import OmegaBound.ADVXXZRetainedAtom112
import OmegaBound.ADVXXZRetainedAtom113
import OmegaBound.ADVXXZRetainedAtom114
import OmegaBound.ADVXXZRetainedAtom117
import OmegaBound.ADVXXZRetainedAtom120
import OmegaBound.ADVXXZRetainedAtom121
import OmegaBound.ADVXXZRetainedAtom122
import OmegaBound.ADVXXZRetainedAtom123
import OmegaBound.ADVXXZRetainedAtom125
import OmegaBound.ADVXXZRetainedAtom126
import OmegaBound.ADVXXZRetainedAtom128
import OmegaBound.ADVXXZRetainedAtom129
import OmegaBound.ADVXXZRetainedAtom130
import OmegaBound.ADVXXZRetainedAtom136
import OmegaBound.ADVXXZRetainedAtom137
import OmegaBound.ADVXXZRetainedAtom142
import OmegaBound.ADVXXZRetainedAtom143
import OmegaBound.ADVXXZRetainedAtom146
import OmegaBound.ADVXXZRetainedAtom150
import OmegaBound.ADVXXZRetainedAtom151
import OmegaBound.ADVXXZRetainedAtom156
import OmegaBound.ADVXXZRetainedAtom159
import OmegaBound.ADVXXZRetainedAtom160
import OmegaBound.ADVXXZRetainedAtom161
import OmegaBound.ADVXXZRetainedAtom162
import OmegaBound.ADVXXZRetainedAtom163
import OmegaBound.ADVXXZRetainedAtom166
import OmegaBound.ADVXXZRetainedAtom167
import OmegaBound.ADVXXZRetainedAtom168
import OmegaBound.ADVXXZRetainedAtom169
import OmegaBound.ADVXXZRetainedAtom170
import OmegaBound.ADVXXZRetainedAtom171
import OmegaBound.ADVXXZRetainedAtom175
import OmegaBound.ADVXXZRetainedAtom176
import OmegaBound.ADVXXZRetainedAtom178
import OmegaBound.ADVXXZRetainedAtom184
import OmegaBound.ADVXXZRetainedAtom185
import OmegaBound.ADVXXZRetainedAtom191
import OmegaBound.ADVXXZRetainedAtom192
import OmegaBound.ADVXXZRetainedAtom195
import OmegaBound.ADVXXZRetainedAtom196
import OmegaBound.ADVXXZRetainedAtom198

set_option maxRecDepth 1000000
set_option linter.style.longLine false

open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

noncomputable def rowsCellR4ZP102Expr30 : ℝ :=
  ((2663558512440728214315518474903 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((144115183939643959 : ℝ) / 576460752303423488)
    + ((2663558512440728214315518474903 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((144115192212067785 : ℝ) / 576460752303423488)
    + ((-2663558512440728214315518474903 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP102_value_bridge : rowsCellR4ZP102Expr30 = rowsCellR4ZP102Raw30.value := by
  unfold rowsCellR4ZP102Expr30 rowsCellR4ZP102Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP102_coefficient :
    ((dualQ130fR4 102).coefficient : ℝ) =
      (coefficientQ130f 4 102 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP102R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 102 := OmegaBound.ADVXXZT6Round61.coefficientP102R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 102).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP102_lower : ((118524172985216328591 : ℝ) / 500000000000000000000000) ≤ rowsCellR4ZP102Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom13687_lower
    (show 0 ≤ ((2663558512440728214315518474903 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom13708_lower
    (show 0 ≤ ((2663558512440728214315518474903 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-2663558512440728214315518474903 : ℝ) / 3894222643901120721397872246915072) ≤ 0 by norm_num)
  unfold rowsCellR4ZP102Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP102_eq_semantic : rowsCellR4ZP102Expr30 =
    semanticQuantity130f (dualQ130fR4 102) 102 4 2 := by
  calc
    rowsCellR4ZP102Expr30 = rowsCellR4ZP102Raw30.value := rowsCellR4ZP102_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 102) 102 4 2).value := by
      rw [rowsCellR4ZP102_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP102_coefficient

theorem rowsCellR4ZP102 : ((118524172985216328591 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 102) 102 4
      (roleIndex30 .Z) := by
  change ((118524172985216328591 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 102) 102 4 2
  rw [← rowsCellR4ZP102_eq_semantic]
  exact rowsCellR4ZP102_lower

noncomputable def rowsCellR4ZP103Expr30 : ℝ :=
  ((14325867848875134820079874645555 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((32309264147867333278367090501369 : ℝ) / 5192296858534827628530496329220096)
    + ((14325867848875134820079874645555 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((32309271067369376592975111528361 : ℝ) / 5192296858534827628530496329220096)
    + ((-90796293655368603069444522477669930091568825925 : ℝ) / 1496577676626844588240573268701473812127674924007424) * Real.negMulLog ((5097766433038919 : ℝ) / 144115188075855872)
    + ((14325867848875134820079874645555 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((730783914604117427 : ℝ) / 4611686018427387904)
    + ((14325867848875134820079874645555 : ℝ) / 166153499473114484112975882535043072) * Real.negMulLog ((442975311480541908804451303284823 : ℝ) / 2596148429267413814265248164610048)
    + ((14325867848875134820079874645555 : ℝ) / 166153499473114484112975882535043072) * Real.negMulLog ((442975499821907388526171249678599 : ℝ) / 2596148429267413814265248164610048)
    + ((-10469113786702237945500127877892807407625223586985 : ℝ) / 47890485652059026823698344598447161988085597568237568) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-90796293655368603069444522477669930091568825925 : ℝ) / 2993155353253689176481146537402947624255349848014848) * Real.negMulLog ((66959827604889017 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP103_value_bridge : rowsCellR4ZP103Expr30 = rowsCellR4ZP103Raw30.value := by
  unfold rowsCellR4ZP103Expr30 rowsCellR4ZP103Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP103_coefficient :
    ((dualQ130fR4 103).coefficient : ℝ) =
      (coefficientQ130f 4 103 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP103R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 103 := OmegaBound.ADVXXZT6Round61.coefficientP103R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 103).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP103_lower : ((393034739567862447 : ℝ) / 5000000000000000000000) ≤ rowsCellR4ZP103Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16223_lower
    (show 0 ≤ ((14325867848875134820079874645555 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16224_lower
    (show 0 ≤ ((14325867848875134820079874645555 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07789_upper
    (show ((-90796293655368603069444522477669930091568825925 : ℝ) / 1496577676626844588240573268701473812127674924007424) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14635_lower
    (show 0 ≤ ((14325867848875134820079874645555 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16864_lower
    (show 0 ≤ ((14325867848875134820079874645555 : ℝ) / 166153499473114484112975882535043072) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16865_lower
    (show 0 ≤ ((14325867848875134820079874645555 : ℝ) / 166153499473114484112975882535043072) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-10469113786702237945500127877892807407625223586985 : ℝ) / 47890485652059026823698344598447161988085597568237568) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12921_upper
    (show ((-90796293655368603069444522477669930091568825925 : ℝ) / 2993155353253689176481146537402947624255349848014848) ≤ 0 by norm_num)
  unfold rowsCellR4ZP103Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP103_eq_semantic : rowsCellR4ZP103Expr30 =
    semanticQuantity130f (dualQ130fR4 103) 103 4 2 := by
  calc
    rowsCellR4ZP103Expr30 = rowsCellR4ZP103Raw30.value := rowsCellR4ZP103_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 103) 103 4 2).value := by
      rw [rowsCellR4ZP103_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP103_coefficient

theorem rowsCellR4ZP103 : ((393034739567862447 : ℝ) / 5000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 103) 103 4
      (roleIndex30 .Z) := by
  change ((393034739567862447 : ℝ) / 5000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 103) 103 4 2
  rw [← rowsCellR4ZP103_eq_semantic]
  exact rowsCellR4ZP103_lower

noncomputable def rowsCellR4ZP104Expr30 : ℝ :=
  ((1525926197868532294220433035767 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((36028796700413935 : ℝ) / 144115188075855872)
    + ((1525926197868532294220433035767 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((36028797337514001 : ℝ) / 144115188075855872)
    + ((-1525926197868532294220433035767 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP104_value_bridge : rowsCellR4ZP104Expr30 = rowsCellR4ZP104Raw30.value := by
  unfold rowsCellR4ZP104Expr30 rowsCellR4ZP104Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP104_coefficient :
    ((dualQ130fR4 104).coefficient : ℝ) =
      (coefficientQ130f 4 104 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP104R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 104 := OmegaBound.ADVXXZT6Round61.coefficientP104R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 104).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP104_lower : ((12731497622970941621 : ℝ) / 1000000000000000000000000) ≤ rowsCellR4ZP104Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12080_lower
    (show 0 ≤ ((1525926197868532294220433035767 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12113_lower
    (show 0 ≤ ((1525926197868532294220433035767 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-1525926197868532294220433035767 : ℝ) / 41538374868278621028243970633760768) ≤ 0 by norm_num)
  unfold rowsCellR4ZP104Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP104_eq_semantic : rowsCellR4ZP104Expr30 =
    semanticQuantity130f (dualQ130fR4 104) 104 4 2 := by
  calc
    rowsCellR4ZP104Expr30 = rowsCellR4ZP104Raw30.value := rowsCellR4ZP104_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 104) 104 4 2).value := by
      rw [rowsCellR4ZP104_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP104_coefficient

theorem rowsCellR4ZP104 : ((12731497622970941621 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 104) 104 4
      (roleIndex30 .Z) := by
  change ((12731497622970941621 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 104) 104 4 2
  rw [← rowsCellR4ZP104_eq_semantic]
  exact rowsCellR4ZP104_lower

noncomputable def rowsCellR4ZP105Expr30 : ℝ :=
  ((3070095275042980126802539698309 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((18013913445898219 : ℝ) / 72057594037927936)
    + ((3070095275042980126802539698309 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((18014883573065749 : ℝ) / 72057594037927936)
    + ((-3070095275042980126802539698309 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((1 : ℝ) / 2)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP105_value_bridge : rowsCellR4ZP105Expr30 = rowsCellR4ZP105Raw30.value := by
  unfold rowsCellR4ZP105Expr30 rowsCellR4ZP105Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP105_coefficient :
    ((dualQ130fR4 105).coefficient : ℝ) =
      (coefficientQ130f 4 105 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP105R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 105 := OmegaBound.ADVXXZT6Round61.coefficientP105R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 105).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP105_lower : ((3201900485968744523 : ℝ) / 250000000000000000000000) ≤ rowsCellR4ZP105Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11350_lower
    (show 0 ≤ ((3070095275042980126802539698309 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11407_lower
    (show 0 ≤ ((3070095275042980126802539698309 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-3070095275042980126802539698309 : ℝ) / 83076749736557242056487941267521536) ≤ 0 by norm_num)
  unfold rowsCellR4ZP105Expr30
  linarith [h0, h1, h2]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP105_eq_semantic : rowsCellR4ZP105Expr30 =
    semanticQuantity130f (dualQ130fR4 105) 105 4 2 := by
  calc
    rowsCellR4ZP105Expr30 = rowsCellR4ZP105Raw30.value := rowsCellR4ZP105_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 105) 105 4 2).value := by
      rw [rowsCellR4ZP105_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP105_coefficient

theorem rowsCellR4ZP105 : ((3201900485968744523 : ℝ) / 250000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 105) 105 4
      (roleIndex30 .Z) := by
  change ((3201900485968744523 : ℝ) / 250000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 105) 105 4 2
  rw [← rowsCellR4ZP105_eq_semantic]
  exact rowsCellR4ZP105_lower

noncomputable def rowsCellR4ZP106Expr30 : ℝ :=
  ((12622195627432265830710837348715 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((34618106134873556002784186623723 : ℝ) / 5192296858534827628530496329220096)
    + ((12622195627432265830710837348715 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((34618107371275419046320099325099 : ℝ) / 5192296858534827628530496329220096)
    + ((-80473138172471931406984871488476468847261890415 : ℝ) / 748288838313422294120286634350736906063837462003712) * Real.negMulLog ((5429843120472631 : ℝ) / 144115188075855872)
    + ((12622195627432265830710837348715 : ℝ) / 20769187434139310514121985316880384) * Real.negMulLog ((364009039790094025 : ℝ) / 2305843009213693952)
    + ((12622195627432265830710837348715 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((443780609664429159455426971929429 : ℝ) / 2596148429267413814265248164610048)
    + ((12622195627432265830710837348715 : ℝ) / 83076749736557242056487941267521536) * Real.negMulLog ((443780630138676177269717555845397 : ℝ) / 2596148429267413814265248164610048)
    + ((-4594593310384342470244947915247349126851562927875 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-80473138172471931406984871488476468847261890415 : ℝ) / 1496577676626844588240573268701473812127674924007424) * Real.negMulLog ((66627750917455305 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP106_value_bridge : rowsCellR4ZP106Expr30 = rowsCellR4ZP106Raw30.value := by
  unfold rowsCellR4ZP106Expr30 rowsCellR4ZP106Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP106_coefficient :
    ((dualQ130fR4 106).coefficient : ℝ) =
      (coefficientQ130f 4 106 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP106R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 106 := OmegaBound.ADVXXZT6Round61.coefficientP106R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 106).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP106_lower : ((138982532804356591249 : ℝ) / 1000000000000000000000000) ≤ rowsCellR4ZP106Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16240_lower
    (show 0 ≤ ((12622195627432265830710837348715 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16241_lower
    (show 0 ≤ ((12622195627432265830710837348715 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom08063_upper
    (show ((-80473138172471931406984871488476468847261890415 : ℝ) / 748288838313422294120286634350736906063837462003712) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom14242_lower
    (show 0 ≤ ((12622195627432265830710837348715 : ℝ) / 20769187434139310514121985316880384) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16866_lower
    (show 0 ≤ ((12622195627432265830710837348715 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16867_lower
    (show 0 ≤ ((12622195627432265830710837348715 : ℝ) / 83076749736557242056487941267521536) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-4594593310384342470244947915247349126851562927875 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12898_upper
    (show ((-80473138172471931406984871488476468847261890415 : ℝ) / 1496577676626844588240573268701473812127674924007424) ≤ 0 by norm_num)
  unfold rowsCellR4ZP106Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP106_eq_semantic : rowsCellR4ZP106Expr30 =
    semanticQuantity130f (dualQ130fR4 106) 106 4 2 := by
  calc
    rowsCellR4ZP106Expr30 = rowsCellR4ZP106Raw30.value := rowsCellR4ZP106_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 106) 106 4 2).value := by
      rw [rowsCellR4ZP106_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP106_coefficient

theorem rowsCellR4ZP106 : ((138982532804356591249 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 106) 106 4
      (roleIndex30 .Z) := by
  change ((138982532804356591249 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 106) 106 4 2
  rw [← rowsCellR4ZP106_eq_semantic]
  exact rowsCellR4ZP106_lower

noncomputable def rowsCellR4ZP107Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP107_value_bridge : rowsCellR4ZP107Expr30 = rowsCellR4ZP107Raw30.value := by
  unfold rowsCellR4ZP107Expr30 rowsCellR4ZP107Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP107_coefficient :
    ((dualQ130fR4 107).coefficient : ℝ) =
      (coefficientQ130f 4 107 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP107R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 107 := OmegaBound.ADVXXZT6Round61.coefficientP107R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 107).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP107_lower : (0 : ℝ) ≤ rowsCellR4ZP107Expr30 := by
  unfold rowsCellR4ZP107Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP107_eq_semantic : rowsCellR4ZP107Expr30 =
    semanticQuantity130f (dualQ130fR4 107) 107 4 2 := by
  calc
    rowsCellR4ZP107Expr30 = rowsCellR4ZP107Raw30.value := rowsCellR4ZP107_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 107) 107 4 2).value := by
      rw [rowsCellR4ZP107_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP107_coefficient

theorem rowsCellR4ZP107 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 107) 107 4
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 107) 107 4 2
  rw [← rowsCellR4ZP107_eq_semantic]
  exact rowsCellR4ZP107_lower

noncomputable def rowsCellR4ZP108Expr30 : ℝ :=
  ((24088466488731462292702814670595 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((305636671402555404518867964004898615061561956336619 : ℝ) / 12259964326927110866866776217202473468949912977468817408)
    + ((24088466488731462292702814670595 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((6060505650258449 : ℝ) / 18446744073709551616)
    + ((24088466488731462292702814670595 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((1515302375468597 : ℝ) / 4611686018427387904)
    + ((-374992433129751913041002183981193662505376229490545 : ℝ) / 287342913912354160942190067590682971928513585409425408) * Real.negMulLog ((5719947159738567 : ℝ) / 9223372036854775808)
    + ((24088466488731462292702814670595 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((22400938871623661 : ℝ) / 1152921504606846976)
    + ((24088466488731462292702814670595 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((44801882705618227 : ℝ) / 2305843009213693952)
    + ((24088466488731462292702814670595 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((124507639453137541341950261400329507559542048448085013 : ℝ) / 6129982163463555433433388108601236734474956488734408704)
    + ((24088466488731462292702814670595 : ℝ) / 15576890575604482885591488987660288) * Real.negMulLog ((124507664587926370268924566177981138793815285697641493 : ℝ) / 6129982163463555433433388108601236734474956488734408704)
    + ((-374992433129751913041002183981193662505376229490545 : ℝ) / 287342913912354160942190067590682971928513585409425408) * Real.negMulLog ((3432417385883687 : ℝ) / 72057594037927936)
    + ((-2158417180836819386756942892655321038161878831655 : ℝ) / 4489733029880533764721719806104421436383024772022272) * Real.negMulLog ((1 : ℝ) / 2)
    + ((24088466488731462292702814670595 : ℝ) / 31153781151208965771182977975320576) * Real.negMulLog ((2337240767962219032230071205112652669482841125742937067 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((-374992433129751913041002183981193662505376229490545 : ℝ) / 574685827824708321884380135181365943857027170818850816) * Real.negMulLog ((32596379633080281 : ℝ) / 36028797018963968)
    + ((-374992433129751913041002183981193662505376229490545 : ℝ) / 574685827824708321884380135181365943857027170818850816) * Real.negMulLog ((4605966071267649337 : ℝ) / 4611686018427387904)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP108_value_bridge : rowsCellR4ZP108Expr30 = rowsCellR4ZP108Raw30.value := by
  unfold rowsCellR4ZP108Expr30 rowsCellR4ZP108Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP108_coefficient :
    ((dualQ130fR4 108).coefficient : ℝ) =
      (coefficientQ130f 4 108 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP108R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 108 := OmegaBound.ADVXXZT6Round61.coefficientP108R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 108).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP108_lower : ((115351902159152414497 : ℝ) / 250000000000000000000000) ≤ rowsCellR4ZP108Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19137_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08793_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom05213_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom08362_upper
    (show ((-374992433129751913041002183981193662505376229490545 : ℝ) / 287342913912354160942190067590682971928513585409425408) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11454_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12274_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19637_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 15576890575604482885591488987660288) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19638_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 15576890575604482885591488987660288) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom06829_upper
    (show ((-374992433129751913041002183981193662505376229490545 : ℝ) / 287342913912354160942190067590682971928513585409425408) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-2158417180836819386756942892655321038161878831655 : ℝ) / 4489733029880533764721719806104421436383024772022272) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19817_lower
    (show 0 ≤ ((24088466488731462292702814670595 : ℝ) / 31153781151208965771182977975320576) by norm_num)
  have h11 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11774_upper
    (show ((-374992433129751913041002183981193662505376229490545 : ℝ) / 574685827824708321884380135181365943857027170818850816) ≤ 0 by norm_num)
  have h12 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom15143_upper
    (show ((-374992433129751913041002183981193662505376229490545 : ℝ) / 574685827824708321884380135181365943857027170818850816) ≤ 0 by norm_num)
  unfold rowsCellR4ZP108Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP108_eq_semantic : rowsCellR4ZP108Expr30 =
    semanticQuantity130f (dualQ130fR4 108) 108 4 2 := by
  calc
    rowsCellR4ZP108Expr30 = rowsCellR4ZP108Raw30.value := rowsCellR4ZP108_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 108) 108 4 2).value := by
      rw [rowsCellR4ZP108_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP108_coefficient

theorem rowsCellR4ZP108 : ((115351902159152414497 : ℝ) / 250000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 108) 108 4
      (roleIndex30 .Z) := by
  change ((115351902159152414497 : ℝ) / 250000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 108) 108 4 2
  rw [← rowsCellR4ZP108_eq_semantic]
  exact rowsCellR4ZP108_lower

noncomputable def rowsCellR4ZP109Expr30 : ℝ :=
  ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((8155616038133403 : ℝ) / 2305843009213693952)
    + ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((8155696504238611 : ℝ) / 2305843009213693952)
    + ((10858873087314493610555986891707 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((12200079772038357393347922681007 : ℝ) / 2596148429267413814265248164610048)
    + ((10858873087314493610555986891707 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((24400163704955638227141173160143 : ℝ) / 5192296858534827628530496329220096)
    + ((-137137724826755399997566136553631719831229372769 : ℝ) / 374144419156711147060143317175368453031918731001856) * Real.negMulLog ((3864119208996671 : ℝ) / 72057594037927936)
    + ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((615454489935916142464655667779377 : ℝ) / 2596148429267413814265248164610048)
    + ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((307727248088410418327398518039377 : ℝ) / 1298074214633706907132624082305024)
    + ((-10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-137137724826755399997566136553631719831229372769 : ℝ) / 748288838313422294120286634350736906063837462003712) * Real.negMulLog ((32164677809967297 : ℝ) / 36028797018963968)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP109_value_bridge : rowsCellR4ZP109Expr30 = rowsCellR4ZP109Raw30.value := by
  unfold rowsCellR4ZP109Expr30 rowsCellR4ZP109Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP109_coefficient :
    ((dualQ130fR4 109).coefficient : ℝ) =
      (coefficientQ130f 4 109 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP109R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 109 := OmegaBound.ADVXXZT6Round61.coefficientP109R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 109).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP109_lower : ((422283851582002546497 : ℝ) / 1000000000000000000000000) ≤ rowsCellR4ZP109Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10436_lower
    (show 0 ≤ ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10438_lower
    (show 0 ≤ ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16004_lower
    (show 0 ≤ ((10858873087314493610555986891707 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16156_lower
    (show 0 ≤ ((10858873087314493610555986891707 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07114_upper
    (show ((-137137724826755399997566136553631719831229372769 : ℝ) / 374144419156711147060143317175368453031918731001856) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16975_lower
    (show 0 ≤ ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16717_lower
    (show 0 ≤ ((10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-10858873087314493610555986891707 : ℝ) / 10384593717069655257060992658440192) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11721_upper
    (show ((-137137724826755399997566136553631719831229372769 : ℝ) / 748288838313422294120286634350736906063837462003712) ≤ 0 by norm_num)
  unfold rowsCellR4ZP109Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP109_eq_semantic : rowsCellR4ZP109Expr30 =
    semanticQuantity130f (dualQ130fR4 109) 109 4 2 := by
  calc
    rowsCellR4ZP109Expr30 = rowsCellR4ZP109Raw30.value := rowsCellR4ZP109_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 109) 109 4 2).value := by
      rw [rowsCellR4ZP109_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP109_coefficient

theorem rowsCellR4ZP109 : ((422283851582002546497 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 109) 109 4
      (roleIndex30 .Z) := by
  change ((422283851582002546497 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 109) 109 4 2
  rw [← rowsCellR4ZP109_eq_semantic]
  exact rowsCellR4ZP109_lower

noncomputable def rowsCellR4ZP110Expr30 : ℝ :=
  ((9188529310595151518326141233161 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((10937836348419545456783409295253 : ℝ) / 5192296858534827628530496329220096)
    + ((9188529310595151518326141233161 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((21929868931732178655796327816417 : ℝ) / 10384593717069655257060992658440192)
    + ((-155436457310517289960609078885298589164724176977 : ℝ) / 17958932119522135058886879224417685745532099088089088) * Real.negMulLog ((2589537295079539 : ℝ) / 144115188075855872)
    + ((9188529310595151518326141233161 : ℝ) / 498460498419343452338927647605129216) * Real.negMulLog ((293423167737254044074122838003819 : ℝ) / 2596148429267413814265248164610048)
    + ((9188529310595151518326141233161 : ℝ) / 498460498419343452338927647605129216) * Real.negMulLog ((588300227306054819511884681634591 : ℝ) / 5192296858534827628530496329220096)
    + ((9188529310595151518326141233161 : ℝ) / 124615124604835863084731911901282304) * Real.negMulLog ((55141235385049079 : ℝ) / 288230376151711744)
    + ((-506666857557949988141796594377852797287567308719 : ℝ) / 8979466059761067529443439612208842872766049544044544) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-155436457310517289960609078885298589164724176977 : ℝ) / 35917864239044270117773758448835371491064198176178176) * Real.negMulLog ((69468056742848397 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP110_value_bridge : rowsCellR4ZP110Expr30 = rowsCellR4ZP110Raw30.value := by
  unfold rowsCellR4ZP110Expr30 rowsCellR4ZP110Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP110_coefficient :
    ((dualQ130fR4 110).coefficient : ℝ) =
      (coefficientQ130f 4 110 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP110R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 110 := OmegaBound.ADVXXZT6Round61.coefficientP110R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 110).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP110_lower : ((2609086831674319163 : ℝ) / 200000000000000000000000) ≤ rowsCellR4ZP110Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15986_lower
    (show 0 ≤ ((9188529310595151518326141233161 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16132_lower
    (show 0 ≤ ((9188529310595151518326141233161 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom05952_upper
    (show ((-155436457310517289960609078885298589164724176977 : ℝ) / 17958932119522135058886879224417685745532099088089088) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16678_lower
    (show 0 ≤ ((9188529310595151518326141233161 : ℝ) / 498460498419343452338927647605129216) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16922_lower
    (show 0 ≤ ((9188529310595151518326141233161 : ℝ) / 498460498419343452338927647605129216) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12388_lower
    (show 0 ≤ ((9188529310595151518326141233161 : ℝ) / 124615124604835863084731911901282304) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-506666857557949988141796594377852797287567308719 : ℝ) / 8979466059761067529443439612208842872766049544044544) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom13092_upper
    (show ((-155436457310517289960609078885298589164724176977 : ℝ) / 35917864239044270117773758448835371491064198176178176) ≤ 0 by norm_num)
  unfold rowsCellR4ZP110Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP110_eq_semantic : rowsCellR4ZP110Expr30 =
    semanticQuantity130f (dualQ130fR4 110) 110 4 2 := by
  calc
    rowsCellR4ZP110Expr30 = rowsCellR4ZP110Raw30.value := rowsCellR4ZP110_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 110) 110 4 2).value := by
      rw [rowsCellR4ZP110_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP110_coefficient

theorem rowsCellR4ZP110 : ((2609086831674319163 : ℝ) / 200000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 110) 110 4
      (roleIndex30 .Z) := by
  change ((2609086831674319163 : ℝ) / 200000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 110) 110 4 2
  rw [← rowsCellR4ZP110_eq_semantic]
  exact rowsCellR4ZP110_lower

noncomputable def rowsCellR4ZP111Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP111_value_bridge : rowsCellR4ZP111Expr30 = rowsCellR4ZP111Raw30.value := by
  unfold rowsCellR4ZP111Expr30 rowsCellR4ZP111Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP111_coefficient :
    ((dualQ130fR4 111).coefficient : ℝ) =
      (coefficientQ130f 4 111 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP111R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 111 := OmegaBound.ADVXXZT6Round61.coefficientP111R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 111).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP111_lower : (0 : ℝ) ≤ rowsCellR4ZP111Expr30 := by
  unfold rowsCellR4ZP111Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP111_eq_semantic : rowsCellR4ZP111Expr30 =
    semanticQuantity130f (dualQ130fR4 111) 111 4 2 := by
  calc
    rowsCellR4ZP111Expr30 = rowsCellR4ZP111Raw30.value := rowsCellR4ZP111_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 111) 111 4 2).value := by
      rw [rowsCellR4ZP111_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP111_coefficient

theorem rowsCellR4ZP111 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 111) 111 4
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 111) 111 4 2
  rw [← rowsCellR4ZP111_eq_semantic]
  exact rowsCellR4ZP111_lower

noncomputable def rowsCellR4ZP112Expr30 : ℝ :=
  ((-38121941485248753282052177152152514170159627455 : ℝ) / 5986310706507378352962293074805895248510699696029696) * Real.negMulLog ((1409966802922307 : ℝ) / 295147905179352825856)
    + ((36883292339045764757786623992695 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((32142057411992121799566806416014720587 : ℝ) / 5444517870735015415413993718908291383296)
    + ((36883292339045764757786623992695 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((32142075542994247064703343566200028089 : ℝ) / 5444517870735015415413993718908291383296)
    + ((-380073215570512258346494743581842549808072488925 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((5949304186710397 : ℝ) / 144115188075855872)
    + ((36883292339045764757786623992695 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((2908427440575313845 : ℝ) / 18446744073709551616)
    + ((36883292339045764757786623992695 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((470571042583479855209686366902922494389 : ℝ) / 2722258935367507707706996859454145691648)
    + ((36883292339045764757786623992695 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((470571226925140370965918787579346895943 : ℝ) / 2722258935367507707706996859454145691648)
    + ((-35757459845880651456389011146361404629868870787425 : ℝ) / 2993155353253689176481146537402947624255349848014848) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-380073215570512258346494743581842549808072488925 : ℝ) / 280608314367533360295107487881526339773939048251392) * Real.negMulLog ((66108289851217539 : ℝ) / 72057594037927936)
    + ((-38121941485248753282052177152152514170159627455 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((147572542622873490621 : ℝ) / 147573952589676412928)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP112_value_bridge : rowsCellR4ZP112Expr30 = rowsCellR4ZP112Raw30.value := by
  unfold rowsCellR4ZP112Expr30 rowsCellR4ZP112Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP112_coefficient :
    ((dualQ130fR4 112).coefficient : ℝ) =
      (coefficientQ130f 4 112 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP112R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 112 := OmegaBound.ADVXXZT6Round61.coefficientP112R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 112).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP112_lower : ((4360926453589619878463 : ℝ) / 1000000000000000000000000) ≤ rowsCellR4ZP112Expr30 := by
  have h0 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom05105_upper
    (show ((-38121941485248753282052177152152514170159627455 : ℝ) / 5986310706507378352962293074805895248510699696029696) ≤ 0 by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18452_lower
    (show 0 ≤ ((36883292339045764757786623992695 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18453_lower
    (show 0 ≤ ((36883292339045764757786623992695 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom08591_upper
    (show ((-380073215570512258346494743581842549808072488925 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15003_lower
    (show 0 ≤ ((36883292339045764757786623992695 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18567_lower
    (show 0 ≤ ((36883292339045764757786623992695 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18568_lower
    (show 0 ≤ ((36883292339045764757786623992695 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-35757459845880651456389011146361404629868870787425 : ℝ) / 2993155353253689176481146537402947624255349848014848) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12864_upper
    (show ((-380073215570512258346494743581842549808072488925 : ℝ) / 280608314367533360295107487881526339773939048251392) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom15644_upper
    (show ((-38121941485248753282052177152152514170159627455 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  unfold rowsCellR4ZP112Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP112_eq_semantic : rowsCellR4ZP112Expr30 =
    semanticQuantity130f (dualQ130fR4 112) 112 4 2 := by
  calc
    rowsCellR4ZP112Expr30 = rowsCellR4ZP112Raw30.value := rowsCellR4ZP112_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 112) 112 4 2).value := by
      rw [rowsCellR4ZP112_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP112_coefficient

theorem rowsCellR4ZP112 : ((4360926453589619878463 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 112) 112 4
      (roleIndex30 .Z) := by
  change ((4360926453589619878463 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 112) 112 4 2
  rw [← rowsCellR4ZP112_eq_semantic]
  exact rowsCellR4ZP112_lower

noncomputable def rowsCellR4ZP113Expr30 : ℝ :=
  ((451049008209351202327560159115 : ℝ) / 20282409603651670423947251286016) * Real.negMulLog ((815782427636663762997806273209137 : ℝ) / 166153499473114484112975882535043072)
    + ((451049008209351202327560159115 : ℝ) / 20282409603651670423947251286016) * Real.negMulLog ((203945619132523545210609731634111 : ℝ) / 41538374868278621028243970633760768)
    + ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((62998914115848357 : ℝ) / 9223372036854775808)
    + ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((62999446690747245 : ℝ) / 9223372036854775808)
    + ((-5825385486389468665306266078307384049379154085 : ℝ) / 23384026197294446691258957323460528314494920687616) * Real.negMulLog ((7757953605980547 : ℝ) / 144115188075855872)
    + ((-41003452455374811417447044017373536834038465 : ℝ) / 11417981541647679048466287755595961091061972992) * Real.negMulLog ((1028166240800297 : ℝ) / 18014398509481984)
    + ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((19385955100291931795018571224112335 : ℝ) / 83076749736557242056487941267521536)
    + ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((4846490630566044191850068103396417 : ℝ) / 20769187434139310514121985316880384)
    + ((-451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-41003452455374811417447044017373536834038465 : ℝ) / 22835963083295358096932575511191922182123945984) * Real.negMulLog ((7979033013940695 : ℝ) / 9007199254740992)
    + ((-5825385486389468665306266078307384049379154085 : ℝ) / 46768052394588893382517914646921056628989841375232) * Real.negMulLog ((64299640431947389 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP113_value_bridge : rowsCellR4ZP113Expr30 = rowsCellR4ZP113Raw30.value := by
  unfold rowsCellR4ZP113Expr30 rowsCellR4ZP113Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP113_coefficient :
    ((dualQ130fR4 113).coefficient : ℝ) =
      (coefficientQ130f 4 113 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP113R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 113 := OmegaBound.ADVXXZT6Round61.coefficientP113R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 113).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP113_lower : ((239242731596380085839 : ℝ) / 50000000000000000000000) ≤ rowsCellR4ZP113Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17065_lower
    (show 0 ≤ ((451049008209351202327560159115 : ℝ) / 20282409603651670423947251286016) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16618_lower
    (show 0 ≤ ((451049008209351202327560159115 : ℝ) / 20282409603651670423947251286016) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12582_lower
    (show 0 ≤ ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12583_lower
    (show 0 ≤ ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10185_upper
    (show ((-5825385486389468665306266078307384049379154085 : ℝ) / 23384026197294446691258957323460528314494920687616) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom04828_upper
    (show ((-41003452455374811417447044017373536834038465 : ℝ) / 11417981541647679048466287755595961091061972992) ≤ 0 by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17884_lower
    (show 0 ≤ ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17504_lower
    (show 0 ≤ ((451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-451049008209351202327560159115 : ℝ) / 40564819207303340847894502572032) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10293_upper
    (show ((-41003452455374811417447044017373536834038465 : ℝ) / 22835963083295358096932575511191922182123945984) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12669_upper
    (show ((-5825385486389468665306266078307384049379154085 : ℝ) / 46768052394588893382517914646921056628989841375232) ≤ 0 by norm_num)
  unfold rowsCellR4ZP113Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP113_eq_semantic : rowsCellR4ZP113Expr30 =
    semanticQuantity130f (dualQ130fR4 113) 113 4 2 := by
  calc
    rowsCellR4ZP113Expr30 = rowsCellR4ZP113Raw30.value := rowsCellR4ZP113_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 113) 113 4 2).value := by
      rw [rowsCellR4ZP113_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP113_coefficient

theorem rowsCellR4ZP113 : ((239242731596380085839 : ℝ) / 50000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 113) 113 4
      (roleIndex30 .Z) := by
  change ((239242731596380085839 : ℝ) / 50000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 113) 113 4 2
  rw [← rowsCellR4ZP113_eq_semantic]
  exact rowsCellR4ZP113_lower

noncomputable def rowsCellR4ZP114Expr30 : ℝ :=
  ((13500501710698607214145569147745 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((6154320634957395 : ℝ) / 18446744073709551616)
    + ((13500501710698607214145569147745 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((6155532465489993 : ℝ) / 18446744073709551616)
    + ((13500501710698607214145569147745 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((4983501806441366815506786829013689096041987952610641 : ℝ) / 6129982163463555433433388108601236734474956488734408704)
    + ((-34570095248041826146975390885744606812588374723545 : ℝ) / 8979466059761067529443439612208842872766049544044544) * Real.negMulLog ((4734975335045189 : ℝ) / 1152921504606846976)
    + ((13500501710698607214145569147745 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((48714579630270085470247599215387838526581453833892527 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((13500501710698607214145569147745 : ℝ) / 3894222643901120721397872246915072) * Real.negMulLog ((48714579635133531740085087227528597099137658119778991 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((13500501710698607214145569147745 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((5587422059203905 : ℝ) / 288230376151711744)
    + ((13500501710698607214145569147745 : ℝ) / 1947111321950560360698936123457536) * Real.negMulLog ((11174858565119225 : ℝ) / 576460752303423488)
    + ((-140570328568201012708352509349016249388955837215 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((3799045958373465 : ℝ) / 72057594037927936)
    + ((-140570328568201012708352509349016249388955837215 : ℝ) / 140304157183766680147553743940763169886969524125696) * Real.negMulLog ((1900221766077121 : ℝ) / 36028797018963968)
    + ((-301732199312561988377450422787025659935616786075 : ℝ) / 280608314367533360295107487881526339773939048251392) * Real.negMulLog ((1 : ℝ) / 2)
    + ((13500501710698607214145569147745 : ℝ) / 7788445287802241442795744493830144) * Real.negMulLog ((1191397413173417050223531852202942730109411476259474769 : ℝ) / 1532495540865888858358347027150309183618739122183602176)
    + ((-140570328568201012708352509349016249388955837215 : ℝ) / 280608314367533360295107487881526339773939048251392) * Real.negMulLog ((16114176743404863 : ℝ) / 18014398509481984)
    + ((-140570328568201012708352509349016249388955837215 : ℝ) / 280608314367533360295107487881526339773939048251392) * Real.negMulLog ((32229751060590503 : ℝ) / 36028797018963968)
    + ((-34570095248041826146975390885744606812588374723545 : ℝ) / 17958932119522135058886879224417685745532099088089088) * Real.negMulLog ((571725776968378299 : ℝ) / 576460752303423488)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP114_value_bridge : rowsCellR4ZP114Expr30 = rowsCellR4ZP114Raw30.value := by
  unfold rowsCellR4ZP114Expr30 rowsCellR4ZP114Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP114_coefficient :
    ((dualQ130fR4 114).coefficient : ℝ) =
      (coefficientQ130f 4 114 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP114R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 114 := OmegaBound.ADVXXZT6Round61.coefficientP114R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 114).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP114_lower : ((509502786322440050921 : ℝ) / 500000000000000000000000) ≤ rowsCellR4ZP114Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom09032_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom09037_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19290_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07676_upper
    (show ((-34570095248041826146975390885744606812588374723545 : ℝ) / 8979466059761067529443439612208842872766049544044544) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19536_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19537_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 3894222643901120721397872246915072) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08192_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom11047_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 1947111321950560360698936123457536) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07053_upper
    (show ((-140570328568201012708352509349016249388955837215 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom05518_upper
    (show ((-140570328568201012708352509349016249388955837215 : ℝ) / 140304157183766680147553743940763169886969524125696) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-301732199312561988377450422787025659935616786075 : ℝ) / 280608314367533360295107487881526339773939048251392) ≤ 0 by norm_num)
  have h11 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19804_lower
    (show 0 ≤ ((13500501710698607214145569147745 : ℝ) / 7788445287802241442795744493830144) by norm_num)
  have h12 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11200_upper
    (show ((-140570328568201012708352509349016249388955837215 : ℝ) / 280608314367533360295107487881526339773939048251392) ≤ 0 by norm_num)
  have h13 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11734_upper
    (show ((-140570328568201012708352509349016249388955837215 : ℝ) / 280608314367533360295107487881526339773939048251392) ≤ 0 by norm_num)
  have h14 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom14379_upper
    (show ((-34570095248041826146975390885744606812588374723545 : ℝ) / 17958932119522135058886879224417685745532099088089088) ≤ 0 by norm_num)
  unfold rowsCellR4ZP114Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP114_eq_semantic : rowsCellR4ZP114Expr30 =
    semanticQuantity130f (dualQ130fR4 114) 114 4 2 := by
  calc
    rowsCellR4ZP114Expr30 = rowsCellR4ZP114Raw30.value := rowsCellR4ZP114_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 114) 114 4 2).value := by
      rw [rowsCellR4ZP114_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP114_coefficient

theorem rowsCellR4ZP114 : ((509502786322440050921 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 114) 114 4
      (roleIndex30 .Z) := by
  change ((509502786322440050921 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 114) 114 4 2
  rw [← rowsCellR4ZP114_eq_semantic]
  exact rowsCellR4ZP114_lower

noncomputable def rowsCellR4ZP115Expr30 : ℝ :=
  ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((4077294914317001 : ℝ) / 1152921504606846976)
    + ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((8154632300476449 : ℝ) / 2305843009213693952)
    + ((12389667249259182395000421430029 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((12213835585152269559856002853055 : ℝ) / 2596148429267413814265248164610048)
    + ((12389667249259182395000421430029 : ℝ) / 5192296858534827628530496329220096) * Real.negMulLog ((48855362062334401613874613943299 : ℝ) / 10384593717069655257060992658440192)
    + ((-156884456614741183772385338311579810225030324023 : ℝ) / 374144419156711147060143317175368453031918731001856) * Real.negMulLog ((7716526801734437 : ℝ) / 144115188075855872)
    + ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((307714040588777119014980727772993 : ℝ) / 1298074214633706907132624082305024)
    + ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((1230856459157679621088352286835709 : ℝ) / 5192296858534827628530496329220096)
    + ((-12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-156884456614741183772385338311579810225030324023 : ℝ) / 748288838313422294120286634350736906063837462003712) * Real.negMulLog ((64341067236193499 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP115_value_bridge : rowsCellR4ZP115Expr30 = rowsCellR4ZP115Raw30.value := by
  unfold rowsCellR4ZP115Expr30 rowsCellR4ZP115Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP115_coefficient :
    ((dualQ130fR4 115).coefficient : ℝ) =
      (coefficientQ130f 4 115 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP115R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 115 := OmegaBound.ADVXXZT6Round61.coefficientP115R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 115).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP115_lower : ((240887322102834540559 : ℝ) / 500000000000000000000000) ≤ rowsCellR4ZP115Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom07225_lower
    (show 0 ≤ ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10422_lower
    (show 0 ≤ ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16011_lower
    (show 0 ≤ ((12389667249259182395000421430029 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16335_lower
    (show 0 ≤ ((12389667249259182395000421430029 : ℝ) / 5192296858534827628530496329220096) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10167_upper
    (show ((-156884456614741183772385338311579810225030324023 : ℝ) / 374144419156711147060143317175368453031918731001856) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16713_lower
    (show 0 ≤ ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17189_lower
    (show 0 ≤ ((12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-12389667249259182395000421430029 : ℝ) / 10384593717069655257060992658440192) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12683_upper
    (show ((-156884456614741183772385338311579810225030324023 : ℝ) / 748288838313422294120286634350736906063837462003712) ≤ 0 by norm_num)
  unfold rowsCellR4ZP115Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP115_eq_semantic : rowsCellR4ZP115Expr30 =
    semanticQuantity130f (dualQ130fR4 115) 115 4 2 := by
  calc
    rowsCellR4ZP115Expr30 = rowsCellR4ZP115Raw30.value := rowsCellR4ZP115_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 115) 115 4 2).value := by
      rw [rowsCellR4ZP115_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP115_coefficient

theorem rowsCellR4ZP115 : ((240887322102834540559 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 115) 115 4
      (roleIndex30 .Z) := by
  change ((240887322102834540559 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 115) 115 4 2
  rw [← rowsCellR4ZP115_eq_semantic]
  exact rowsCellR4ZP115_lower

noncomputable def rowsCellR4ZP116Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP116_value_bridge : rowsCellR4ZP116Expr30 = rowsCellR4ZP116Raw30.value := by
  unfold rowsCellR4ZP116Expr30 rowsCellR4ZP116Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP116_coefficient :
    ((dualQ130fR4 116).coefficient : ℝ) =
      (coefficientQ130f 4 116 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP116R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 116 := OmegaBound.ADVXXZT6Round61.coefficientP116R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 116).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP116_lower : (0 : ℝ) ≤ rowsCellR4ZP116Expr30 := by
  unfold rowsCellR4ZP116Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP116_eq_semantic : rowsCellR4ZP116Expr30 =
    semanticQuantity130f (dualQ130fR4 116) 116 4 2 := by
  calc
    rowsCellR4ZP116Expr30 = rowsCellR4ZP116Raw30.value := rowsCellR4ZP116_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 116) 116 4 2).value := by
      rw [rowsCellR4ZP116_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP116_coefficient

theorem rowsCellR4ZP116 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 116) 116 4
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 116) 116 4 2
  rw [← rowsCellR4ZP116_eq_semantic]
  exact rowsCellR4ZP116_lower

noncomputable def rowsCellR4ZP117Expr30 : ℝ :=
  ((511299297018308841474856419583 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((324520770586701925499021929454033 : ℝ) / 83076749736557242056487941267521536)
    + ((511299297018308841474856419583 : ℝ) / 40564819207303340847894502572032) * Real.negMulLog ((324520823369161802207717976167841 : ℝ) / 83076749736557242056487941267521536)
    + ((-6022430205529467298783543733487684008233755601 : ℝ) / 1461501637330902918203684832716283019655932542976) * Real.negMulLog ((2620808964734345 : ℝ) / 144115188075855872)
    + ((-3206383403951040808671488744145803021907187325 : ℝ) / 11692013098647223345629478661730264157247460343808) * Real.negMulLog ((3934679395556385 : ℝ) / 144115188075855872)
    + ((-1686427281080479234809552970279949040046583909 : ℝ) / 5846006549323611672814739330865132078623730171904) * Real.negMulLog ((8017556515814877 : ℝ) / 144115188075855872)
    + ((511299297018308841474856419583 : ℝ) / 20282409603651670423947251286016) * Real.negMulLog ((181133261155312847 : ℝ) / 1152921504606846976)
    + ((511299297018308841474856419583 : ℝ) / 81129638414606681695789005144064) * Real.negMulLog ((7392639613340840251368634704225839 : ℝ) / 41538374868278621028243970633760768)
    + ((511299297018308841474856419583 : ℝ) / 81129638414606681695789005144064) * Real.negMulLog ((7392639662790887431808376581925471 : ℝ) / 41538374868278621028243970633760768)
    + ((-92613309095345206650484950080584679604662282801 : ℝ) / 5846006549323611672814739330865132078623730171904) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-1686427281080479234809552970279949040046583909 : ℝ) / 11692013098647223345629478661730264157247460343808) * Real.negMulLog ((64040037522113059 : ℝ) / 72057594037927936)
    + ((-3206383403951040808671488744145803021907187325 : ℝ) / 23384026197294446691258957323460528314494920687616) * Real.negMulLog ((68122914642371551 : ℝ) / 72057594037927936)
    + ((-6022430205529467298783543733487684008233755601 : ℝ) / 2923003274661805836407369665432566039311865085952) * Real.negMulLog ((69436785073193591 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP117_value_bridge : rowsCellR4ZP117Expr30 = rowsCellR4ZP117Raw30.value := by
  unfold rowsCellR4ZP117Expr30 rowsCellR4ZP117Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP117_coefficient :
    ((dualQ130fR4 117).coefficient : ℝ) =
      (coefficientQ130f 4 117 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP117R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 117 := OmegaBound.ADVXXZT6Round61.coefficientP117R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 117).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP117_lower : ((2894196155805014439753 : ℝ) / 500000000000000000000000) ≤ rowsCellR4ZP117Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16763_lower
    (show 0 ≤ ((511299297018308841474856419583 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16764_lower
    (show 0 ≤ ((511299297018308841474856419583 : ℝ) / 40564819207303340847894502572032) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom06005_upper
    (show ((-6022430205529467298783543733487684008233755601 : ℝ) / 1461501637330902918203684832716283019655932542976) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom07150_upper
    (show ((-3206383403951040808671488744145803021907187325 : ℝ) / 11692013098647223345629478661730264157247460343808) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10324_upper
    (show ((-1686427281080479234809552970279949040046583909 : ℝ) / 5846006549323611672814739330865132078623730171904) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom13737_lower
    (show 0 ≤ ((511299297018308841474856419583 : ℝ) / 20282409603651670423947251286016) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17669_lower
    (show 0 ≤ ((511299297018308841474856419583 : ℝ) / 81129638414606681695789005144064) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17670_lower
    (show 0 ≤ ((511299297018308841474856419583 : ℝ) / 81129638414606681695789005144064) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-92613309095345206650484950080584679604662282801 : ℝ) / 5846006549323611672814739330865132078623730171904) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12632_upper
    (show ((-1686427281080479234809552970279949040046583909 : ℝ) / 11692013098647223345629478661730264157247460343808) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12948_upper
    (show ((-3206383403951040808671488744145803021907187325 : ℝ) / 23384026197294446691258957323460528314494920687616) ≤ 0 by norm_num)
  have h11 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom13076_upper
    (show ((-6022430205529467298783543733487684008233755601 : ℝ) / 2923003274661805836407369665432566039311865085952) ≤ 0 by norm_num)
  unfold rowsCellR4ZP117Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11]

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP117_eq_semantic : rowsCellR4ZP117Expr30 =
    semanticQuantity130f (dualQ130fR4 117) 117 4 2 := by
  calc
    rowsCellR4ZP117Expr30 = rowsCellR4ZP117Raw30.value := rowsCellR4ZP117_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 117) 117 4 2).value := by
      rw [rowsCellR4ZP117_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP117_coefficient

theorem rowsCellR4ZP117 : ((2894196155805014439753 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 117) 117 4
      (roleIndex30 .Z) := by
  change ((2894196155805014439753 : ℝ) / 500000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR4 117) 117 4 2
  rw [← rowsCellR4ZP117_eq_semantic]
  exact rowsCellR4ZP117_lower

noncomputable def rowsCellR4ZP118Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP118_value_bridge : rowsCellR4ZP118Expr30 = rowsCellR4ZP118Raw30.value := by
  unfold rowsCellR4ZP118Expr30 rowsCellR4ZP118Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR4ZP118_coefficient :
    ((dualQ130fR4 118).coefficient : ℝ) =
      (coefficientQ130f 4 118 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP118R4 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 4 118 := OmegaBound.ADVXXZT6Round61.coefficientP118R4_eq_released.symm
    _ = _ := (coefficientQ130f_cast 4 118).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP118_lower : (0 : ℝ) ≤ rowsCellR4ZP118Expr30 := by
  unfold rowsCellR4ZP118Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR4ZP118_eq_semantic : rowsCellR4ZP118Expr30 =
    semanticQuantity130f (dualQ130fR4 118) 118 4 2 := by
  calc
    rowsCellR4ZP118Expr30 = rowsCellR4ZP118Raw30.value := rowsCellR4ZP118_value_bridge
    _ = (semanticRowQ130f (dualQ130fR4 118) 118 4 2).value := by
      rw [rowsCellR4ZP118_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR4ZP118_coefficient

theorem rowsCellR4ZP118 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 118) 118 4
      (roleIndex30 .Z) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR4 118) 118 4 2
  rw [← rowsCellR4ZP118_eq_semantic]
  exact rowsCellR4ZP118_lower


end OmegaBound.ADVXXZGeneral
