import OmegaBound.ADVXXZT6Round76LedgerTwin
import OmegaBound.ADVXXZT6DenominatorBase
import OmegaBound.ADVXXZT6Round26CountingSpine
import OmegaBound.ADVXXZT7Round20ExactSplit
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Combinatorics.Nullstellensatz
