-- Generated by `tools/iapply_cells.py` (aggregator mode) of the development repository (not part of this release).
import OmegaBound.ADVXXZGeneralRowsCellsR0X0
import OmegaBound.ADVXXZGeneralRowsCellsR0X1
import OmegaBound.ADVXXZGeneralRowsCellsR0X2
import OmegaBound.ADVXXZGeneralRowsCellsR0X3
import OmegaBound.ADVXXZGeneralRowsCellsR0X4

open scoped BigOperators
open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

def rowsR0XQ30Num (p : Fin 126) : ℕ :=
  match p.1 with
  | 0 => 12658605636715197529
  | 1 => 449563772378287282814
  | 2 => 801542285360216678326
  | 3 => 0
  | 4 => 68049430371389274956
  | 5 => 12741095062745875122
  | 6 => 517217405039433474554
  | 7 => 5268199910793381255431
  | 8 => 0
  | 9 => 1214187050963771858923
  | 10 => 310527943441784145117
  | 11 => 174824475068990233464
  | 12 => 4901230737127011900415
  | 13 => 4752116891430761057587
  | 14 => 4398290079221394888740
  | 15 => 0
  | 16 => 2569922956211913695176
  | 17 => 0
  | 18 => 119486434636748767197
  | 19 => 0
  | 20 => 13149505228576188847
  | 21 => 12780241610621636988
  | 22 => 410214869036134542128
  | 23 => 1066860911414325578051
  | 24 => 0
  | 25 => 0
  | 26 => 12659985434262707303
  | 27 => 477642770353603709629
  | 28 => 1569630399325901427869
  | 29 => 0
  | 30 => 151109847316458436632
  | 31 => 350816207158946673768
  | 32 => 632404641033275080491
  | 33 => 4506005831019014376082
  | 34 => 5104834998841299884318
  | 35 => 5130756532941778663015
  | 36 => 0
  | 37 => 2593415215166779847242
  | 38 => 0
  | 39 => 122239429934173745221
  | 40 => 0
  | 41 => 13147384543142474697
  | 42 => 12665405125510220378
  | 43 => 445080247821412029632
  | 44 => 825836391960285746369
  | 45 => 0
  | 46 => 117341294581169626177
  | 47 => 12806565145691472898
  | 48 => 519340579435308435567
  | 49 => 5355898329592895789944
  | 50 => 0
  | 51 => 1218745040901849538306
  | 52 => 270111205260156092344
  | 53 => 106472035238928845253
  | 54 => 4407424102166084284621
  | 55 => 4076928620032340749178
  | 56 => 4058470105375412072308
  | 57 => 0
  | 58 => 1689452086896007351772
  | 59 => 0
  | 60 => 53900481602837487402
  | 61 => 0
  | 62 => 12964850085803982327
  | 63 => 12782367490622600134
  | 64 => 411408827617251542676
  | 65 => 1056115632529899412984
  | 66 => 0
  | 67 => 117914509236388890550
  | 68 => 12808513661265262931
  | 69 => 483336247524360680593
  | 70 => 1612888615535556040273
  | 71 => 0
  | 72 => 1225299054710766361037
  | 73 => 270501509528082461204
  | 74 => 578269141050968161494
  | 75 => 3547275410466250939090
  | 76 => 3780925998070132888100
  | 77 => 4106028292552590160524
  | 78 => 0
  | 79 => 0
  | 80 => 0
  | 81 => 0
  | 82 => 0
  | 83 => 12720169558376795897
  | 84 => 12865649909142940363
  | 85 => 369680876143755319791
  | 86 => 1226280082401296123034
  | 87 => 0
  | 88 => 0
  | 89 => 12665275335695590900
  | 90 => 426732554141850211535
  | 91 => 0
  | 92 => 0
  | 93 => 178476382334657076276
  | 94 => 351280172551083599535
  | 95 => 820112788996321767840
  | 96 => 3483297636581639357673
  | 97 => 4757363748625174011613
  | 98 => 5188609441659585294999
  | 99 => 0
  | 100 => 1641004089379286123937
  | 101 => 0
  | 102 => 51967819885152636579
  | 103 => 0
  | 104 => 12963426874036752769
  | 105 => 12874675296474905941
  | 106 => 369603705182810869927
  | 107 => 1242709287436780423609
  | 108 => 0
  | 109 => 63228300492335845232
  | 110 => 12740231401539557104
  | 111 => 433110577841027167164
  | 112 => 0
  | 113 => 0
  | 114 => 1061528238241628323857
  | 115 => 313830828667135210432
  | 116 => 806065526263333511820
  | 117 => 3058958055256301906189
  | 118 => 4121975677977968646380
  | 119 => 4449522191515566975387
  | 120 => 0
  | 121 => 0
  | 122 => 0
  | 123 => 0
  | 124 => 0
  | 125 => 12712023117476094017
  | _ => 0

noncomputable def rowsR0XQ30 (p : Fin 126) : ℝ :=
  (rowsR0XQ30Num p : ℝ) / 1000000000000000000000000

theorem rowsR0XQ30_le_semantic (p : Fin 126) :
    rowsR0XQ30 p ≤ semanticQuantity130f (dualQ130fR0 p) p 0
      (roleIndex30 .X) := by
  fin_cases p
  · convert rowsCellR0XP000 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP001 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP002 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP003 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP004 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP005 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP006 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP007 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP008 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP009 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP010 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP011 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP012 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP013 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP014 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP015 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP016 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP017 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP018 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP019 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP020 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP021 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP022 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP023 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP024 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP025 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP026 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP027 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP028 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP029 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP030 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP031 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP032 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP033 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP034 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP035 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP036 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP037 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP038 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP039 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP040 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP041 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP042 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP043 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP044 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP045 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP046 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP047 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP048 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP049 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP050 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP051 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP052 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP053 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP054 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP055 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP056 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP057 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP058 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP059 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP060 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP061 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP062 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP063 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP064 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP065 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP066 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP067 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP068 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP069 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP070 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP071 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP072 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP073 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP074 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP075 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP076 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP077 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP078 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP079 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP080 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP081 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP082 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP083 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP084 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP085 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP086 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP087 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP088 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP089 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP090 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP091 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP092 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP093 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP094 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP095 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP096 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP097 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP098 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP099 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP100 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP101 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP102 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP103 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP104 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP105 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP106 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP107 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP108 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP109 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP110 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP111 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP112 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP113 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP114 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP115 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP116 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP117 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP118 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP119 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP120 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP121 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP122 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP123 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP124 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]
  · convert rowsCellR0XP125 using 1 <;> norm_num [rowsR0XQ30, rowsR0XQ30Num]

theorem rowsR0XQ30Num_sum :
    (∑ p : Fin 126, rowsR0XQ30Num p) = 122642098737366102723498 := by
  decide +kernel

theorem rowsR0XQ30_sum :
    (∑ p : Fin 126, rowsR0XQ30 p) = ((61321049368683051361749 : ℝ) / 500000000000000000000000) := by
  simp only [rowsR0XQ30]
  rw [← Finset.sum_div, ← Nat.cast_sum, rowsR0XQ30Num_sum]
  norm_num

theorem rowsR0XFlooredSum_le_paper30 :
    (∑ p : Fin 126, rowsR0XQ30 p) ≤
      Real.log 2 * paperRow30 0 .X / (releasedCertificate.D ^ 2 : ℝ) := by
  have hscaled :
      (releasedCertificate.D ^ 2 : ℝ) * (∑ p : Fin 126, rowsR0XQ30 p) ≤
        Real.log 2 * paperRow30 0 .X := by
    rw [paperRow_eq_sum30, Finset.mul_sum, Finset.mul_sum]
    exact Finset.sum_le_sum (fun p _ => by
      calc
        (releasedCertificate.D ^ 2 : ℝ) * rowsR0XQ30 p ≤
            (releasedCertificate.D ^ 2 : ℝ) * semanticQuantity130f
              (dualQ130fR0 p) p 0 (roleIndex30 .X) := by
          exact mul_le_mul_of_nonneg_left (rowsR0XQ30_le_semantic p) (by positivity)
        _ ≤ Real.log 2 * paperParent30 p 0 .X :=
          semantic_parent_bound (dualQ130fR0 p) p 0 .X)
  have hD : (0 : ℝ) < (releasedCertificate.D ^ 2 : ℝ) := by
    norm_num [releasedCertificate, OmegaBound.ADVXXZT2.certDen]
  apply (le_div_iff₀ hD).2
  simpa [mul_comm] using hscaled

theorem R2_le_rowsR0XFlooredSum30 :
    OmegaBound.ADVXXZCert.R2 ≤ (∑ p : Fin 126, rowsR0XQ30 p) := by
  rw [rowsR0XQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R2]

theorem rowsR0XFlooredSum_margin30 :
    (∑ p : Fin 126, rowsR0XQ30 p) - OmegaBound.ADVXXZCert.R2 =
      ((42897101749 : ℝ) / 500000000000000000000000) := by
  rw [rowsR0XQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R2]

theorem R2_le_rowsR0XPaper30 :
    OmegaBound.ADVXXZCert.R2 ≤
      Real.log 2 * paperRow30 0 .X / (releasedCertificate.D ^ 2 : ℝ) :=
  R2_le_rowsR0XFlooredSum30.trans rowsR0XFlooredSum_le_paper30

end OmegaBound.ADVXXZGeneral
