-- Generated by `tools/iapply_cells.py` (cells mode) of the development repository (not part of this release).
-- The release tooling rewrote its imports.
import OmegaBound.ReleaseCompactRowsR2Y7Check
import OmegaBound.ADVXXZGeneralRowsSemanticCore30
import OmegaBound.ReleaseCompactR61CohortR2P096P125Check
import OmegaBound.ADVXXZRetainedAtom039
import OmegaBound.ADVXXZRetainedAtom042
import OmegaBound.ADVXXZRetainedAtom046
import OmegaBound.ADVXXZRetainedAtom050
import OmegaBound.ADVXXZRetainedAtom051
import OmegaBound.ADVXXZRetainedAtom055
import OmegaBound.ADVXXZRetainedAtom063
import OmegaBound.ADVXXZRetainedAtom067
import OmegaBound.ADVXXZRetainedAtom077
import OmegaBound.ADVXXZRetainedAtom078
import OmegaBound.ADVXXZRetainedAtom085
import OmegaBound.ADVXXZRetainedAtom086
import OmegaBound.ADVXXZRetainedAtom095
import OmegaBound.ADVXXZRetainedAtom101
import OmegaBound.ADVXXZRetainedAtom104
import OmegaBound.ADVXXZRetainedAtom109
import OmegaBound.ADVXXZRetainedAtom118
import OmegaBound.ADVXXZRetainedAtom124
import OmegaBound.ADVXXZRetainedAtom127
import OmegaBound.ADVXXZRetainedAtom141
import OmegaBound.ADVXXZRetainedAtom156
import OmegaBound.ADVXXZRetainedAtom159
import OmegaBound.ADVXXZRetainedAtom161
import OmegaBound.ADVXXZRetainedAtom162
import OmegaBound.ADVXXZRetainedAtom170
import OmegaBound.ADVXXZRetainedAtom172
import OmegaBound.ADVXXZRetainedAtom181
import OmegaBound.ADVXXZRetainedAtom182
import OmegaBound.ADVXXZRetainedAtom183
import OmegaBound.ADVXXZRetainedAtom188
import OmegaBound.ADVXXZRetainedAtom192
import OmegaBound.ADVXXZRetainedAtom193
import OmegaBound.ADVXXZRetainedAtom195
import OmegaBound.ADVXXZRetainedAtom196
import OmegaBound.ADVXXZRetainedAtom198

set_option maxRecDepth 1000000
set_option linter.style.longLine false

open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

noncomputable def rowsCellR2YP119Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP119_value_bridge : rowsCellR2YP119Expr30 = rowsCellR2YP119Raw30.value := by
  unfold rowsCellR2YP119Expr30 rowsCellR2YP119Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP119_coefficient :
    ((dualQ130fR2 119).coefficient : ℝ) =
      (coefficientQ130f 2 119 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP119R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 119 := OmegaBound.ADVXXZT6Round61.coefficientP119R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 119).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP119_lower : (0 : ℝ) ≤ rowsCellR2YP119Expr30 := by
  unfold rowsCellR2YP119Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP119_eq_semantic : rowsCellR2YP119Expr30 =
    semanticQuantity130f (dualQ130fR2 119) 119 2 1 := by
  calc
    rowsCellR2YP119Expr30 = rowsCellR2YP119Raw30.value := rowsCellR2YP119_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 119) 119 2 1).value := by
      rw [rowsCellR2YP119_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP119_coefficient

theorem rowsCellR2YP119 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 119) 119 2
      (roleIndex30 .Y) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 119) 119 2 1
  rw [← rowsCellR2YP119_eq_semantic]
  exact rowsCellR2YP119_lower

noncomputable def rowsCellR2YP120Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP120_value_bridge : rowsCellR2YP120Expr30 = rowsCellR2YP120Raw30.value := by
  unfold rowsCellR2YP120Expr30 rowsCellR2YP120Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP120_coefficient :
    ((dualQ130fR2 120).coefficient : ℝ) =
      (coefficientQ130f 2 120 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP120R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 120 := OmegaBound.ADVXXZT6Round61.coefficientP120R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 120).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP120_lower : (0 : ℝ) ≤ rowsCellR2YP120Expr30 := by
  unfold rowsCellR2YP120Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP120_eq_semantic : rowsCellR2YP120Expr30 =
    semanticQuantity130f (dualQ130fR2 120) 120 2 1 := by
  calc
    rowsCellR2YP120Expr30 = rowsCellR2YP120Raw30.value := rowsCellR2YP120_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 120) 120 2 1).value := by
      rw [rowsCellR2YP120_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP120_coefficient

theorem rowsCellR2YP120 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 120) 120 2
      (roleIndex30 .Y) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 120) 120 2 1
  rw [← rowsCellR2YP120_eq_semantic]
  exact rowsCellR2YP120_lower

noncomputable def rowsCellR2YP121Expr30 : ℝ :=
  ((3917085499497813488272697945741 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((5884022238185237 : ℝ) / 18446744073709551616)
    + ((3917085499497813488272697945741 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((1471091752558459 : ℝ) / 4611686018427387904)
    + ((3917085499497813488272697945741 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((3655905279153116425600804872182067602276883751203367 : ℝ) / 6129982163463555433433388108601236734474956488734408704)
    + ((3917085499497813488272697945741 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((5171692790417689 : ℝ) / 288230376151711744)
    + ((3917085499497813488272697945741 : ℝ) / 10384593717069655257060992658440192) * Real.negMulLog ((10343389242086459 : ℝ) / 576460752303423488)
    + ((3917085499497813488272697945741 : ℝ) / 20769187434139310514121985316880384) * Real.negMulLog ((58372103847086654424546462434992916019759545238195673 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((3917085499497813488272697945741 : ℝ) / 20769187434139310514121985316880384) * Real.negMulLog ((58372103868033463505598905766213710677249682576018905 : ℝ) / 3064991081731777716716694054300618367237478244367204352)
    + ((-51278939933188102590349808477800474914469091312883 : ℝ) / 191561942608236107294793378393788647952342390272950272) * Real.negMulLog ((143837200302411931917797262856941787 : ℝ) / 7546502698242718995520471377163321344)
    + ((-41251395295539848199700651946872955820053305159 : ℝ) / 748288838313422294120286634350736906063837462003712) * Real.negMulLog ((827225503202989 : ℝ) / 18014398509481984)
    + ((-81031865690243576058852206026554879989310046217 : ℝ) / 1496577676626844588240573268701473812127674924007424) * Real.negMulLog ((1 : ℝ) / 2)
    + ((3917085499497813488272697945741 : ℝ) / 41538374868278621028243970633760768) * Real.negMulLog ((1191138226446212310860504340398499433010101621838279207 : ℝ) / 1532495540865888858358347027150309183618739122183602176)
    + ((-41251395295539848199700651946872955820053305159 : ℝ) / 1496577676626844588240573268701473812127674924007424) * Real.negMulLog ((8179973751538003 : ℝ) / 9007199254740992)
    + ((-51278939933188102590349808477800474914469091312883 : ℝ) / 383123885216472214589586756787577295904684780545900544) * Real.negMulLog ((3629414148818947565842438425724718885 : ℝ) / 3773251349121359497760235688581660672)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP121_value_bridge : rowsCellR2YP121Expr30 = rowsCellR2YP121Raw30.value := by
  unfold rowsCellR2YP121Expr30 rowsCellR2YP121Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP121_coefficient :
    ((dualQ130fR2 121).coefficient : ℝ) =
      (coefficientQ130f 2 121 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP121R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 121 := OmegaBound.ADVXXZT6Round61.coefficientP121R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 121).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP121_lower : ((49316850351339664139 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2YP121Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08529_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom05156_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19262_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom07835_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10997_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 10384593717069655257060992658440192) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19540_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 20769187434139310514121985316880384) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19541_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 20769187434139310514121985316880384) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom18146_upper
    (show ((-51278939933188102590349808477800474914469091312883 : ℝ) / 191561942608236107294793378393788647952342390272950272) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom04696_upper
    (show ((-41251395295539848199700651946872955820053305159 : ℝ) / 748288838313422294120286634350736906063837462003712) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-81031865690243576058852206026554879989310046217 : ℝ) / 1496577676626844588240573268701473812127674924007424) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19801_lower
    (show 0 ≤ ((3917085499497813488272697945741 : ℝ) / 41538374868278621028243970633760768) by norm_num)
  have h11 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom10465_upper
    (show ((-41251395295539848199700651946872955820053305159 : ℝ) / 1496577676626844588240573268701473812127674924007424) ≤ 0 by norm_num)
  have h12 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom18371_upper
    (show ((-51278939933188102590349808477800474914469091312883 : ℝ) / 383123885216472214589586756787577295904684780545900544) ≤ 0 by norm_num)
  unfold rowsCellR2YP121Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP121_eq_semantic : rowsCellR2YP121Expr30 =
    semanticQuantity130f (dualQ130fR2 121) 121 2 1 := by
  calc
    rowsCellR2YP121Expr30 = rowsCellR2YP121Raw30.value := rowsCellR2YP121_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 121) 121 2 1).value := by
      rw [rowsCellR2YP121_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP121_coefficient

theorem rowsCellR2YP121 : ((49316850351339664139 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 121) 121 2
      (roleIndex30 .Y) := by
  change ((49316850351339664139 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 121) 121 2 1
  rw [← rowsCellR2YP121_eq_semantic]
  exact rowsCellR2YP121_lower

noncomputable def rowsCellR2YP122Expr30 : ℝ :=
  ((1616040902977881441575823777471877 : ℝ) / 62307562302417931542365955950641152) * Real.negMulLog ((18976094894212990573714338531259855918086163526925 : ℝ) / 766247770432944429179173513575154591809369561091801088)
    + ((1616040902977881441575823777471877 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((6008415059074929 : ℝ) / 18446744073709551616)
    + ((1616040902977881441575823777471877 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((3004211596403693 : ℝ) / 9223372036854775808)
    + ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 766247770432944429179173513575154591809369561091801088) * Real.negMulLog ((364663865475999 : ℝ) / 576460752303423488)
    + ((1616040902977881441575823777471877 : ℝ) / 62307562302417931542365955950641152) * Real.negMulLog ((5087941545029965 : ℝ) / 288230376151711744)
    + ((1616040902977881441575823777471877 : ℝ) / 62307562302417931542365955950641152) * Real.negMulLog ((5087941973550851 : ℝ) / 288230376151711744)
    + ((1616040902977881441575823777471877 : ℝ) / 124615124604835863084731911901282304) * Real.negMulLog ((7584366560038243201746062910225847456190211573680883 : ℝ) / 383123885216472214589586756787577295904684780545900544)
    + ((1616040902977881441575823777471877 : ℝ) / 124615124604835863084731911901282304) * Real.negMulLog ((7584366564910515732497987850510378419400082311351027 : ℝ) / 383123885216472214589586756787577295904684780545900544)
    + ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 766247770432944429179173513575154591809369561091801088) * Real.negMulLog ((3287315587181415 : ℝ) / 72057594037927936)
    + ((-342596749790939235270698048162893261165820660659 : ℝ) / 93536104789177786765035829293842113257979682750464) * Real.negMulLog ((1 : ℝ) / 2)
    + ((1616040902977881441575823777471877 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((149197304895895724398849213683634477310269420407878925 : ℝ) / 191561942608236107294793378393788647952342390272950272)
    + ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 1532495540865888858358347027150309183618739122183602176) * Real.negMulLog ((32741481431782553 : ℝ) / 36028797018963968)
    + ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 1532495540865888858358347027150309183618739122183602176) * Real.negMulLog ((287865712286235745 : ℝ) / 288230376151711744)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP122_value_bridge : rowsCellR2YP122Expr30 = rowsCellR2YP122Raw30.value := by
  unfold rowsCellR2YP122Expr30 rowsCellR2YP122Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP122_coefficient :
    ((dualQ130fR2 122).coefficient : ℝ) =
      (coefficientQ130f 2 122 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP122R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 122 := OmegaBound.ADVXXZT6Round61.coefficientP122R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 122).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP122_lower : ((363381714018058764163 : ℝ) / 100000000000000000000000) ≤ rowsCellR2YP122Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18864_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 62307562302417931542365955950641152) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom08662_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom06381_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h3 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom04275_upper
    (show ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 766247770432944429179173513575154591809369561091801088) ≤ 0 by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom07776_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 62307562302417931542365955950641152) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom07777_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 62307562302417931542365955950641152) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19322_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 124615124604835863084731911901282304) by norm_num)
  have h7 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19323_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 124615124604835863084731911901282304) by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom06749_upper
    (show ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 766247770432944429179173513575154591809369561091801088) ≤ 0 by norm_num)
  have h9 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-342596749790939235270698048162893261165820660659 : ℝ) / 93536104789177786765035829293842113257979682750464) ≤ 0 by norm_num)
  have h10 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom19658_lower
    (show 0 ≤ ((1616040902977881441575823777471877 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h11 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom11806_upper
    (show ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 1532495540865888858358347027150309183618739122183602176) ≤ 0 by norm_num)
  have h12 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom14101_upper
    (show ((-8527148128769631533688619370040879197333074738523395 : ℝ) / 1532495540865888858358347027150309183618739122183602176) ≤ 0 by norm_num)
  unfold rowsCellR2YP122Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP122_eq_semantic : rowsCellR2YP122Expr30 =
    semanticQuantity130f (dualQ130fR2 122) 122 2 1 := by
  calc
    rowsCellR2YP122Expr30 = rowsCellR2YP122Raw30.value := rowsCellR2YP122_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 122) 122 2 1).value := by
      rw [rowsCellR2YP122_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP122_coefficient

theorem rowsCellR2YP122 : ((363381714018058764163 : ℝ) / 100000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 122) 122 2
      (roleIndex30 .Y) := by
  change ((363381714018058764163 : ℝ) / 100000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 122) 122 2 1
  rw [← rowsCellR2YP122_eq_semantic]
  exact rowsCellR2YP122_lower

noncomputable def rowsCellR2YP123Expr30 : ℝ :=
  (0 : ℝ)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP123_value_bridge : rowsCellR2YP123Expr30 = rowsCellR2YP123Raw30.value := by
  unfold rowsCellR2YP123Expr30 rowsCellR2YP123Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP123_coefficient :
    ((dualQ130fR2 123).coefficient : ℝ) =
      (coefficientQ130f 2 123 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP123R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 123 := OmegaBound.ADVXXZT6Round61.coefficientP123R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 123).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP123_lower : (0 : ℝ) ≤ rowsCellR2YP123Expr30 := by
  unfold rowsCellR2YP123Expr30
  linarith

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP123_eq_semantic : rowsCellR2YP123Expr30 =
    semanticQuantity130f (dualQ130fR2 123) 123 2 1 := by
  calc
    rowsCellR2YP123Expr30 = rowsCellR2YP123Raw30.value := rowsCellR2YP123_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 123) 123 2 1).value := by
      rw [rowsCellR2YP123_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP123_coefficient

theorem rowsCellR2YP123 : (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 123) 123 2
      (roleIndex30 .Y) := by
  change (0 : ℝ) ≤
    semanticQuantity130f (dualQ130fR2 123) 123 2 1
  rw [← rowsCellR2YP123_eq_semantic]
  exact rowsCellR2YP123_lower

noncomputable def rowsCellR2YP124Expr30 : ℝ :=
  ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) * Real.negMulLog ((1912078559316727 : ℝ) / 576460752303423488)
    + ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) * Real.negMulLog ((7648565223391735 : ℝ) / 2305843009213693952)
    + ((507261276172782324647788178565 : ℝ) / 324518553658426726783156020576256) * Real.negMulLog ((21126610731719586221658315502675 : ℝ) / 5192296858534827628530496329220096)
    + ((507261276172782324647788178565 : ℝ) / 324518553658426726783156020576256) * Real.negMulLog ((42253270849842112526919187245525 : ℝ) / 10384593717069655257060992658440192)
    + ((-6297445158534179753518060069852345818706358175 : ℝ) / 23384026197294446691258957323460528314494920687616) * Real.negMulLog ((6807025715440825 : ℝ) / 144115188075855872)
    + ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) * Real.negMulLog ((619298866768757744976842599353261 : ℝ) / 2596148429267413814265248164610048)
    + ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) * Real.negMulLog ((1238598693097140210120435974854187 : ℝ) / 5192296858534827628530496329220096)
    + ((-507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-6297445158534179753518060069852345818706358175 : ℝ) / 46768052394588893382517914646921056628989841375232) * Real.negMulLog ((65250568322487111 : ℝ) / 72057594037927936)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP124_value_bridge : rowsCellR2YP124Expr30 = rowsCellR2YP124Raw30.value := by
  unfold rowsCellR2YP124Expr30 rowsCellR2YP124Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP124_coefficient :
    ((dualQ130fR2 124).coefficient : ℝ) =
      (coefficientQ130f 2 124 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP124R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 124 := OmegaBound.ADVXXZT6Round61.coefficientP124R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 124).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP124_lower : ((312220502977961408537 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2YP124Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom05539_lower
    (show 0 ≤ ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom10120_lower
    (show 0 ≤ ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) by norm_num)
  have h2 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16102_lower
    (show 0 ≤ ((507261276172782324647788178565 : ℝ) / 324518553658426726783156020576256) by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom16282_lower
    (show 0 ≤ ((507261276172782324647788178565 : ℝ) / 324518553658426726783156020576256) by norm_num)
  have h4 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom09556_upper
    (show ((-6297445158534179753518060069852345818706358175 : ℝ) / 23384026197294446691258957323460528314494920687616) ≤ 0 by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17004_lower
    (show 0 ≤ ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) by norm_num)
  have h6 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom17213_lower
    (show 0 ≤ ((507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-507261276172782324647788178565 : ℝ) / 649037107316853453566312041152512) ≤ 0 by norm_num)
  have h8 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom12795_upper
    (show ((-6297445158534179753518060069852345818706358175 : ℝ) / 46768052394588893382517914646921056628989841375232) ≤ 0 by norm_num)
  unfold rowsCellR2YP124Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7, h8]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP124_eq_semantic : rowsCellR2YP124Expr30 =
    semanticQuantity130f (dualQ130fR2 124) 124 2 1 := by
  calc
    rowsCellR2YP124Expr30 = rowsCellR2YP124Raw30.value := rowsCellR2YP124_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 124) 124 2 1).value := by
      rw [rowsCellR2YP124_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP124_coefficient

theorem rowsCellR2YP124 : ((312220502977961408537 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 124) 124 2
      (roleIndex30 .Y) := by
  change ((312220502977961408537 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 124) 124 2 1
  rw [← rowsCellR2YP124_eq_semantic]
  exact rowsCellR2YP124_lower

noncomputable def rowsCellR2YP125Expr30 : ℝ :=
  ((18222294896981294163645998201875 : ℝ) / 498460498419343452338927647605129216) * Real.negMulLog ((11145387117783452921689370367087 : ℝ) / 21267647932558653966460912964485513216)
    + ((18222294896981294163645998201875 : ℝ) / 498460498419343452338927647605129216) * Real.negMulLog ((5579018377657918345082505243789 : ℝ) / 10633823966279326983230456482242756608)
    + ((-100070649695772038922334842858298562499590915625 : ℝ) / 11972621413014756705924586149611790497021399392059392) * Real.negMulLog ((1353775451855121 : ℝ) / 295147905179352825856)
    + ((18222294896981294163645998201875 : ℝ) / 996920996838686904677855295210258432) * Real.negMulLog ((1214938370693623053549931358612515729 : ℝ) / 10633823966279326983230456482242756608)
    + ((18222294896981294163645998201875 : ℝ) / 996920996838686904677855295210258432) * Real.negMulLog ((608158642332515387451288644603106163 : ℝ) / 5316911983139663491615228241121378304)
    + ((18222294896981294163645998201875 : ℝ) / 249230249209671726169463823802564608) * Real.negMulLog ((55582613757752071 : ℝ) / 288230376151711744)
    + ((-1012842779038767838297401487816482047708057333125 : ℝ) / 17958932119522135058886879224417685745532099088089088) * Real.negMulLog ((1 : ℝ) / 2)
    + ((-100070649695772038922334842858298562499590915625 : ℝ) / 23945242826029513411849172299223580994042798784118784) * Real.negMulLog ((147572598814224557807 : ℝ) / 147573952589676412928)

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP125_value_bridge : rowsCellR2YP125Expr30 = rowsCellR2YP125Raw30.value := by
  unfold rowsCellR2YP125Expr30 rowsCellR2YP125Raw30 LinearQ130f.value termsValue130f AtomQ130f.value
  norm_num <;> ring

theorem rowsCellR2YP125_coefficient :
    ((dualQ130fR2 125).coefficient : ℝ) =
      (coefficientQ130f 2 125 : ℝ) := by
  calc
    _ = (OmegaBound.ADVXXZT6Round61.coefficientQP125R2 : ℝ) := by rfl
    _ = OmegaBound.ADVXXZT6Round61.releasedParentCoefficient 2 125 := OmegaBound.ADVXXZT6Round61.coefficientP125R2_eq_released.symm
    _ = _ := (coefficientQ130f_cast 2 125).symm

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP125_lower : ((12723749517277424331 : ℝ) / 1000000000000000000000000) ≤ rowsCellR2YP125Expr30 := by
  have h0 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15997_lower
    (show 0 ≤ ((18222294896981294163645998201875 : ℝ) / 498460498419343452338927647605129216) by norm_num)
  have h1 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom15912_lower
    (show 0 ≤ ((18222294896981294163645998201875 : ℝ) / 498460498419343452338927647605129216) by norm_num)
  have h2 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom05057_upper
    (show ((-100070649695772038922334842858298562499590915625 : ℝ) / 11972621413014756705924586149611790497021399392059392) ≤ 0 by norm_num)
  have h3 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18321_lower
    (show 0 ≤ ((18222294896981294163645998201875 : ℝ) / 996920996838686904677855295210258432) by norm_num)
  have h4 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom18296_lower
    (show 0 ≤ ((18222294896981294163645998201875 : ℝ) / 996920996838686904677855295210258432) by norm_num)
  have h5 := mul_le_mul_of_nonneg_left OmegaBound.ADVXXZCert.retainedAtom12422_lower
    (show 0 ≤ ((18222294896981294163645998201875 : ℝ) / 249230249209671726169463823802564608) by norm_num)
  have h6 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom03980_upper
    (show ((-1012842779038767838297401487816482047708057333125 : ℝ) / 17958932119522135058886879224417685745532099088089088) ≤ 0 by norm_num)
  have h7 := mul_le_mul_of_nonpos_left OmegaBound.ADVXXZCert.retainedAtom15646_upper
    (show ((-100070649695772038922334842858298562499590915625 : ℝ) / 23945242826029513411849172299223580994042798784118784) ≤ 0 by norm_num)
  unfold rowsCellR2YP125Expr30
  linarith [h0, h1, h2, h3, h4, h5, h6, h7]

set_option maxHeartbeats 2000000 in
theorem rowsCellR2YP125_eq_semantic : rowsCellR2YP125Expr30 =
    semanticQuantity130f (dualQ130fR2 125) 125 2 1 := by
  calc
    rowsCellR2YP125Expr30 = rowsCellR2YP125Raw30.value := rowsCellR2YP125_value_bridge
    _ = (semanticRowQ130f (dualQ130fR2 125) 125 2 1).value := by
      rw [rowsCellR2YP125_raw]
    _ = _ := semanticRowQ130f_value _ _ _ _ rowsCellR2YP125_coefficient

theorem rowsCellR2YP125 : ((12723749517277424331 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 125) 125 2
      (roleIndex30 .Y) := by
  change ((12723749517277424331 : ℝ) / 1000000000000000000000000) ≤
    semanticQuantity130f (dualQ130fR2 125) 125 2 1
  rw [← rowsCellR2YP125_eq_semantic]
  exact rowsCellR2YP125_lower


end OmegaBound.ADVXXZGeneral
