-- Generated by `tools/iapply_cells.py` (aggregator mode) of the development repository (not part of this release).
import OmegaBound.ADVXXZGeneralRowsSource30Assembly
import OmegaBound.ADVXXZGeneralRowsCellsR4Y0
import OmegaBound.ADVXXZGeneralRowsCellsR4Y1
import OmegaBound.ADVXXZGeneralRowsCellsR4Y2
import OmegaBound.ADVXXZGeneralRowsCellsR4Y3
import OmegaBound.ADVXXZGeneralRowsCellsR4Y4
import OmegaBound.ADVXXZGeneralRowsCellsR4Y5
import OmegaBound.ADVXXZGeneralRowsCellsR4Y6
import OmegaBound.ADVXXZGeneralRowsCellsR4Y7

open scoped BigOperators
open OmegaBound.ADVXXZT6Round130f
namespace OmegaBound.ADVXXZGeneral

def rowsR4YQ30Num (p : Fin 126) : ℕ :=
  match p.1 with
  | 0 => 12668881110449454484
  | 1 => 0
  | 2 => 0
  | 3 => 510893759930417092521
  | 4 => 361730939347573765423
  | 5 => 12778195354933163159
  | 6 => 0
  | 7 => 0
  | 8 => 4023234944682572012406
  | 9 => 1802192685678113945453
  | 10 => 524567910786260383249
  | 11 => 0
  | 12 => 3916245676720820303503
  | 13 => 0
  | 14 => 1259444573443599830746
  | 15 => 2964539177423807031740
  | 16 => 783292764444878851672
  | 17 => 0
  | 18 => 237316063850343554524
  | 19 => 132454297339762125248
  | 20 => 13161389958240721164
  | 21 => 12746391710767223612
  | 22 => 49798840463753466612
  | 23 => 0
  | 24 => 124393796629205089726
  | 25 => 399775929054392108404
  | 26 => 12661319670263706602
  | 27 => 0
  | 28 => 2836100752796560626727
  | 29 => 4944461202288419572841
  | 30 => 5338233073547245797937
  | 31 => 579806907362751077575
  | 32 => 0
  | 33 => 4214028973357901206002
  | 34 => 0
  | 35 => 963294200112614346795
  | 36 => 2950726791173123090765
  | 37 => 759085231036262865833
  | 38 => 0
  | 39 => 237387798142738987882
  | 40 => 132236850879491874019
  | 41 => 13160655438910879294
  | 42 => 12675336769012776453
  | 43 => 0
  | 44 => 0
  | 45 => 684439208927504448463
  | 46 => 329574433959855793157
  | 47 => 12866128038522905900
  | 48 => 0
  | 49 => 0
  | 50 => 3408311886639428229469
  | 51 => 0
  | 52 => 488463758995376958166
  | 53 => 0
  | 54 => 4287627481422128119441
  | 55 => 0
  | 56 => 1436044105888616940171
  | 57 => 3196940314374714857666
  | 58 => 657083638826384222234
  | 59 => 0
  | 60 => 278326749683221739237
  | 61 => 75047545707868090288
  | 62 => 12974782659582430622
  | 63 => 12748633722382842689
  | 64 => 45463640819724551347
  | 65 => 0
  | 66 => 683373259233650065330
  | 67 => 327257932270317451102
  | 68 => 12867606711223337373
  | 69 => 0
  | 70 => 2739037010454751697891
  | 71 => 3875276744457117521195
  | 72 => 0
  | 73 => 493018838032313942841
  | 74 => 0
  | 75 => 4900259463229136505670
  | 76 => 0
  | 77 => 1416967591432242654859
  | 78 => 3665485642651879570182
  | 79 => 118772134303814166025
  | 80 => 0
  | 81 => 310433783566774045233
  | 82 => 0
  | 83 => 12722407535571709739
  | 84 => 12798760104210673569
  | 85 => 106863517140785863103
  | 86 => 0
  | 87 => 152880257337250256067
  | 88 => 397699880508560097743
  | 89 => 12666869405470909352
  | 90 => 0
  | 91 => 4391867390314321855448
  | 92 => 5541395976438129805890
  | 93 => 5278437417565720017693
  | 94 => 582711047145253033739
  | 95 => 0
  | 96 => 4924846079650571020158
  | 97 => 0
  | 98 => 956777990335954794082
  | 99 => 3121734437791123747747
  | 100 => 713326693556313579636
  | 101 => 0
  | 102 => 275966893165167532114
  | 103 => 66232142585864990903
  | 104 => 12973347700907070053
  | 105 => 12807601924847324354
  | 106 => 105312729968067123561
  | 107 => 0
  | 108 => 535949474307351006703
  | 109 => 362402105927266977637
  | 110 => 12777347225871002334
  | 111 => 0
  | 112 => 4326194500163968542310
  | 113 => 5088976044988365643283
  | 114 => 1581850538026198662632
  | 115 => 542845529734860251728
  | 116 => 0
  | 117 => 5237278513323965570962
  | 118 => 0
  | 119 => 1287835487047853569753
  | 120 => 3570689763569998412150
  | 121 => 98096147927880863439
  | 122 => 0
  | 123 => 311470036406569505444
  | 124 => 0
  | 125 => 12723871517384369620
  | _ => 0

noncomputable def rowsR4YQ30 (p : Fin 126) : ℝ :=
  (rowsR4YQ30Num p : ℝ) / 1000000000000000000000000

theorem rowsR4YQ30_le_semantic (p : Fin 126) :
    rowsR4YQ30 p ≤ semanticQuantity130f (dualQ130fR4 p) p 4
      (roleIndex30 .Y) := by
  fin_cases p
  · convert rowsCellR4YP000 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP001 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP002 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP003 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP004 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP005 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP006 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP007 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP008 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP009 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP010 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP011 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP012 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP013 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP014 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP015 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP016 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP017 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP018 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP019 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP020 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP021 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP022 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP023 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP024 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP025 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP026 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP027 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP028 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP029 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP030 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP031 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP032 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP033 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP034 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP035 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP036 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP037 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP038 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP039 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP040 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP041 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP042 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP043 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP044 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP045 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP046 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP047 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP048 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP049 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP050 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP051 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP052 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP053 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP054 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP055 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP056 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP057 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP058 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP059 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP060 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP061 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP062 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP063 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP064 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP065 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP066 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP067 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP068 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP069 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP070 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP071 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP072 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP073 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP074 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP075 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP076 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP077 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP078 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP079 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP080 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP081 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP082 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP083 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP084 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP085 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP086 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP087 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP088 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP089 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP090 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP091 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP092 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP093 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP094 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP095 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP096 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP097 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP098 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP099 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP100 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP101 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP102 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP103 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP104 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP105 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP106 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP107 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP108 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP109 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP110 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP111 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP112 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP113 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP114 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP115 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP116 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP117 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP118 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP119 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP120 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP121 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP122 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP123 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP124 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]
  · convert rowsCellR4YP125 using 1 <;> norm_num [rowsR4YQ30, rowsR4YQ30Num]

theorem rowsR4YQ30Num_sum :
    (∑ p : Fin 126, rowsR4YQ30Num p) = 123252868426855345801868 := by
  decide +kernel

theorem rowsR4YQ30_sum :
    (∑ p : Fin 126, rowsR4YQ30 p) = ((30813217106713836450467 : ℝ) / 250000000000000000000000) := by
  simp only [rowsR4YQ30]
  rw [← Finset.sum_div, ← Nat.cast_sum, rowsR4YQ30Num_sum]
  norm_num

theorem rowsR4YFlooredSum_le_paper30 :
    (∑ p : Fin 126, rowsR4YQ30 p) ≤
      Real.log 2 * paperRow30 4 .Y / (releasedCertificate.D ^ 2 : ℝ) := by
  have hscaled :
      (releasedCertificate.D ^ 2 : ℝ) * (∑ p : Fin 126, rowsR4YQ30 p) ≤
        Real.log 2 * paperRow30 4 .Y := by
    rw [paperRow_eq_sum30, Finset.mul_sum, Finset.mul_sum]
    exact Finset.sum_le_sum (fun p _ => by
      calc
        (releasedCertificate.D ^ 2 : ℝ) * rowsR4YQ30 p ≤
            (releasedCertificate.D ^ 2 : ℝ) * semanticQuantity130f
              (dualQ130fR4 p) p 4 (roleIndex30 .Y) := by
          exact mul_le_mul_of_nonneg_left (rowsR4YQ30_le_semantic p) (by positivity)
        _ ≤ Real.log 2 * paperParent30 p 4 .Y :=
          semantic_parent_bound (dualQ130fR4 p) p 4 .Y)
  have hD : (0 : ℝ) < (releasedCertificate.D ^ 2 : ℝ) := by
    norm_num [releasedCertificate, OmegaBound.ADVXXZT2.certDen]
  apply (le_div_iff₀ hD).2
  simpa [mul_comm] using hscaled

theorem R6_le_rowsR4YFlooredSum30 :
    OmegaBound.ADVXXZCert.R6 ≤ (∑ p : Fin 126, rowsR4YQ30 p) := by
  rw [rowsR4YQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R6]

theorem rowsR4YFlooredSum_margin30 :
    (∑ p : Fin 126, rowsR4YQ30 p) - OmegaBound.ADVXXZCert.R6 =
      ((59886902967 : ℝ) / 250000000000000000000000) := by
  rw [rowsR4YQ30_sum]
  norm_num [OmegaBound.ADVXXZCert.R6]

theorem R6_le_rowsR4YPaper30 :
    OmegaBound.ADVXXZCert.R6 ≤
      Real.log 2 * paperRow30 4 .Y / (releasedCertificate.D ^ 2 : ℝ) :=
  R6_le_rowsR4YFlooredSum30.trans rowsR4YFlooredSum_le_paper30

end OmegaBound.ADVXXZGeneral
