-- Generated by `tools/ctriple/genregions.py` of the development repository (not part of this release).
-- The release tooling removed unused declarations and rewrote its imports.
import OmegaBound.ADVXXZCertRegionalSemanticBase
import OmegaBound.ADVXXZCertSemantic
set_option maxRecDepth 1000000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZR3CertificateSplitData

open ADVXXZ

def r3ResXRow08Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r3ResXRow08Dist : SplitDist 4 where
  num := r3ResXRow08Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow09Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 4503599627370481
  | 3 => 4503599627370493
  | 9 => 4503599627370490
  | 27 => 4503599627370520
  | _ => 0

def r3ResXRow09Dist : SplitDist 4 where
  num := r3ResXRow09Num
  den := 18014398509481984
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow10Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 162267466431542128679496821524759
  | 3 => 162267466431542128679496821524759
  | 9 => 162251087226884598103659199051497
  | 27 => 162251087226884598103659199051497
  | _ => 0

def r3ResXRow10Dist : SplitDist 4 where
  num := r3ResXRow10Num
  den := 649037107316853453566312041152512
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow11Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 2596148316068870533720340190453951
  | 3 => 2596148316068870533720340190453951
  | 9 => 2596148542465957094810156138766145
  | 27 => 2596148542465957094810156138766145
  | _ => 0

def r3ResXRow11Dist : SplitDist 4 where
  num := r3ResXRow11Num
  den := 10384593717069655257060992658440192
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow12Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 1329227986407040693101429011581645449
  | 3 => 1329227986407040693101429011581645449
  | 9 => 1329228005162791052706185108979043703
  | 27 => 1329228005162791052706185108979043703
  | _ => 0

def r3ResXRow12Dist : SplitDist 4 where
  num := r3ResXRow12Num
  den := 5316911983139663491615228241121378304
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow13Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 166153497385396703445547119703740685
  | 3 => 166153497385396703445547119703740685
  | 9 => 166153501560832264780404645366345459
  | 27 => 166153501560832264780404645366345459
  | _ => 0

def r3ResXRow13Dist : SplitDist 4 where
  num := r3ResXRow13Num
  den := 664613997892457936451903530140172288
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow14Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 20769180338470094815766556868802205
  | 3 => 20769180338470094815766556868802205
  | 9 => 20769194529808526212477413764958563
  | 27 => 20769194529808526212477413764958563
  | _ => 0

def r3ResXRow14Dist : SplitDist 4 where
  num := r3ResXRow14Num
  den := 83076749736557242056487941267521536
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r3ResXRow15Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 1297931250776367465653298245488969
  | 3 => 1297931250776367465653298245488969
  | 9 => 1298217178491046348611949919121079
  | 27 => 1298217178491046348611949919121079
  | _ => 0

def r3ResXRow15Dist : SplitDist 4 where
  num := r3ResXRow15Num
  den := 5192296858534827628530496329220096
  den_pos := by decide +kernel
  sum_num := by decide +kernel

end OmegaBound.ADVXXZR3CertificateSplitData
