-- Generated by `tools/advxxz_cert.py` of the development repository (not part of this release).
import OmegaBound.ADVXXZCertSemanticBase
set_option maxRecDepth 1000000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZCertSemantic

open OmegaBound.ADVXXZCert

def level3Specs10 : List DistSpec :=
  [{ sourceStart := 10527, sourceSize := 6, nums := [812510439817879832494080, 20207799918080814502379520, 37008023474123236108664832, 37008157888781086026104832, 20207872340217288374353920, 812514621984095927795712], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id262_ident_0_6_shape_5_1_2_r1_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10533, sourceSize := 6, nums := [818893600711353147850752, 20084630436860582820839424, 37124791820929679556083712, 37124931147401327328362496, 20084736112147507584172032, 818895564953950334484480], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id262_ident_0_6_shape_5_1_2_r2_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10539, sourceSize := 6, nums := [811164588949283757096960, 20205482449897188526915584, 37011686099956761467289600, 37011848971188886151626752, 20205525836941789784702976, 811170736070491084161024], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id262_ident_0_6_shape_5_1_2_r3_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10545, sourceSize := 6, nums := [764778048444272883007488, 20062195505912742634586112, 37201478773663249138188288, 37201457741900112054976512, 20062173628785468647669760, 764794984298555413364736], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id262_ident_0_6_shape_5_1_2_r4_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10551, sourceSize := 6, nums := [769938524375096349425664, 19992668958602997188788224, 37265839032153150377164800, 37265829175939350499688448, 19992650354471838708400128, 769952637461967648325632], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id262_ident_0_6_shape_5_1_2_r5_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10557, sourceSize := 6, nums := [767461181675409330143232, 20013875859372171079974912, 37247114324715521534066688, 37247095044518393935822848, 20013854325154508332597248, 767477947568396559187968], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id262_ident_0_6_shape_5_1_2_r6_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10563, sourceSize := 6, nums := [0, 0, 28111892453765212998205440, 41472608453669916638183424, 0, 46472377775569271135404032], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_region_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10569, sourceSize := 6, nums := [818405267892893443424256, 37127483030439150351286272, 20082417393595559461257216, 20082492008410348731236352, 37127669136150356199211008, 818411846516092585377792], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_r1_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10575, sourceSize := 6, nums := [811998419430589234937856, 37008634778902417543004160, 20207730443552765276848128, 20207763400114563075538944, 37008734823784504551800832, 812016817219561089662976], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_r2_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10581, sourceSize := 6, nums := [769904519967012991008768, 37263422344122792998338560, 19995122396568197806424064, 19995099025900042375397376, 37263400611388766256365568, 769929785057588344258560], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_r3_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10587, sourceSize := 6, nums := [767366978940586250207232, 37244428057183029647376384, 20016654696627816389148672, 20016635297399287584915456, 37244415338103910850101248, 767378314749770050043904], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_r4_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10593, sourceSize := 6, nums := [811427292766027061919744, 37009215227992101850447872, 20207727021192348086304768, 20207754905645155130277888, 37009309384339159573856256, 811444851069609068986368], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_r5_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10599, sourceSize := 6, nums := [764460322826778706968576, 37198823318840453967642624, 20065278355596580076126208, 20065077255854349166313472, 37198289630225320743272448, 764949799660918111469568], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id263_ident_0_6_shape_5_2_1_r6_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10605, sourceSize := 16, nums := [1351045043812948116504576, 1298814605635908356014080, 1298814605952004594335744, 1351045043341933078904832, 25065546602630919997095936, 25065546524447770587168768, 1298815416219916465864704, 25065578728392221716905984, 1298815416107507776487424, 1298814605757703293763584, 1298814605955819129274368, 1298815416063748837736448, 25065578678671830241247232, 1298815416013888897941504, 1351008986958506408017920, 1351008987041773274529792], nonempty := by decide, sum_num := by
       have h := norm_term_zero_L3_id264_ident_0_6_shape_5_3_0_csd_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10621, sourceSize := 10, nums := [932567563280609515143168, 19967884326803541212528640, 18097310767458089158311936, 18097310830056617948479488, 932567592572741404852224, 18097310862659391496126464, 18097310758475344373612544, 932567594710714653081600, 19969480795463561414443008, 932567591523789595213824], nonempty := by decide, sum_num := by
       have h := norm_term_zero_L3_id265_ident_0_6_shape_6_0_2_csd_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10631, sourceSize := 6, nums := [19341680697872647156924416, 19339289207499651979149312, 19349761140466447810560000, 19337981542901061286625280, 19350078239373283534307328, 19338087854891309004226560], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_region_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10637, sourceSize := 4, nums := [13261737338222952371453952, 44714565969965711697641472, 44828831600694261996060672, 13251743774121474706636800], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_r1_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10641, sourceSize := 4, nums := [13259211213571315048906752, 44810690770636421361303552, 44729604775670902236905472, 13257371923125762124677120], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_r2_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10645, sourceSize := 4, nums := [13274931291035894072475648, 44737100222095587218030592, 44784965396308717064945664, 13259881773564202416340992], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_r3_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10649, sourceSize := 4, nums := [13313427332682329578536960, 44715327953798090075406336, 44715328072392532549435392, 13312795324131448568414208], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_r4_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10653, sourceSize := 4, nums := [13274476834821429660745728, 44785222197205343290785792, 44737131313655905033125888, 13260048337321722787135488], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_r5_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10657, sourceSize := 4, nums := [13313355373239797897232384, 44715405928332551975337984, 44715405801346147131850752, 13312711580085903767371776], nonempty := by decide, sum_num := by
       have h := norm_term_general_L3_id266_ident_0_6_shape_6_1_1_r6_split_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10661, sourceSize := 10, nums := [932388962339358586699776, 19970410251679199114821632, 18096226465392365112655872, 18096226430746632388608000, 932388997781993098838016, 18096226358357056706052096, 18096226435963548774432768, 932388999166364271771648, 19972006779164029718888448, 932389002413852999024640], nonempty := by decide, sum_num := by
       have h := norm_term_zero_L3_id267_ident_0_6_shape_6_2_0_csd_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10671, sourceSize := 4, nums := [29014219670751254811770880, 29014219670751061538242560, 29014219670751080865595392, 29014219670751003556184064], nonempty := by decide, sum_num := by
       have h := norm_term_zero_L3_id268_ident_0_6_shape_7_0_1_csd_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10675, sourceSize := 4, nums := [29014219670751254811770880, 29014219670751061538242560, 29014219670751080865595392, 29014219670751003556184064], nonempty := by decide, sum_num := by
       have h := norm_term_zero_L3_id269_ident_0_6_shape_7_1_0_csd_sum
       norm_num [certDen] at h ⊢ },
   { sourceStart := 10679, sourceSize := 1, nums := [116056878683004400771792896], nonempty := by decide, sum_num := by
       have h := norm_term_zero_L3_id270_ident_0_6_shape_8_0_0_csd_sum
       norm_num [certDen] at h ⊢ }]

end OmegaBound.ADVXXZCertSemantic
