-- Generated by `tools/ctriple/genregions.py` of the development repository (not part of this release).
-- The release tooling removed unused declarations and rewrote its imports.
import OmegaBound.ADVXXZCertRegionalSemanticBase
import OmegaBound.ADVXXZCertSemantic
set_option maxRecDepth 1000000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZR2CertificateSplitData

open ADVXXZ

def r2ResYRow00Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 0 => 1
  | _ => 0

def r2ResYRow00Dist : SplitDist 4 where
  num := r2ResYRow00Num
  den := 1
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow01Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 1 => 2251799813685251
  | 3 => 2251799813685252
  | 9 => 2251799813685240
  | 27 => 2251799813685249
  | _ => 0

def r2ResYRow01Dist : SplitDist 4 where
  num := r2ResYRow01Num
  den := 9007199254740992
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow02Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 2 => 4631246415899924
  | 4 => 99203616390681003
  | 6 => 4631246490001934
  | 10 => 89882148056852624
  | 12 => 89882148151477712
  | 18 => 4631246494522282
  | 28 => 89882147628401824
  | 30 => 89882147589728864
  | 36 => 99203558591319984
  | 54 => 4631246494537337
  | _ => 0

def r2ResYRow02Dist : SplitDist 4 where
  num := r2ResYRow02Num
  den := 576460752303423488
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow03Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 5 => 6710764332848119
  | 7 => 6710764331780081
  | 11 => 6451211927244594
  | 13 => 124502002990958845
  | 15 => 6451211926957497
  | 19 => 6451211441054414
  | 21 => 6451211454794336
  | 29 => 6451211927017833
  | 31 => 124502002970784928
  | 33 => 6451211927011398
  | 37 => 124501980631998464
  | 39 => 124501980583281280
  | 45 => 6710781488381135
  | 55 => 6451211441081801
  | 57 => 6451211441451934
  | 63 => 6710781486776829
  | _ => 0

def r2ResYRow03Dist : SplitDist 4 where
  num := r2ResYRow03Num
  den := 576460752303423488
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow04Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 8 => 7265049192005509
  | 14 => 146862018215033664
  | 16 => 146862018082066368
  | 20 => 7027703454132189
  | 22 => 149246416460348448
  | 24 => 7027703454770472
  | 32 => 146862018034722944
  | 34 => 146862018080442112
  | 38 => 149246415978601568
  | 40 => 2797163328625278402
  | 42 => 149246415353218624
  | 46 => 146862022236698048
  | 48 => 146862022241495072
  | 56 => 7027703440660226
  | 58 => 149246416485858176
  | 60 => 7027703454707204
  | 64 => 146862022215641376
  | 66 => 146862022233149152
  | 72 => 7265001188558350
  | _ => 0

def r2ResYRow04Dist : SplitDist 4 where
  num := r2ResYRow04Num
  den := 4611686018427387904
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow05Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 17 => 5501268602596789
  | 23 => 5198841482917122
  | 25 => 5198841480331102
  | 35 => 5501268642709248
  | 41 => 128216249561090800
  | 43 => 128216250479953808
  | 47 => 5198840985266290
  | 49 => 128216274371391815
  | 51 => 5198840985232993
  | 59 => 5198841480274653
  | 61 => 5198841480351315
  | 65 => 5198840984289406
  | 67 => 128216274364033152
  | 69 => 5198840985012252
  | 73 => 5501218207798047
  | 75 => 5501218210174696
  | _ => 0

def r2ResYRow05Dist : SplitDist 4 where
  num := r2ResYRow05Num
  den := 576460752303423488
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow06Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 26 => 6834851823276454
  | 44 => 164911334341708256
  | 50 => 198939860312800669
  | 52 => 198939859380984576
  | 62 => 6834851407929167
  | 68 => 198939859405816832
  | 70 => 198939859475002752
  | 74 => 6834850476314147
  | 76 => 164911327501801408
  | 78 => 6834850481212715
  | _ => 0

def r2ResYRow06Dist : SplitDist 4 where
  num := r2ResYRow06Num
  den := 1152921504606846976
  den_pos := by decide +kernel
  sum_num := by decide +kernel

def r2ResYRow07Num (c : Chunk 4) : ℕ :=
  match (ADVXXZCertSemantic.chunkIndex c).1 with
  | 53 => 4503599627370520
  | 71 => 4503599627370490
  | 77 => 4503599627370493
  | 79 => 4503599627370481
  | _ => 0

def r2ResYRow07Dist : SplitDist 4 where
  num := r2ResYRow07Num
  den := 18014398509481984
  den_pos := by decide +kernel
  sum_num := by decide +kernel

end OmegaBound.ADVXXZR2CertificateSplitData
