-- GENERATED by release/emitters/emit_round61_cohorts.py.
-- Production cohort: released region 0, parents P032--P063 (32 rows, one native check).
import OmegaBound.ReleaseCompactR61CohortBase

set_option maxRecDepth 100000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZT6Round61

def coefficientQP032R0 : ℚ := ((16161465212330532871048764351457 : ℚ) / 20769187434139310514121985316880384)

def coefficientQP033R0 : ℚ := ((21593615504114567240340889748125 : ℚ) / 3894222643901120721397872246915072)

def coefficientQP034R0 : ℚ := ((3070594849749048854953504078415 : ℚ) / 486777830487640090174734030864384)

def coefficientQP035R0 : ℚ := ((1578159475903385519059637465183045 : ℚ) / 249230249209671726169463823802564608)

def coefficientQP036R0 : ℚ := (0 : ℚ)

def coefficientQP037R0 : ℚ := ((1514085883991740175480946529695 : ℚ) / 324518553658426726783156020576256)

def coefficientQP038R0 : ℚ := (0 : ℚ)

def coefficientQP039R0 : ℚ := ((9898325112296869505451774725135 : ℚ) / 62307562302417931542365955950641152)

def coefficientQP040R0 : ℚ := (0 : ℚ)

def coefficientQP041R0 : ℚ := ((18411260336998951163234898701695 : ℚ) / 996920996838686904677855295210258432)

def coefficientQP042R0 : ℚ := ((9108028321555133997020631069803 : ℚ) / 498460498419343452338927647605129216)

def coefficientQP043R0 : ℚ := ((833513010430242767040947067075 : ℚ) / 1298074214633706907132624082305024)

def coefficientQP044R0 : ℚ := ((2319846973287393432340395879733 : ℚ) / 1947111321950560360698936123457536)

def coefficientQP045R0 : ℚ := (0 : ℚ)

def coefficientQP046R0 : ℚ := ((439496006272459341522550287001 : ℚ) / 2596148429267413814265248164610048)

def coefficientQP047R0 : ℚ := ((1534923372085133998290905278557 : ℚ) / 83076749736557242056487941267521536)

def coefficientQP048R0 : ℚ := ((17964587798544743308127671080923 : ℚ) / 31153781151208965771182977975320576)

def coefficientQP049R0 : ℚ := ((122058223617833549786559657393263 : ℚ) / 20769187434139310514121985316880384)

def coefficientQP050R0 : ℚ := (0 : ℚ)

def coefficientQP051R0 : ℚ := ((20990367752779106541653836840385 : ℚ) / 15576890575604482885591488987660288)

def coefficientQP052R0 : ℚ := ((9234232687727177520616722980983 : ℚ) / 31153781151208965771182977975320576)

def coefficientQP053R0 : ℚ := ((32796261466751038559596220184781 : ℚ) / 249230249209671726169463823802564608)

def coefficientQP054R0 : ℚ := ((11084845998358237491826153473809181811 : ℚ) / 2041694201525630780780247644590609268736)

def coefficientQP055R0 : ℚ := ((13088166565247553238407594557703 : ℚ) / 2596148429267413814265248164610048)

def coefficientQP056R0 : ℚ := ((12974357572052334489540150393723 : ℚ) / 2596148429267413814265248164610048)

def coefficientQP057R0 : ℚ := (0 : ℚ)

def coefficientQP058R0 : ℚ := ((63317022598562362984069524941 : ℚ) / 20282409603651670423947251286016)

def coefficientQP059R0 : ℚ := (0 : ℚ)

def coefficientQP060R0 : ℚ := ((11659174672100603991166522491795 : ℚ) / 166153499473114484112975882535043072)

def coefficientQP061R0 : ℚ := (0 : ℚ)

def coefficientQP062R0 : ℚ := ((3053173528522233874987441486645 : ℚ) / 166153499473114484112975882535043072)

def coefficientQP063R0 : ℚ := ((3064046352227493359689749159763 : ℚ) / 166153499473114484112975882535043072)

/-- One executable certificate for the 32 rows of this cohort. -/
theorem releaseCompactR61CohortR0P032P063Check :
    releaseCompactR61RowOK 0 32 coefficientQP032R0 ∧
    releaseCompactR61RowOK 0 33 coefficientQP033R0 ∧
    releaseCompactR61RowOK 0 34 coefficientQP034R0 ∧
    releaseCompactR61RowOK 0 35 coefficientQP035R0 ∧
    releaseCompactR61RowOK 0 36 coefficientQP036R0 ∧
    releaseCompactR61RowOK 0 37 coefficientQP037R0 ∧
    releaseCompactR61RowOK 0 38 coefficientQP038R0 ∧
    releaseCompactR61RowOK 0 39 coefficientQP039R0 ∧
    releaseCompactR61RowOK 0 40 coefficientQP040R0 ∧
    releaseCompactR61RowOK 0 41 coefficientQP041R0 ∧
    releaseCompactR61RowOK 0 42 coefficientQP042R0 ∧
    releaseCompactR61RowOK 0 43 coefficientQP043R0 ∧
    releaseCompactR61RowOK 0 44 coefficientQP044R0 ∧
    releaseCompactR61RowOK 0 45 coefficientQP045R0 ∧
    releaseCompactR61RowOK 0 46 coefficientQP046R0 ∧
    releaseCompactR61RowOK 0 47 coefficientQP047R0 ∧
    releaseCompactR61RowOK 0 48 coefficientQP048R0 ∧
    releaseCompactR61RowOK 0 49 coefficientQP049R0 ∧
    releaseCompactR61RowOK 0 50 coefficientQP050R0 ∧
    releaseCompactR61RowOK 0 51 coefficientQP051R0 ∧
    releaseCompactR61RowOK 0 52 coefficientQP052R0 ∧
    releaseCompactR61RowOK 0 53 coefficientQP053R0 ∧
    releaseCompactR61RowOK 0 54 coefficientQP054R0 ∧
    releaseCompactR61RowOK 0 55 coefficientQP055R0 ∧
    releaseCompactR61RowOK 0 56 coefficientQP056R0 ∧
    releaseCompactR61RowOK 0 57 coefficientQP057R0 ∧
    releaseCompactR61RowOK 0 58 coefficientQP058R0 ∧
    releaseCompactR61RowOK 0 59 coefficientQP059R0 ∧
    releaseCompactR61RowOK 0 60 coefficientQP060R0 ∧
    releaseCompactR61RowOK 0 61 coefficientQP061R0 ∧
    releaseCompactR61RowOK 0 62 coefficientQP062R0 ∧
    releaseCompactR61RowOK 0 63 coefficientQP063R0 := by
  unfold releaseCompactR61RowOK
  native_decide

theorem coefficientP032R0_eq_released : releasedParentCoefficient 0 32 = (coefficientQP032R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 32 coefficientQP032R0
    releaseCompactR61CohortR0P032P063Check.1

theorem coefficientP033R0_eq_released : releasedParentCoefficient 0 33 = (coefficientQP033R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 33 coefficientQP033R0
    releaseCompactR61CohortR0P032P063Check.2.1

theorem coefficientP034R0_eq_released : releasedParentCoefficient 0 34 = (coefficientQP034R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 34 coefficientQP034R0
    releaseCompactR61CohortR0P032P063Check.2.2.1

theorem coefficientP035R0_eq_released : releasedParentCoefficient 0 35 = (coefficientQP035R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 35 coefficientQP035R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.1

theorem coefficientP036R0_eq_released : releasedParentCoefficient 0 36 = (coefficientQP036R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 36 coefficientQP036R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.1

theorem coefficientP037R0_eq_released : releasedParentCoefficient 0 37 = (coefficientQP037R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 37 coefficientQP037R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.1

theorem coefficientP038R0_eq_released : releasedParentCoefficient 0 38 = (coefficientQP038R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 38 coefficientQP038R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.1

theorem coefficientP039R0_eq_released : releasedParentCoefficient 0 39 = (coefficientQP039R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 39 coefficientQP039R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.1

theorem coefficientP040R0_eq_released : releasedParentCoefficient 0 40 = (coefficientQP040R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 40 coefficientQP040R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.1

theorem coefficientP041R0_eq_released : releasedParentCoefficient 0 41 = (coefficientQP041R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 41 coefficientQP041R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.1

theorem coefficientP042R0_eq_released : releasedParentCoefficient 0 42 = (coefficientQP042R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 42 coefficientQP042R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP043R0_eq_released : releasedParentCoefficient 0 43 = (coefficientQP043R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 43 coefficientQP043R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP044R0_eq_released : releasedParentCoefficient 0 44 = (coefficientQP044R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 44 coefficientQP044R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP045R0_eq_released : releasedParentCoefficient 0 45 = (coefficientQP045R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 45 coefficientQP045R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP046R0_eq_released : releasedParentCoefficient 0 46 = (coefficientQP046R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 46 coefficientQP046R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP047R0_eq_released : releasedParentCoefficient 0 47 = (coefficientQP047R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 47 coefficientQP047R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP048R0_eq_released : releasedParentCoefficient 0 48 = (coefficientQP048R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 48 coefficientQP048R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP049R0_eq_released : releasedParentCoefficient 0 49 = (coefficientQP049R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 49 coefficientQP049R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP050R0_eq_released : releasedParentCoefficient 0 50 = (coefficientQP050R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 50 coefficientQP050R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP051R0_eq_released : releasedParentCoefficient 0 51 = (coefficientQP051R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 51 coefficientQP051R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP052R0_eq_released : releasedParentCoefficient 0 52 = (coefficientQP052R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 52 coefficientQP052R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP053R0_eq_released : releasedParentCoefficient 0 53 = (coefficientQP053R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 53 coefficientQP053R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP054R0_eq_released : releasedParentCoefficient 0 54 = (coefficientQP054R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 54 coefficientQP054R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP055R0_eq_released : releasedParentCoefficient 0 55 = (coefficientQP055R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 55 coefficientQP055R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP056R0_eq_released : releasedParentCoefficient 0 56 = (coefficientQP056R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 56 coefficientQP056R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP057R0_eq_released : releasedParentCoefficient 0 57 = (coefficientQP057R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 57 coefficientQP057R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP058R0_eq_released : releasedParentCoefficient 0 58 = (coefficientQP058R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 58 coefficientQP058R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP059R0_eq_released : releasedParentCoefficient 0 59 = (coefficientQP059R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 59 coefficientQP059R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP060R0_eq_released : releasedParentCoefficient 0 60 = (coefficientQP060R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 60 coefficientQP060R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP061R0_eq_released : releasedParentCoefficient 0 61 = (coefficientQP061R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 61 coefficientQP061R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP062R0_eq_released : releasedParentCoefficient 0 62 = (coefficientQP062R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 62 coefficientQP062R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP063R0_eq_released : releasedParentCoefficient 0 63 = (coefficientQP063R0 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 0 63 coefficientQP063R0
    releaseCompactR61CohortR0P032P063Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2

end OmegaBound.ADVXXZT6Round61
