-- GENERATED by release/emitters/emit_round61_cohorts.py.
-- Production cohort: released region 2, parents P096--P125 (30 rows, one native check).
import OmegaBound.ReleaseCompactR61CohortBase

set_option maxRecDepth 100000
set_option linter.style.longLine false

namespace OmegaBound.ADVXXZT6Round61

def coefficientQP096R2 : ℚ := (0 : ℚ)

def coefficientQP097R2 : ℚ := ((7067144661965969296233373446311142253 : ℚ) / 1361129467683753853853498429727072845824)

def coefficientQP098R2 : ℚ := (0 : ℚ)

def coefficientQP099R2 : ℚ := (0 : ℚ)

def coefficientQP100R2 : ℚ := ((6107938283437586269931315975147 : ℚ) / 5192296858534827628530496329220096)

def coefficientQP101R2 : ℚ := ((56916245800564003845644934206065 : ℚ) / 10384593717069655257060992658440192)

def coefficientQP102R2 : ℚ := ((698954249736961648577259473281 : ℚ) / 7788445287802241442795744493830144)

def coefficientQP103R2 : ℚ := ((1789655133369188307187011292995 : ℚ) / 5192296858534827628530496329220096)

def coefficientQP104R2 : ℚ := ((12218380578502953271580876086643 : ℚ) / 664613997892457936451903530140172288)

def coefficientQP105R2 : ℚ := ((3086179085176112617584462792425 : ℚ) / 166153499473114484112975882535043072)

def coefficientQP106R2 : ℚ := ((9767907733916845835369365797539 : ℚ) / 20769187434139310514121985316880384)

def coefficientQP107R2 : ℚ := ((10257500661299042068317098402775 : ℚ) / 10384593717069655257060992658440192)

def coefficientQP108R2 : ℚ := (0 : ℚ)

def coefficientQP109R2 : ℚ := ((11780277999634612463114464202685 : ℚ) / 166153499473114484112975882535043072)

def coefficientQP110R2 : ℚ := ((9158777443199644930022808369227 : ℚ) / 498460498419343452338927647605129216)

def coefficientQP111R2 : ℚ := ((11169656596917288118787544328227 : ℚ) / 20769187434139310514121985316880384)

def coefficientQP112R2 : ℚ := (0 : ℚ)

def coefficientQP113R2 : ℚ := ((11263803222782106911784471490903 : ℚ) / 2596148429267413814265248164610048)

def coefficientQP114R2 : ℚ := ((96006279088714084490104728436459 : ℚ) / 31153781151208965771182977975320576)

def coefficientQP115R2 : ℚ := (0 : ℚ)

def coefficientQP116R2 : ℚ := ((18389590165080015568536455822001 : ℚ) / 10384593717069655257060992658440192)

def coefficientQP117R2 : ℚ := (0 : ℚ)

def coefficientQP118R2 : ℚ := ((4012765952515436447796629891093284171 : ℚ) / 680564733841876926926749214863536422912)

def coefficientQP119R2 : ℚ := (0 : ℚ)

def coefficientQP120R2 : ℚ := (0 : ℚ)

def coefficientQP121R2 : ℚ := ((3917085499497813488272697945741 : ℚ) / 41538374868278621028243970633760768)

def coefficientQP122R2 : ℚ := ((1616040902977881441575823777471877 : ℚ) / 249230249209671726169463823802564608)

def coefficientQP123R2 : ℚ := (0 : ℚ)

def coefficientQP124R2 : ℚ := ((507261276172782324647788178565 : ℚ) / 1298074214633706907132624082305024)

def coefficientQP125R2 : ℚ := ((18222294896981294163645998201875 : ℚ) / 996920996838686904677855295210258432)

/-- One executable certificate for the 30 rows of this cohort. -/
theorem releaseCompactR61CohortR2P096P125Check :
    releaseCompactR61RowOK 2 96 coefficientQP096R2 ∧
    releaseCompactR61RowOK 2 97 coefficientQP097R2 ∧
    releaseCompactR61RowOK 2 98 coefficientQP098R2 ∧
    releaseCompactR61RowOK 2 99 coefficientQP099R2 ∧
    releaseCompactR61RowOK 2 100 coefficientQP100R2 ∧
    releaseCompactR61RowOK 2 101 coefficientQP101R2 ∧
    releaseCompactR61RowOK 2 102 coefficientQP102R2 ∧
    releaseCompactR61RowOK 2 103 coefficientQP103R2 ∧
    releaseCompactR61RowOK 2 104 coefficientQP104R2 ∧
    releaseCompactR61RowOK 2 105 coefficientQP105R2 ∧
    releaseCompactR61RowOK 2 106 coefficientQP106R2 ∧
    releaseCompactR61RowOK 2 107 coefficientQP107R2 ∧
    releaseCompactR61RowOK 2 108 coefficientQP108R2 ∧
    releaseCompactR61RowOK 2 109 coefficientQP109R2 ∧
    releaseCompactR61RowOK 2 110 coefficientQP110R2 ∧
    releaseCompactR61RowOK 2 111 coefficientQP111R2 ∧
    releaseCompactR61RowOK 2 112 coefficientQP112R2 ∧
    releaseCompactR61RowOK 2 113 coefficientQP113R2 ∧
    releaseCompactR61RowOK 2 114 coefficientQP114R2 ∧
    releaseCompactR61RowOK 2 115 coefficientQP115R2 ∧
    releaseCompactR61RowOK 2 116 coefficientQP116R2 ∧
    releaseCompactR61RowOK 2 117 coefficientQP117R2 ∧
    releaseCompactR61RowOK 2 118 coefficientQP118R2 ∧
    releaseCompactR61RowOK 2 119 coefficientQP119R2 ∧
    releaseCompactR61RowOK 2 120 coefficientQP120R2 ∧
    releaseCompactR61RowOK 2 121 coefficientQP121R2 ∧
    releaseCompactR61RowOK 2 122 coefficientQP122R2 ∧
    releaseCompactR61RowOK 2 123 coefficientQP123R2 ∧
    releaseCompactR61RowOK 2 124 coefficientQP124R2 ∧
    releaseCompactR61RowOK 2 125 coefficientQP125R2 := by
  unfold releaseCompactR61RowOK
  native_decide

theorem coefficientP096R2_eq_released : releasedParentCoefficient 2 96 = (coefficientQP096R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 96 coefficientQP096R2
    releaseCompactR61CohortR2P096P125Check.1

theorem coefficientP097R2_eq_released : releasedParentCoefficient 2 97 = (coefficientQP097R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 97 coefficientQP097R2
    releaseCompactR61CohortR2P096P125Check.2.1

theorem coefficientP098R2_eq_released : releasedParentCoefficient 2 98 = (coefficientQP098R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 98 coefficientQP098R2
    releaseCompactR61CohortR2P096P125Check.2.2.1

theorem coefficientP099R2_eq_released : releasedParentCoefficient 2 99 = (coefficientQP099R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 99 coefficientQP099R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.1

theorem coefficientP100R2_eq_released : releasedParentCoefficient 2 100 = (coefficientQP100R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 100 coefficientQP100R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.1

theorem coefficientP101R2_eq_released : releasedParentCoefficient 2 101 = (coefficientQP101R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 101 coefficientQP101R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.1

theorem coefficientP102R2_eq_released : releasedParentCoefficient 2 102 = (coefficientQP102R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 102 coefficientQP102R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.1

theorem coefficientP103R2_eq_released : releasedParentCoefficient 2 103 = (coefficientQP103R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 103 coefficientQP103R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.1

theorem coefficientP104R2_eq_released : releasedParentCoefficient 2 104 = (coefficientQP104R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 104 coefficientQP104R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.1

theorem coefficientP105R2_eq_released : releasedParentCoefficient 2 105 = (coefficientQP105R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 105 coefficientQP105R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.1

theorem coefficientP106R2_eq_released : releasedParentCoefficient 2 106 = (coefficientQP106R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 106 coefficientQP106R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP107R2_eq_released : releasedParentCoefficient 2 107 = (coefficientQP107R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 107 coefficientQP107R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP108R2_eq_released : releasedParentCoefficient 2 108 = (coefficientQP108R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 108 coefficientQP108R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP109R2_eq_released : releasedParentCoefficient 2 109 = (coefficientQP109R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 109 coefficientQP109R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP110R2_eq_released : releasedParentCoefficient 2 110 = (coefficientQP110R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 110 coefficientQP110R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP111R2_eq_released : releasedParentCoefficient 2 111 = (coefficientQP111R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 111 coefficientQP111R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP112R2_eq_released : releasedParentCoefficient 2 112 = (coefficientQP112R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 112 coefficientQP112R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP113R2_eq_released : releasedParentCoefficient 2 113 = (coefficientQP113R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 113 coefficientQP113R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP114R2_eq_released : releasedParentCoefficient 2 114 = (coefficientQP114R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 114 coefficientQP114R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP115R2_eq_released : releasedParentCoefficient 2 115 = (coefficientQP115R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 115 coefficientQP115R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP116R2_eq_released : releasedParentCoefficient 2 116 = (coefficientQP116R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 116 coefficientQP116R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP117R2_eq_released : releasedParentCoefficient 2 117 = (coefficientQP117R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 117 coefficientQP117R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP118R2_eq_released : releasedParentCoefficient 2 118 = (coefficientQP118R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 118 coefficientQP118R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP119R2_eq_released : releasedParentCoefficient 2 119 = (coefficientQP119R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 119 coefficientQP119R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP120R2_eq_released : releasedParentCoefficient 2 120 = (coefficientQP120R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 120 coefficientQP120R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP121R2_eq_released : releasedParentCoefficient 2 121 = (coefficientQP121R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 121 coefficientQP121R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP122R2_eq_released : releasedParentCoefficient 2 122 = (coefficientQP122R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 122 coefficientQP122R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP123R2_eq_released : releasedParentCoefficient 2 123 = (coefficientQP123R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 123 coefficientQP123R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP124R2_eq_released : releasedParentCoefficient 2 124 = (coefficientQP124R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 124 coefficientQP124R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1

theorem coefficientP125R2_eq_released : releasedParentCoefficient 2 125 = (coefficientQP125R2 : Real) :=
  releaseCompactR61Coefficient_eq_of_rowOK 2 125 coefficientQP125R2
    releaseCompactR61CohortR2P096P125Check.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2

end OmegaBound.ADVXXZT6Round61
